// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id) VALUES ($1,$2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1,$2)
ON CONFLICT DO NOTHING
`

type AddUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.RoleID)
	return err
}

const createDeviceTemplate = `-- name: CreateDeviceTemplate :one
INSERT INTO device_templates (name, vendor, device_type, discovery_rules, monitoring_rules, classification_rules, enabled)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, name, vendor, device_type, discovery_rules, monitoring_rules, classification_rules, enabled, created_at, updated_at
`

type CreateDeviceTemplateParams struct {
	Name                string `json:"name"`
	Vendor              string `json:"vendor"`
	DeviceType          string `json:"device_type"`
	DiscoveryRules      []byte `json:"discovery_rules"`
	MonitoringRules     []byte `json:"monitoring_rules"`
	ClassificationRules []byte `json:"classification_rules"`
	Enabled             bool   `json:"enabled"`
}

func (q *Queries) CreateDeviceTemplate(ctx context.Context, arg CreateDeviceTemplateParams) (DeviceTemplate, error) {
	row := q.db.QueryRow(ctx, createDeviceTemplate,
		arg.Name,
		arg.Vendor,
		arg.DeviceType,
		arg.DiscoveryRules,
		arg.MonitoringRules,
		arg.ClassificationRules,
		arg.Enabled,
	)
	var i DeviceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Vendor,
		&i.DeviceType,
		&i.DiscoveryRules,
		&i.MonitoringRules,
		&i.ClassificationRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (code, description) VALUES ($1,$2) RETURNING id, code, description, created_at
`

type CreatePermissionParams struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Code, arg.Description)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description) VALUES ($1,$2) RETURNING id, name, description, created_at
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, full_name, email, is_active)
VALUES ($1,$2,$3,$4) RETURNING id, username, full_name, email, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVendorFingerprint = `-- name: CreateVendorFingerprint :one
INSERT INTO vendor_fingerprints (kind, pattern, vendor, device_type, confidence, enabled)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, kind, pattern, vendor, device_type, confidence, enabled, created_at
`

type CreateVendorFingerprintParams struct {
	Kind       string `json:"kind"`
	Pattern    string `json:"pattern"`
	Vendor     string `json:"vendor"`
	DeviceType string `json:"device_type"`
	Confidence int32  `json:"confidence"`
	Enabled    bool   `json:"enabled"`
}

func (q *Queries) CreateVendorFingerprint(ctx context.Context, arg CreateVendorFingerprintParams) (VendorFingerprint, error) {
	row := q.db.QueryRow(ctx, createVendorFingerprint,
		arg.Kind,
		arg.Pattern,
		arg.Vendor,
		arg.DeviceType,
		arg.Confidence,
		arg.Enabled,
	)
	var i VendorFingerprint
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Pattern,
		&i.Vendor,
		&i.DeviceType,
		&i.Confidence,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeviceTemplate = `-- name: DeleteDeviceTemplate :exec
DELETE FROM device_templates WHERE id=$1
`

func (q *Queries) DeleteDeviceTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceTemplate, id)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id=$1
`

func (q *Queries) DeletePermission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id=$1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id=$1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteVendorFingerprint = `-- name: DeleteVendorFingerprint :exec
DELETE FROM vendor_fingerprints WHERE id=$1
`

func (q *Queries) DeleteVendorFingerprint(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVendorFingerprint, id)
	return err
}

const getDeviceTemplate = `-- name: GetDeviceTemplate :one
SELECT id, name, vendor, device_type, discovery_rules, monitoring_rules, classification_rules, enabled, created_at, updated_at FROM device_templates WHERE id = $1
`

func (q *Queries) GetDeviceTemplate(ctx context.Context, id uuid.UUID) (DeviceTemplate, error) {
	row := q.db.QueryRow(ctx, getDeviceTemplate, id)
	var i DeviceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Vendor,
		&i.DeviceType,
		&i.DiscoveryRules,
		&i.MonitoringRules,
		&i.ClassificationRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_log (actor, action, category, entity_type, entity_id, summary, details)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type InsertAuditLogParams struct {
	Actor      string `json:"actor"`
	Action     string `json:"action"`
	Category   string `json:"category"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Summary    string `json:"summary"`
	Details    []byte `json:"details"`
}

// ===== Audit log ===========================================================
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Actor,
		arg.Action,
		arg.Category,
		arg.EntityType,
		arg.EntityID,
		arg.Summary,
		arg.Details,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, at, actor, action, category, entity_type, entity_id, summary, details FROM audit_log
WHERE ($2::text IS NULL OR category = $2)
ORDER BY at DESC
LIMIT $1
`

type ListAuditLogParams struct {
	Limit    int32   `json:"limit"`
	Category *string `json:"category"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.Limit, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Actor,
			&i.Action,
			&i.Category,
			&i.EntityType,
			&i.EntityID,
			&i.Summary,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTemplates = `-- name: ListDeviceTemplates :many

SELECT id, name, vendor, device_type, discovery_rules, monitoring_rules, classification_rules, enabled, created_at, updated_at FROM device_templates ORDER BY name
`

// ===== Device templates ====================================================
func (q *Queries) ListDeviceTemplates(ctx context.Context) ([]DeviceTemplate, error) {
	rows, err := q.db.Query(ctx, listDeviceTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceTemplate{}
	for rows.Next() {
		var i DeviceTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Vendor,
			&i.DeviceType,
			&i.DiscoveryRules,
			&i.MonitoringRules,
			&i.ClassificationRules,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, code, description, created_at FROM permissions ORDER BY code
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, created_at FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many

SELECT id, username, full_name, email, is_active, created_at, updated_at FROM users ORDER BY username
`

// ===== RBAC: users / roles / permissions ==================================
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorFingerprints = `-- name: ListVendorFingerprints :many

SELECT id, kind, pattern, vendor, device_type, confidence, enabled, created_at FROM vendor_fingerprints ORDER BY kind, vendor, pattern
`

// ===== Vendor fingerprints =================================================
func (q *Queries) ListVendorFingerprints(ctx context.Context) ([]VendorFingerprint, error) {
	rows, err := q.db.Query(ctx, listVendorFingerprints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorFingerprint{}
	for rows.Next() {
		var i VendorFingerprint
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Pattern,
			&i.Vendor,
			&i.DeviceType,
			&i.Confidence,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permissionsForRole = `-- name: PermissionsForRole :many
SELECT p.id, p.code, p.description, p.created_at FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1 ORDER BY p.code
`

func (q *Queries) PermissionsForRole(ctx context.Context, roleID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, permissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolesForUser = `-- name: RolesForUser :many
SELECT r.id, r.name, r.description, r.created_at FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1 ORDER BY r.name
`

func (q *Queries) RolesForUser(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, rolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRolePermissionsClear = `-- name: SetRolePermissionsClear :exec
DELETE FROM role_permissions WHERE role_id=$1
`

func (q *Queries) SetRolePermissionsClear(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setRolePermissionsClear, roleID)
	return err
}

const setUserRolesClear = `-- name: SetUserRolesClear :exec
DELETE FROM user_roles WHERE user_id=$1
`

func (q *Queries) SetUserRolesClear(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserRolesClear, userID)
	return err
}

const updateDeviceTemplate = `-- name: UpdateDeviceTemplate :one
UPDATE device_templates
SET name=$2, vendor=$3, device_type=$4, discovery_rules=$5, monitoring_rules=$6,
    classification_rules=$7, enabled=$8, updated_at=now()
WHERE id=$1 RETURNING id, name, vendor, device_type, discovery_rules, monitoring_rules, classification_rules, enabled, created_at, updated_at
`

type UpdateDeviceTemplateParams struct {
	ID                  uuid.UUID `json:"id"`
	Name                string    `json:"name"`
	Vendor              string    `json:"vendor"`
	DeviceType          string    `json:"device_type"`
	DiscoveryRules      []byte    `json:"discovery_rules"`
	MonitoringRules     []byte    `json:"monitoring_rules"`
	ClassificationRules []byte    `json:"classification_rules"`
	Enabled             bool      `json:"enabled"`
}

func (q *Queries) UpdateDeviceTemplate(ctx context.Context, arg UpdateDeviceTemplateParams) (DeviceTemplate, error) {
	row := q.db.QueryRow(ctx, updateDeviceTemplate,
		arg.ID,
		arg.Name,
		arg.Vendor,
		arg.DeviceType,
		arg.DiscoveryRules,
		arg.MonitoringRules,
		arg.ClassificationRules,
		arg.Enabled,
	)
	var i DeviceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Vendor,
		&i.DeviceType,
		&i.DiscoveryRules,
		&i.MonitoringRules,
		&i.ClassificationRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET full_name=$2, email=$3, is_active=$4, updated_at=now()
WHERE id=$1 RETURNING id, username, full_name, email, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVendorFingerprint = `-- name: UpdateVendorFingerprint :one
UPDATE vendor_fingerprints
SET kind=$2, pattern=$3, vendor=$4, device_type=$5, confidence=$6, enabled=$7
WHERE id=$1 RETURNING id, kind, pattern, vendor, device_type, confidence, enabled, created_at
`

type UpdateVendorFingerprintParams struct {
	ID         uuid.UUID `json:"id"`
	Kind       string    `json:"kind"`
	Pattern    string    `json:"pattern"`
	Vendor     string    `json:"vendor"`
	DeviceType string    `json:"device_type"`
	Confidence int32     `json:"confidence"`
	Enabled    bool      `json:"enabled"`
}

func (q *Queries) UpdateVendorFingerprint(ctx context.Context, arg UpdateVendorFingerprintParams) (VendorFingerprint, error) {
	row := q.db.QueryRow(ctx, updateVendorFingerprint,
		arg.ID,
		arg.Kind,
		arg.Pattern,
		arg.Vendor,
		arg.DeviceType,
		arg.Confidence,
		arg.Enabled,
	)
	var i VendorFingerprint
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Pattern,
		&i.Vendor,
		&i.DeviceType,
		&i.Confidence,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
