// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: alerting.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts SET status = 'acknowledged', acknowledged_at = now()
WHERE id = $1 AND status = 'open'
RETURNING id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at, acknowledged_by, escalated, escalated_at, fingerprint
`

func (q *Queries) AcknowledgeAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.Escalated,
		&i.EscalatedAt,
		&i.Fingerprint,
	)
	return i, err
}

const acknowledgeAlertBy = `-- name: AcknowledgeAlertBy :one
UPDATE alerts SET status = 'acknowledged', acknowledged_at = now(), acknowledged_by = $2
WHERE id = $1 AND status = 'open'
RETURNING id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at, acknowledged_by, escalated, escalated_at, fingerprint
`

type AcknowledgeAlertByParams struct {
	ID             uuid.UUID `json:"id"`
	AcknowledgedBy *string   `json:"acknowledged_by"`
}

func (q *Queries) AcknowledgeAlertBy(ctx context.Context, arg AcknowledgeAlertByParams) (Alert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlertBy, arg.ID, arg.AcknowledgedBy)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.Escalated,
		&i.EscalatedAt,
		&i.Fingerprint,
	)
	return i, err
}

const addAlertEvent = `-- name: AddAlertEvent :one

INSERT INTO alert_events (alert_id, kind, actor, note)
VALUES ($1,$2,$3,$4)
RETURNING id, alert_id, at, kind, actor, note
`

type AddAlertEventParams struct {
	AlertID uuid.UUID `json:"alert_id"`
	Kind    string    `json:"kind"`
	Actor   string    `json:"actor"`
	Note    string    `json:"note"`
}

// ---- Alert lifecycle timeline ---------------------------------------------
func (q *Queries) AddAlertEvent(ctx context.Context, arg AddAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, addAlertEvent,
		arg.AlertID,
		arg.Kind,
		arg.Actor,
		arg.Note,
	)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.At,
		&i.Kind,
		&i.Actor,
		&i.Note,
	)
	return i, err
}

const createAlertRule = `-- name: CreateAlertRule :one

INSERT INTO alert_rules (name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, escalate_after_minutes, condition, warn_threshold, crit_threshold)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, created_at, updated_at, escalate_after_minutes, condition, warn_threshold, crit_threshold
`

type CreateAlertRuleParams struct {
	Name                 string  `json:"name"`
	TriggerStatus        string  `json:"trigger_status"`
	MinFailures          int32   `json:"min_failures"`
	DeviceCategory       *string `json:"device_category"`
	Severity             string  `json:"severity"`
	AutoWorkOrder        bool    `json:"auto_work_order"`
	WorkOrderPriority    string  `json:"work_order_priority"`
	Enabled              bool    `json:"enabled"`
	EscalateAfterMinutes int32   `json:"escalate_after_minutes"`
	Condition            string  `json:"condition"`
	WarnThreshold        *int32  `json:"warn_threshold"`
	CritThreshold        *int32  `json:"crit_threshold"`
}

// ---- Alert rules ----------------------------------------------------------
func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.Name,
		arg.TriggerStatus,
		arg.MinFailures,
		arg.DeviceCategory,
		arg.Severity,
		arg.AutoWorkOrder,
		arg.WorkOrderPriority,
		arg.Enabled,
		arg.EscalateAfterMinutes,
		arg.Condition,
		arg.WarnThreshold,
		arg.CritThreshold,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerStatus,
		&i.MinFailures,
		&i.DeviceCategory,
		&i.Severity,
		&i.AutoWorkOrder,
		&i.WorkOrderPriority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EscalateAfterMinutes,
		&i.Condition,
		&i.WarnThreshold,
		&i.CritThreshold,
	)
	return i, err
}

const createMaintenanceWindow = `-- name: CreateMaintenanceWindow :one

INSERT INTO maintenance_windows (scope, device_id, location_id, reason, starts_at, ends_at, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, scope, device_id, location_id, reason, starts_at, ends_at, created_by, created_at
`

type CreateMaintenanceWindowParams struct {
	Scope      string     `json:"scope"`
	DeviceID   *uuid.UUID `json:"device_id"`
	LocationID *uuid.UUID `json:"location_id"`
	Reason     string     `json:"reason"`
	StartsAt   time.Time  `json:"starts_at"`
	EndsAt     time.Time  `json:"ends_at"`
	CreatedBy  string     `json:"created_by"`
}

// ---- Maintenance windows (alert suppression) ------------------------------
func (q *Queries) CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, createMaintenanceWindow,
		arg.Scope,
		arg.DeviceID,
		arg.LocationID,
		arg.Reason,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.DeviceID,
		&i.LocationID,
		&i.Reason,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules WHERE id = $1
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertRule, id)
	return err
}

const deleteMaintenanceWindow = `-- name: DeleteMaintenanceWindow :exec
DELETE FROM maintenance_windows WHERE id = $1
`

func (q *Queries) DeleteMaintenanceWindow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceWindow, id)
	return err
}

const deviceCollectionRecency = `-- name: DeviceCollectionRecency :many
SELECT d.id AS device_id, d.name, d.primary_ip,
  GREATEST(
    COALESCE((SELECT max(collected_at) FROM os_inventory oi WHERE oi.device_id = d.id), 'epoch'),
    COALESCE((SELECT max(collected_at) FROM vh_collection_health h WHERE h.device_id = d.id AND h.status = 'ok'), 'epoch'),
    COALESCE((SELECT max(tested_at) FROM credential_test_results c WHERE c.device_id = d.id AND c.success), 'epoch')
  )::timestamptz AS last_success
FROM devices d WHERE d.deleted_at IS NULL
`

type DeviceCollectionRecencyRow struct {
	DeviceID    uuid.UUID   `json:"device_id"`
	Name        string      `json:"name"`
	PrimaryIp   *netip.Addr `json:"primary_ip"`
	LastSuccess time.Time   `json:"last_success"`
}

// Most recent successful collection signal per device (deep OS inventory, ok virtualization
// collection, or a successful credential test) — feeds the collection-stale state alert.
func (q *Queries) DeviceCollectionRecency(ctx context.Context) ([]DeviceCollectionRecencyRow, error) {
	rows, err := q.db.Query(ctx, deviceCollectionRecency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceCollectionRecencyRow{}
	for rows.Next() {
		var i DeviceCollectionRecencyRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Name,
			&i.PrimaryIp,
			&i.LastSuccess,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const escalateStaleAlerts = `-- name: EscalateStaleAlerts :many
UPDATE alerts a SET escalated = true, escalated_at = now()
FROM alert_rules r
WHERE a.rule_id = r.id
  AND a.status = 'open'
  AND a.escalated = false
  AND r.escalate_after_minutes > 0
  AND a.opened_at < now() - make_interval(mins => r.escalate_after_minutes)
RETURNING a.id, a.device_id, a.message, a.work_order_id, a.severity
`

type EscalateStaleAlertsRow struct {
	ID          uuid.UUID  `json:"id"`
	DeviceID    *uuid.UUID `json:"device_id"`
	Message     string     `json:"message"`
	WorkOrderID *uuid.UUID `json:"work_order_id"`
	Severity    string     `json:"severity"`
}

// Mark open, unacknowledged, not-yet-escalated alerts as escalated once they
// have aged past their rule's escalate_after_minutes (0 = never).
func (q *Queries) EscalateStaleAlerts(ctx context.Context) ([]EscalateStaleAlertsRow, error) {
	rows, err := q.db.Query(ctx, escalateStaleAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EscalateStaleAlertsRow{}
	for rows.Next() {
		var i EscalateStaleAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Message,
			&i.WorkOrderID,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlert = `-- name: GetAlert :one
SELECT id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at, acknowledged_by, escalated, escalated_at, fingerprint FROM alerts WHERE id = $1
`

func (q *Queries) GetAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.Escalated,
		&i.EscalatedAt,
		&i.Fingerprint,
	)
	return i, err
}

const listActiveMaintenanceWindows = `-- name: ListActiveMaintenanceWindows :many
SELECT id, scope, device_id, location_id, reason, starts_at, ends_at, created_by, created_at FROM maintenance_windows WHERE now() >= starts_at AND now() < ends_at
`

func (q *Queries) ListActiveMaintenanceWindows(ctx context.Context) ([]MaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listActiveMaintenanceWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.DeviceID,
			&i.LocationID,
			&i.Reason,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertEvents = `-- name: ListAlertEvents :many
SELECT id, alert_id, at, kind, actor, note FROM alert_events WHERE alert_id = $1 ORDER BY at
`

func (q *Queries) ListAlertEvents(ctx context.Context, alertID uuid.UUID) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertEvents, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertEvent{}
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.At,
			&i.Kind,
			&i.Actor,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, created_at, updated_at, escalate_after_minutes, condition, warn_threshold, crit_threshold FROM alert_rules ORDER BY created_at DESC
`

func (q *Queries) ListAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerStatus,
			&i.MinFailures,
			&i.DeviceCategory,
			&i.Severity,
			&i.AutoWorkOrder,
			&i.WorkOrderPriority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EscalateAfterMinutes,
			&i.Condition,
			&i.WarnThreshold,
			&i.CritThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at, acknowledged_by, escalated, escalated_at, fingerprint FROM alerts ORDER BY
    CASE status WHEN 'open' THEN 0 WHEN 'acknowledged' THEN 1 ELSE 2 END,
    opened_at DESC
LIMIT 500
`

func (q *Queries) ListAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.DeviceID,
			&i.CheckID,
			&i.Severity,
			&i.Status,
			&i.Message,
			&i.WorkOrderID,
			&i.OpenedAt,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
			&i.AcknowledgedBy,
			&i.Escalated,
			&i.EscalatedAt,
			&i.Fingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsEnriched = `-- name: ListAlertsEnriched :many
SELECT a.id, a.rule_id, a.device_id, a.check_id, a.severity, a.status, a.message,
       a.fingerprint, a.work_order_id, a.opened_at, a.acknowledged_at, a.acknowledged_by,
       a.escalated, a.escalated_at, a.resolved_at,
       r.name AS rule_name, r.condition AS condition,
       r.warn_threshold, r.crit_threshold,
       d.name AS device_name, d.primary_ip AS device_ip, d.category AS device_category,
       d.location_id AS device_location
FROM alerts a
JOIN alert_rules r ON r.id = a.rule_id
LEFT JOIN devices d ON d.id = a.device_id
ORDER BY CASE a.status WHEN 'open' THEN 0 WHEN 'acknowledged' THEN 1 ELSE 2 END, a.opened_at DESC
LIMIT 2000
`

type ListAlertsEnrichedRow struct {
	ID             uuid.UUID   `json:"id"`
	RuleID         uuid.UUID   `json:"rule_id"`
	DeviceID       *uuid.UUID  `json:"device_id"`
	CheckID        *uuid.UUID  `json:"check_id"`
	Severity       string      `json:"severity"`
	Status         string      `json:"status"`
	Message        string      `json:"message"`
	Fingerprint    string      `json:"fingerprint"`
	WorkOrderID    *uuid.UUID  `json:"work_order_id"`
	OpenedAt       time.Time   `json:"opened_at"`
	AcknowledgedAt *time.Time  `json:"acknowledged_at"`
	AcknowledgedBy *string     `json:"acknowledged_by"`
	Escalated      bool        `json:"escalated"`
	EscalatedAt    *time.Time  `json:"escalated_at"`
	ResolvedAt     *time.Time  `json:"resolved_at"`
	RuleName       string      `json:"rule_name"`
	Condition      string      `json:"condition"`
	WarnThreshold  *int32      `json:"warn_threshold"`
	CritThreshold  *int32      `json:"crit_threshold"`
	DeviceName     *string     `json:"device_name"`
	DeviceIp       *netip.Addr `json:"device_ip"`
	DeviceCategory *string     `json:"device_category"`
	DeviceLocation *uuid.UUID  `json:"device_location"`
}

// Alerts joined with their rule (name + condition) and device (name/ip/category/site) so the
// Alerts page can group, filter, and show clear per-alert context without extra round-trips.
func (q *Queries) ListAlertsEnriched(ctx context.Context) ([]ListAlertsEnrichedRow, error) {
	rows, err := q.db.Query(ctx, listAlertsEnriched)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsEnrichedRow{}
	for rows.Next() {
		var i ListAlertsEnrichedRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.DeviceID,
			&i.CheckID,
			&i.Severity,
			&i.Status,
			&i.Message,
			&i.Fingerprint,
			&i.WorkOrderID,
			&i.OpenedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.Escalated,
			&i.EscalatedAt,
			&i.ResolvedAt,
			&i.RuleName,
			&i.Condition,
			&i.WarnThreshold,
			&i.CritThreshold,
			&i.DeviceName,
			&i.DeviceIp,
			&i.DeviceCategory,
			&i.DeviceLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCollectionHealth = `-- name: ListAllCollectionHealth :many
SELECT h.device_id, d.name, d.primary_ip, h.collector, h.status, h.detail, h.vm_count, h.collected_at
FROM vh_collection_health h JOIN devices d ON d.id = h.device_id
`

type ListAllCollectionHealthRow struct {
	DeviceID    uuid.UUID   `json:"device_id"`
	Name        string      `json:"name"`
	PrimaryIp   *netip.Addr `json:"primary_ip"`
	Collector   string      `json:"collector"`
	Status      string      `json:"status"`
	Detail      *string     `json:"detail"`
	VmCount     *int32      `json:"vm_count"`
	CollectedAt time.Time   `json:"collected_at"`
}

func (q *Queries) ListAllCollectionHealth(ctx context.Context) ([]ListAllCollectionHealthRow, error) {
	rows, err := q.db.Query(ctx, listAllCollectionHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCollectionHealthRow{}
	for rows.Next() {
		var i ListAllCollectionHealthRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Name,
			&i.PrimaryIp,
			&i.Collector,
			&i.Status,
			&i.Detail,
			&i.VmCount,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDatastores = `-- name: ListAllDatastores :many
SELECT ds.host_device_id, d.name AS host_name, d.primary_ip, ds.name, ds.capacity_bytes, ds.free_bytes
FROM vh_datastores ds JOIN devices d ON d.id = ds.host_device_id WHERE ds.capacity_bytes > 0
`

type ListAllDatastoresRow struct {
	HostDeviceID  uuid.UUID   `json:"host_device_id"`
	HostName      string      `json:"host_name"`
	PrimaryIp     *netip.Addr `json:"primary_ip"`
	Name          string      `json:"name"`
	CapacityBytes *int64      `json:"capacity_bytes"`
	FreeBytes     *int64      `json:"free_bytes"`
}

func (q *Queries) ListAllDatastores(ctx context.Context) ([]ListAllDatastoresRow, error) {
	rows, err := q.db.Query(ctx, listAllDatastores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDatastoresRow{}
	for rows.Next() {
		var i ListAllDatastoresRow
		if err := rows.Scan(
			&i.HostDeviceID,
			&i.HostName,
			&i.PrimaryIp,
			&i.Name,
			&i.CapacityBytes,
			&i.FreeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRules = `-- name: ListEnabledAlertRules :many
SELECT id, name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, created_at, updated_at, escalate_after_minutes, condition, warn_threshold, crit_threshold FROM alert_rules WHERE enabled AND condition = 'check' ORDER BY created_at
`

// Check-status rules only — the check engine matches these against monitoring checks.
func (q *Queries) ListEnabledAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listEnabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerStatus,
			&i.MinFailures,
			&i.DeviceCategory,
			&i.Severity,
			&i.AutoWorkOrder,
			&i.WorkOrderPriority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EscalateAfterMinutes,
			&i.Condition,
			&i.WarnThreshold,
			&i.CritThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChecksWithDevice = `-- name: ListEnabledChecksWithDevice :many

SELECT c.id, c.device_id, c.kind, c.target_port, c.last_status, c.consecutive_failures,
       d.name AS device_name, d.category AS device_category, d.primary_ip AS device_ip,
       d.location_id AS device_location_id
FROM monitoring_checks c
JOIN devices d ON d.id = c.device_id
WHERE c.enabled AND c.role IS DISTINCT FROM 'supplemental'
`

type ListEnabledChecksWithDeviceRow struct {
	ID                  uuid.UUID   `json:"id"`
	DeviceID            uuid.UUID   `json:"device_id"`
	Kind                string      `json:"kind"`
	TargetPort          *int32      `json:"target_port"`
	LastStatus          string      `json:"last_status"`
	ConsecutiveFailures int32       `json:"consecutive_failures"`
	DeviceName          string      `json:"device_name"`
	DeviceCategory      string      `json:"device_category"`
	DeviceIp            *netip.Addr `json:"device_ip"`
	DeviceLocationID    *uuid.UUID  `json:"device_location_id"`
}

// ---- Monitoring state for evaluation --------------------------------------
// The evaluator's input: every enabled check joined to its device so rules
// can filter by category and alerts can carry a readable device name.
// SUPPLEMENTAL checks (e.g. SNMP sysUpTime health) are EXCLUDED — they only
// degrade a device to "warning" for visibility and must NEVER raise an alert.
func (q *Queries) ListEnabledChecksWithDevice(ctx context.Context) ([]ListEnabledChecksWithDeviceRow, error) {
	rows, err := q.db.Query(ctx, listEnabledChecksWithDevice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledChecksWithDeviceRow{}
	for rows.Next() {
		var i ListEnabledChecksWithDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Kind,
			&i.TargetPort,
			&i.LastStatus,
			&i.ConsecutiveFailures,
			&i.DeviceName,
			&i.DeviceCategory,
			&i.DeviceIp,
			&i.DeviceLocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledStateRules = `-- name: ListEnabledStateRules :many
SELECT id, name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, created_at, updated_at, escalate_after_minutes, condition, warn_threshold, crit_threshold FROM alert_rules WHERE enabled AND condition <> 'check' ORDER BY created_at
`

// State-based rules — evaluated by the device-state evaluator (api/alert_state.go), not checks.
func (q *Queries) ListEnabledStateRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listEnabledStateRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerStatus,
			&i.MinFailures,
			&i.DeviceCategory,
			&i.Severity,
			&i.AutoWorkOrder,
			&i.WorkOrderPriority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EscalateAfterMinutes,
			&i.Condition,
			&i.WarnThreshold,
			&i.CritThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceWindows = `-- name: ListMaintenanceWindows :many
SELECT id, scope, device_id, location_id, reason, starts_at, ends_at, created_by, created_at FROM maintenance_windows ORDER BY starts_at DESC LIMIT 200
`

func (q *Queries) ListMaintenanceWindows(ctx context.Context) ([]MaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.DeviceID,
			&i.LocationID,
			&i.Reason,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenStateAlertsByRule = `-- name: ListOpenStateAlertsByRule :many
SELECT id, device_id, fingerprint FROM alerts
WHERE rule_id = $1 AND check_id IS NULL AND status <> 'resolved'
`

type ListOpenStateAlertsByRuleRow struct {
	ID          uuid.UUID  `json:"id"`
	DeviceID    *uuid.UUID `json:"device_id"`
	Fingerprint string     `json:"fingerprint"`
}

func (q *Queries) ListOpenStateAlertsByRule(ctx context.Context, ruleID uuid.UUID) ([]ListOpenStateAlertsByRuleRow, error) {
	rows, err := q.db.Query(ctx, listOpenStateAlertsByRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenStateAlertsByRuleRow{}
	for rows.Next() {
		var i ListOpenStateAlertsByRuleRow
		if err := rows.Scan(&i.ID, &i.DeviceID, &i.Fingerprint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openAlert = `-- name: OpenAlert :one

INSERT INTO alerts (rule_id, device_id, check_id, severity, message)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (rule_id, check_id) WHERE status <> 'resolved' DO NOTHING
RETURNING id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at, acknowledged_by, escalated, escalated_at, fingerprint
`

type OpenAlertParams struct {
	RuleID   uuid.UUID  `json:"rule_id"`
	DeviceID *uuid.UUID `json:"device_id"`
	CheckID  *uuid.UUID `json:"check_id"`
	Severity string     `json:"severity"`
	Message  string     `json:"message"`
}

// ---- Alerts ---------------------------------------------------------------
// Atomic open: ON CONFLICT against idx_alerts_one_open means a second open
// for the same (rule, check) is a no-op. RETURNING yields a row ONLY on a
// real insert, so the engine fires the work-order bridge exactly once.
func (q *Queries) OpenAlert(ctx context.Context, arg OpenAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, openAlert,
		arg.RuleID,
		arg.DeviceID,
		arg.CheckID,
		arg.Severity,
		arg.Message,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.Escalated,
		&i.EscalatedAt,
		&i.Fingerprint,
	)
	return i, err
}

const openAlertCountsByDevice = `-- name: OpenAlertCountsByDevice :many
SELECT device_id, COUNT(*)::bigint AS n
FROM alerts WHERE status <> 'resolved' AND device_id IS NOT NULL
GROUP BY device_id
`

type OpenAlertCountsByDeviceRow struct {
	DeviceID *uuid.UUID `json:"device_id"`
	N        int64      `json:"n"`
}

// Open (unresolved) alert counts per device, for site rollups.
func (q *Queries) OpenAlertCountsByDevice(ctx context.Context) ([]OpenAlertCountsByDeviceRow, error) {
	rows, err := q.db.Query(ctx, openAlertCountsByDevice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenAlertCountsByDeviceRow{}
	for rows.Next() {
		var i OpenAlertCountsByDeviceRow
		if err := rows.Scan(&i.DeviceID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openStateAlert = `-- name: OpenStateAlert :one

INSERT INTO alerts (rule_id, device_id, check_id, severity, status, message, fingerprint)
VALUES ($1, $2, NULL, $3, 'open', $4, $5)
RETURNING id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at, acknowledged_by, escalated, escalated_at, fingerprint
`

type OpenStateAlertParams struct {
	RuleID      uuid.UUID  `json:"rule_id"`
	DeviceID    *uuid.UUID `json:"device_id"`
	Severity    string     `json:"severity"`
	Message     string     `json:"message"`
	Fingerprint string     `json:"fingerprint"`
}

// ---- State-based alerts (no check_id; dedup on rule_id + fingerprint) ------
// Opens a state alert. The evaluator checks existence first (single-threaded sweep), and the
// partial unique index (rule_id, fingerprint) WHERE check_id IS NULL is the race backstop.
func (q *Queries) OpenStateAlert(ctx context.Context, arg OpenStateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, openStateAlert,
		arg.RuleID,
		arg.DeviceID,
		arg.Severity,
		arg.Message,
		arg.Fingerprint,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.Escalated,
		&i.EscalatedAt,
		&i.Fingerprint,
	)
	return i, err
}

const resolveAlert = `-- name: ResolveAlert :one
UPDATE alerts SET status = 'resolved', resolved_at = now()
WHERE id = $1 AND status <> 'resolved'
RETURNING id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at, acknowledged_by, escalated, escalated_at, fingerprint
`

func (q *Queries) ResolveAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.Escalated,
		&i.EscalatedAt,
		&i.Fingerprint,
	)
	return i, err
}

const resolveAlertByID = `-- name: ResolveAlertByID :one
UPDATE alerts SET status = 'resolved', resolved_at = now() WHERE id = $1 AND status <> 'resolved' RETURNING id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at, acknowledged_by, escalated, escalated_at, fingerprint
`

func (q *Queries) ResolveAlertByID(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.Escalated,
		&i.EscalatedAt,
		&i.Fingerprint,
	)
	return i, err
}

const resolveRecoveredAlerts = `-- name: ResolveRecoveredAlerts :many
UPDATE alerts a SET status = 'resolved', resolved_at = now()
FROM monitoring_checks c
WHERE a.check_id = c.id AND a.status <> 'resolved' AND c.last_status = 'up'
RETURNING a.id, a.device_id, a.work_order_id, a.message
`

type ResolveRecoveredAlertsRow struct {
	ID          uuid.UUID  `json:"id"`
	DeviceID    *uuid.UUID `json:"device_id"`
	WorkOrderID *uuid.UUID `json:"work_order_id"`
	Message     string     `json:"message"`
}

// Auto-resolve: any un-resolved alert whose check has recovered to 'up'.
func (q *Queries) ResolveRecoveredAlerts(ctx context.Context) ([]ResolveRecoveredAlertsRow, error) {
	rows, err := q.db.Query(ctx, resolveRecoveredAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveRecoveredAlertsRow{}
	for rows.Next() {
		var i ResolveRecoveredAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.WorkOrderID,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAlertRuleEnabled = `-- name: SetAlertRuleEnabled :one
UPDATE alert_rules SET enabled = $2, updated_at = now() WHERE id = $1 RETURNING id, name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, created_at, updated_at, escalate_after_minutes, condition, warn_threshold, crit_threshold
`

type SetAlertRuleEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetAlertRuleEnabled(ctx context.Context, arg SetAlertRuleEnabledParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, setAlertRuleEnabled, arg.ID, arg.Enabled)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerStatus,
		&i.MinFailures,
		&i.DeviceCategory,
		&i.Severity,
		&i.AutoWorkOrder,
		&i.WorkOrderPriority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EscalateAfterMinutes,
		&i.Condition,
		&i.WarnThreshold,
		&i.CritThreshold,
	)
	return i, err
}

const setAlertWorkOrder = `-- name: SetAlertWorkOrder :exec
UPDATE alerts SET work_order_id = $2 WHERE id = $1
`

type SetAlertWorkOrderParams struct {
	ID          uuid.UUID  `json:"id"`
	WorkOrderID *uuid.UUID `json:"work_order_id"`
}

func (q *Queries) SetAlertWorkOrder(ctx context.Context, arg SetAlertWorkOrderParams) error {
	_, err := q.db.Exec(ctx, setAlertWorkOrder, arg.ID, arg.WorkOrderID)
	return err
}
