// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: alerting.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts SET status = 'acknowledged', acknowledged_at = now()
WHERE id = $1 AND status = 'open'
RETURNING id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at
`

func (q *Queries) AcknowledgeAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createAlertRule = `-- name: CreateAlertRule :one

INSERT INTO alert_rules (name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, created_at, updated_at
`

type CreateAlertRuleParams struct {
	Name              string  `json:"name"`
	TriggerStatus     string  `json:"trigger_status"`
	MinFailures       int32   `json:"min_failures"`
	DeviceCategory    *string `json:"device_category"`
	Severity          string  `json:"severity"`
	AutoWorkOrder     bool    `json:"auto_work_order"`
	WorkOrderPriority string  `json:"work_order_priority"`
	Enabled           bool    `json:"enabled"`
}

// ---- Alert rules ----------------------------------------------------------
func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.Name,
		arg.TriggerStatus,
		arg.MinFailures,
		arg.DeviceCategory,
		arg.Severity,
		arg.AutoWorkOrder,
		arg.WorkOrderPriority,
		arg.Enabled,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerStatus,
		&i.MinFailures,
		&i.DeviceCategory,
		&i.Severity,
		&i.AutoWorkOrder,
		&i.WorkOrderPriority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules WHERE id = $1
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertRule, id)
	return err
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, created_at, updated_at FROM alert_rules ORDER BY created_at DESC
`

func (q *Queries) ListAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerStatus,
			&i.MinFailures,
			&i.DeviceCategory,
			&i.Severity,
			&i.AutoWorkOrder,
			&i.WorkOrderPriority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at FROM alerts ORDER BY
    CASE status WHEN 'open' THEN 0 WHEN 'acknowledged' THEN 1 ELSE 2 END,
    opened_at DESC
LIMIT 500
`

func (q *Queries) ListAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.DeviceID,
			&i.CheckID,
			&i.Severity,
			&i.Status,
			&i.Message,
			&i.WorkOrderID,
			&i.OpenedAt,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRules = `-- name: ListEnabledAlertRules :many
SELECT id, name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, created_at, updated_at FROM alert_rules WHERE enabled ORDER BY created_at
`

func (q *Queries) ListEnabledAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listEnabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerStatus,
			&i.MinFailures,
			&i.DeviceCategory,
			&i.Severity,
			&i.AutoWorkOrder,
			&i.WorkOrderPriority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChecksWithDevice = `-- name: ListEnabledChecksWithDevice :many

SELECT c.id, c.device_id, c.kind, c.target_port, c.last_status, c.consecutive_failures,
       d.name AS device_name, d.category AS device_category, d.primary_ip AS device_ip
FROM monitoring_checks c
JOIN devices d ON d.id = c.device_id
WHERE c.enabled
`

type ListEnabledChecksWithDeviceRow struct {
	ID                  uuid.UUID   `json:"id"`
	DeviceID            uuid.UUID   `json:"device_id"`
	Kind                string      `json:"kind"`
	TargetPort          *int32      `json:"target_port"`
	LastStatus          string      `json:"last_status"`
	ConsecutiveFailures int32       `json:"consecutive_failures"`
	DeviceName          string      `json:"device_name"`
	DeviceCategory      string      `json:"device_category"`
	DeviceIp            *netip.Addr `json:"device_ip"`
}

// ---- Monitoring state for evaluation --------------------------------------
// The evaluator's input: every enabled check joined to its device so rules
// can filter by category and alerts can carry a readable device name.
func (q *Queries) ListEnabledChecksWithDevice(ctx context.Context) ([]ListEnabledChecksWithDeviceRow, error) {
	rows, err := q.db.Query(ctx, listEnabledChecksWithDevice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledChecksWithDeviceRow{}
	for rows.Next() {
		var i ListEnabledChecksWithDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Kind,
			&i.TargetPort,
			&i.LastStatus,
			&i.ConsecutiveFailures,
			&i.DeviceName,
			&i.DeviceCategory,
			&i.DeviceIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openAlert = `-- name: OpenAlert :one

INSERT INTO alerts (rule_id, device_id, check_id, severity, message)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (rule_id, check_id) WHERE status <> 'resolved' DO NOTHING
RETURNING id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at
`

type OpenAlertParams struct {
	RuleID   uuid.UUID  `json:"rule_id"`
	DeviceID uuid.UUID  `json:"device_id"`
	CheckID  *uuid.UUID `json:"check_id"`
	Severity string     `json:"severity"`
	Message  string     `json:"message"`
}

// ---- Alerts ---------------------------------------------------------------
// Atomic open: ON CONFLICT against idx_alerts_one_open means a second open
// for the same (rule, check) is a no-op. RETURNING yields a row ONLY on a
// real insert, so the engine fires the work-order bridge exactly once.
func (q *Queries) OpenAlert(ctx context.Context, arg OpenAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, openAlert,
		arg.RuleID,
		arg.DeviceID,
		arg.CheckID,
		arg.Severity,
		arg.Message,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const resolveAlert = `-- name: ResolveAlert :one
UPDATE alerts SET status = 'resolved', resolved_at = now()
WHERE id = $1 AND status <> 'resolved'
RETURNING id, rule_id, device_id, check_id, severity, status, message, work_order_id, opened_at, acknowledged_at, resolved_at
`

func (q *Queries) ResolveAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DeviceID,
		&i.CheckID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.WorkOrderID,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const resolveRecoveredAlerts = `-- name: ResolveRecoveredAlerts :many
UPDATE alerts a SET status = 'resolved', resolved_at = now()
FROM monitoring_checks c
WHERE a.check_id = c.id AND a.status <> 'resolved' AND c.last_status = 'up'
RETURNING a.id, a.device_id, a.work_order_id, a.message
`

type ResolveRecoveredAlertsRow struct {
	ID          uuid.UUID  `json:"id"`
	DeviceID    uuid.UUID  `json:"device_id"`
	WorkOrderID *uuid.UUID `json:"work_order_id"`
	Message     string     `json:"message"`
}

// Auto-resolve: any un-resolved alert whose check has recovered to 'up'.
func (q *Queries) ResolveRecoveredAlerts(ctx context.Context) ([]ResolveRecoveredAlertsRow, error) {
	rows, err := q.db.Query(ctx, resolveRecoveredAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveRecoveredAlertsRow{}
	for rows.Next() {
		var i ResolveRecoveredAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.WorkOrderID,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAlertRuleEnabled = `-- name: SetAlertRuleEnabled :one
UPDATE alert_rules SET enabled = $2, updated_at = now() WHERE id = $1 RETURNING id, name, trigger_status, min_failures, device_category, severity, auto_work_order, work_order_priority, enabled, created_at, updated_at
`

type SetAlertRuleEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetAlertRuleEnabled(ctx context.Context, arg SetAlertRuleEnabledParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, setAlertRuleEnabled, arg.ID, arg.Enabled)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerStatus,
		&i.MinFailures,
		&i.DeviceCategory,
		&i.Severity,
		&i.AutoWorkOrder,
		&i.WorkOrderPriority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAlertWorkOrder = `-- name: SetAlertWorkOrder :exec
UPDATE alerts SET work_order_id = $2 WHERE id = $1
`

type SetAlertWorkOrderParams struct {
	ID          uuid.UUID  `json:"id"`
	WorkOrderID *uuid.UUID `json:"work_order_id"`
}

func (q *Queries) SetAlertWorkOrder(ctx context.Context, arg SetAlertWorkOrderParams) error {
	_, err := q.db.Exec(ctx, setAlertWorkOrder, arg.ID, arg.WorkOrderID)
	return err
}
