// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: backup_runs.sql

package db

import (
	"context"
)

const insertBackupRun = `-- name: InsertBackupRun :one
INSERT INTO backup_runs (kind, status, tables, rows, size_bytes, actor, detail)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, at, kind, status, tables, rows, size_bytes, actor, detail
`

type InsertBackupRunParams struct {
	Kind      string `json:"kind"`
	Status    string `json:"status"`
	Tables    int32  `json:"tables"`
	Rows      int32  `json:"rows"`
	SizeBytes int64  `json:"size_bytes"`
	Actor     string `json:"actor"`
	Detail    string `json:"detail"`
}

func (q *Queries) InsertBackupRun(ctx context.Context, arg InsertBackupRunParams) (BackupRun, error) {
	row := q.db.QueryRow(ctx, insertBackupRun,
		arg.Kind,
		arg.Status,
		arg.Tables,
		arg.Rows,
		arg.SizeBytes,
		arg.Actor,
		arg.Detail,
	)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.Kind,
		&i.Status,
		&i.Tables,
		&i.Rows,
		&i.SizeBytes,
		&i.Actor,
		&i.Detail,
	)
	return i, err
}

const lastSuccessfulBackup = `-- name: LastSuccessfulBackup :one
SELECT id, at, kind, status, tables, rows, size_bytes, actor, detail FROM backup_runs WHERE status = 'success' ORDER BY at DESC LIMIT 1
`

func (q *Queries) LastSuccessfulBackup(ctx context.Context) (BackupRun, error) {
	row := q.db.QueryRow(ctx, lastSuccessfulBackup)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.Kind,
		&i.Status,
		&i.Tables,
		&i.Rows,
		&i.SizeBytes,
		&i.Actor,
		&i.Detail,
	)
	return i, err
}

const listBackupRuns = `-- name: ListBackupRuns :many
SELECT id, at, kind, status, tables, rows, size_bytes, actor, detail FROM backup_runs ORDER BY at DESC LIMIT 100
`

func (q *Queries) ListBackupRuns(ctx context.Context) ([]BackupRun, error) {
	rows, err := q.db.Query(ctx, listBackupRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupRun{}
	for rows.Next() {
		var i BackupRun
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Kind,
			&i.Status,
			&i.Tables,
			&i.Rows,
			&i.SizeBytes,
			&i.Actor,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
