// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cctv.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const getCameraInfo = `-- name: GetCameraInfo :one
SELECT device_id, manufacturer, model, resolution, rtsp_url, onvif_url, last_seen_at FROM camera_info WHERE device_id = $1
`

func (q *Queries) GetCameraInfo(ctx context.Context, deviceID uuid.UUID) (CameraInfo, error) {
	row := q.db.QueryRow(ctx, getCameraInfo, deviceID)
	var i CameraInfo
	err := row.Scan(
		&i.DeviceID,
		&i.Manufacturer,
		&i.Model,
		&i.Resolution,
		&i.RtspUrl,
		&i.OnvifUrl,
		&i.LastSeenAt,
	)
	return i, err
}

const listNVRChannels = `-- name: ListNVRChannels :many
SELECT id, nvr_device_id, channel_no, camera_name, camera_ip, camera_device_id, status, last_seen_at FROM nvr_channels WHERE nvr_device_id = $1 ORDER BY channel_no
`

func (q *Queries) ListNVRChannels(ctx context.Context, nvrDeviceID uuid.UUID) ([]NvrChannel, error) {
	rows, err := q.db.Query(ctx, listNVRChannels, nvrDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NvrChannel{}
	for rows.Next() {
		var i NvrChannel
		if err := rows.Scan(
			&i.ID,
			&i.NvrDeviceID,
			&i.ChannelNo,
			&i.CameraName,
			&i.CameraIp,
			&i.CameraDeviceID,
			&i.Status,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCameraInfo = `-- name: UpsertCameraInfo :one
INSERT INTO camera_info (device_id, manufacturer, model, resolution, rtsp_url, onvif_url)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (device_id) DO UPDATE SET
    manufacturer = EXCLUDED.manufacturer,
    model = EXCLUDED.model,
    resolution = EXCLUDED.resolution,
    rtsp_url = EXCLUDED.rtsp_url,
    onvif_url = EXCLUDED.onvif_url,
    last_seen_at = now()
RETURNING device_id, manufacturer, model, resolution, rtsp_url, onvif_url, last_seen_at
`

type UpsertCameraInfoParams struct {
	DeviceID     uuid.UUID `json:"device_id"`
	Manufacturer *string   `json:"manufacturer"`
	Model        *string   `json:"model"`
	Resolution   *string   `json:"resolution"`
	RtspUrl      *string   `json:"rtsp_url"`
	OnvifUrl     *string   `json:"onvif_url"`
}

func (q *Queries) UpsertCameraInfo(ctx context.Context, arg UpsertCameraInfoParams) (CameraInfo, error) {
	row := q.db.QueryRow(ctx, upsertCameraInfo,
		arg.DeviceID,
		arg.Manufacturer,
		arg.Model,
		arg.Resolution,
		arg.RtspUrl,
		arg.OnvifUrl,
	)
	var i CameraInfo
	err := row.Scan(
		&i.DeviceID,
		&i.Manufacturer,
		&i.Model,
		&i.Resolution,
		&i.RtspUrl,
		&i.OnvifUrl,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertNVRChannel = `-- name: UpsertNVRChannel :one
INSERT INTO nvr_channels (nvr_device_id, channel_no, camera_name, camera_ip, camera_device_id, status)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (nvr_device_id, channel_no) DO UPDATE SET
    camera_name = EXCLUDED.camera_name,
    camera_ip = EXCLUDED.camera_ip,
    camera_device_id = EXCLUDED.camera_device_id,
    status = EXCLUDED.status,
    last_seen_at = now()
RETURNING id, nvr_device_id, channel_no, camera_name, camera_ip, camera_device_id, status, last_seen_at
`

type UpsertNVRChannelParams struct {
	NvrDeviceID    uuid.UUID   `json:"nvr_device_id"`
	ChannelNo      int32       `json:"channel_no"`
	CameraName     *string     `json:"camera_name"`
	CameraIp       *netip.Addr `json:"camera_ip"`
	CameraDeviceID *uuid.UUID  `json:"camera_device_id"`
	Status         string      `json:"status"`
}

func (q *Queries) UpsertNVRChannel(ctx context.Context, arg UpsertNVRChannelParams) (NvrChannel, error) {
	row := q.db.QueryRow(ctx, upsertNVRChannel,
		arg.NvrDeviceID,
		arg.ChannelNo,
		arg.CameraName,
		arg.CameraIp,
		arg.CameraDeviceID,
		arg.Status,
	)
	var i NvrChannel
	err := row.Scan(
		&i.ID,
		&i.NvrDeviceID,
		&i.ChannelNo,
		&i.CameraName,
		&i.CameraIp,
		&i.CameraDeviceID,
		&i.Status,
		&i.LastSeenAt,
	)
	return i, err
}
