// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: devices.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const addDeviceRole = `-- name: AddDeviceRole :exec
INSERT INTO device_roles (device_id, role, source)
VALUES ($1, $2, $3)
ON CONFLICT (device_id, role) DO NOTHING
`

type AddDeviceRoleParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	Role     string    `json:"role"`
	Source   string    `json:"source"`
}

func (q *Queries) AddDeviceRole(ctx context.Context, arg AddDeviceRoleParams) error {
	_, err := q.db.Exec(ctx, addDeviceRole, arg.DeviceID, arg.Role, arg.Source)
	return err
}

const bulkAssignClassification = `-- name: BulkAssignClassification :execrows
UPDATE devices SET
    vlan = COALESCE($1, vlan),
    device_class = COALESCE($2, device_class),
    location_id = COALESCE($3, location_id),
    updated_at = now()
WHERE id = ANY($4::uuid[]) AND deleted_at IS NULL
`

type BulkAssignClassificationParams struct {
	Vlan        *string     `json:"vlan"`
	DeviceClass *string     `json:"device_class"`
	LocationID  *uuid.UUID  `json:"location_id"`
	Ids         []uuid.UUID `json:"ids"`
}

// Assign vlan/device_class/location to many devices at once (multi-select).
// Only the provided (non-null) fields are changed — COALESCE keeps the rest —
// so an operator can set just location, just class, just vlan, or any combo.
func (q *Queries) BulkAssignClassification(ctx context.Context, arg BulkAssignClassificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkAssignClassification,
		arg.Vlan,
		arg.DeviceClass,
		arg.LocationID,
		arg.Ids,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    location_id, primary_ip, hostname, name, vendor, model, serial,
    os_version, category, status, driver, credential_id, metadata,
    vlan, device_class, location
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
RETURNING id, location_id, primary_ip, hostname, name, vendor, model, serial, os_version, category, status, driver, credential_id, last_discovery_at, last_monitoring_at, metadata, created_at, updated_at, deleted_at, vlan, device_class, location
`

type CreateDeviceParams struct {
	LocationID   *uuid.UUID  `json:"location_id"`
	PrimaryIp    *netip.Addr `json:"primary_ip"`
	Hostname     *string     `json:"hostname"`
	Name         string      `json:"name"`
	Vendor       *string     `json:"vendor"`
	Model        *string     `json:"model"`
	Serial       *string     `json:"serial"`
	OsVersion    *string     `json:"os_version"`
	Category     string      `json:"category"`
	Status       string      `json:"status"`
	Driver       *string     `json:"driver"`
	CredentialID *uuid.UUID  `json:"credential_id"`
	Metadata     []byte      `json:"metadata"`
	Vlan         *string     `json:"vlan"`
	DeviceClass  *string     `json:"device_class"`
	Location     *string     `json:"location"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.LocationID,
		arg.PrimaryIp,
		arg.Hostname,
		arg.Name,
		arg.Vendor,
		arg.Model,
		arg.Serial,
		arg.OsVersion,
		arg.Category,
		arg.Status,
		arg.Driver,
		arg.CredentialID,
		arg.Metadata,
		arg.Vlan,
		arg.DeviceClass,
		arg.Location,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PrimaryIp,
		&i.Hostname,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.OsVersion,
		&i.Category,
		&i.Status,
		&i.Driver,
		&i.CredentialID,
		&i.LastDiscoveryAt,
		&i.LastMonitoringAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Vlan,
		&i.DeviceClass,
		&i.Location,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1
`

// Hard delete (cascades to inventory child rows via FK ON DELETE CASCADE).
func (q *Queries) DeleteDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevice, id)
	return err
}

const deleteDevices = `-- name: DeleteDevices :execrows
DELETE FROM devices WHERE id = ANY($1::uuid[])
`

// Bulk hard delete (multi-select). Returns the number of rows removed.
func (q *Queries) DeleteDevices(ctx context.Context, dollar_1 []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevices, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDevice = `-- name: GetDevice :one
SELECT id, location_id, primary_ip, hostname, name, vendor, model, serial, os_version, category, status, driver, credential_id, last_discovery_at, last_monitoring_at, metadata, created_at, updated_at, deleted_at, vlan, device_class, location FROM devices WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDevice(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PrimaryIp,
		&i.Hostname,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.OsVersion,
		&i.Category,
		&i.Status,
		&i.Driver,
		&i.CredentialID,
		&i.LastDiscoveryAt,
		&i.LastMonitoringAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Vlan,
		&i.DeviceClass,
		&i.Location,
	)
	return i, err
}

const listAllDevices = `-- name: ListAllDevices :many
SELECT id, location_id, primary_ip, hostname, name, vendor, model, serial, os_version, category, status, driver, credential_id, last_discovery_at, last_monitoring_at, metadata, created_at, updated_at, deleted_at, vlan, device_class, location FROM devices
WHERE deleted_at IS NULL
ORDER BY category, name
`

// Every live device (the Inventory page), ordered for grouped display.
func (q *Queries) ListAllDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listAllDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.PrimaryIp,
			&i.Hostname,
			&i.Name,
			&i.Vendor,
			&i.Model,
			&i.Serial,
			&i.OsVersion,
			&i.Category,
			&i.Status,
			&i.Driver,
			&i.CredentialID,
			&i.LastDiscoveryAt,
			&i.LastMonitoringAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Vlan,
			&i.DeviceClass,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceFacts = `-- name: ListDeviceFacts :many
SELECT id, device_id, key, value, value_json, driver, observed_at FROM device_facts WHERE device_id = $1 ORDER BY key
`

func (q *Queries) ListDeviceFacts(ctx context.Context, deviceID uuid.UUID) ([]DeviceFact, error) {
	rows, err := q.db.Query(ctx, listDeviceFacts, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceFact{}
	for rows.Next() {
		var i DeviceFact
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Key,
			&i.Value,
			&i.ValueJson,
			&i.Driver,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceRoles = `-- name: ListDeviceRoles :many
SELECT device_id, role, source, created_at FROM device_roles WHERE device_id = $1 ORDER BY role
`

func (q *Queries) ListDeviceRoles(ctx context.Context, deviceID uuid.UUID) ([]DeviceRole, error) {
	rows, err := q.db.Query(ctx, listDeviceRoles, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceRole{}
	for rows.Next() {
		var i DeviceRole
		if err := rows.Scan(
			&i.DeviceID,
			&i.Role,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByCategory = `-- name: ListDevicesByCategory :many
SELECT id, location_id, primary_ip, hostname, name, vendor, model, serial, os_version, category, status, driver, credential_id, last_discovery_at, last_monitoring_at, metadata, created_at, updated_at, deleted_at, vlan, device_class, location FROM devices
WHERE category = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListDevicesByCategory(ctx context.Context, category string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.PrimaryIp,
			&i.Hostname,
			&i.Name,
			&i.Vendor,
			&i.Model,
			&i.Serial,
			&i.OsVersion,
			&i.Category,
			&i.Status,
			&i.Driver,
			&i.CredentialID,
			&i.LastDiscoveryAt,
			&i.LastMonitoringAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Vlan,
			&i.DeviceClass,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByRole = `-- name: ListDevicesByRole :many
SELECT d.id, d.location_id, d.primary_ip, d.hostname, d.name, d.vendor, d.model, d.serial, d.os_version, d.category, d.status, d.driver, d.credential_id, d.last_discovery_at, d.last_monitoring_at, d.metadata, d.created_at, d.updated_at, d.deleted_at, d.vlan, d.device_class, d.location FROM devices d
JOIN device_roles r ON r.device_id = d.id
WHERE r.role = $1
ORDER BY d.name
`

func (q *Queries) ListDevicesByRole(ctx context.Context, role string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.PrimaryIp,
			&i.Hostname,
			&i.Name,
			&i.Vendor,
			&i.Model,
			&i.Serial,
			&i.OsVersion,
			&i.Category,
			&i.Status,
			&i.Driver,
			&i.CredentialID,
			&i.LastDiscoveryAt,
			&i.LastMonitoringAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Vlan,
			&i.DeviceClass,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveDeviceByIP = `-- name: LiveDeviceByIP :one
SELECT id, location_id, primary_ip, hostname, name, vendor, model, serial, os_version, category, status, driver, credential_id, last_discovery_at, last_monitoring_at, metadata, created_at, updated_at, deleted_at, vlan, device_class, location FROM devices
WHERE primary_ip = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT 1
`

// Reconcile key for an UNSCOPED scan (no site selected): match by primary_ip
// alone so a re-scan updates the existing device regardless of an
// operator-assigned location_id, instead of duplicating it. Most-recent wins.
func (q *Queries) LiveDeviceByIP(ctx context.Context, primaryIp *netip.Addr) (Device, error) {
	row := q.db.QueryRow(ctx, liveDeviceByIP, primaryIp)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PrimaryIp,
		&i.Hostname,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.OsVersion,
		&i.Category,
		&i.Status,
		&i.Driver,
		&i.CredentialID,
		&i.LastDiscoveryAt,
		&i.LastMonitoringAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Vlan,
		&i.DeviceClass,
		&i.Location,
	)
	return i, err
}

const liveDeviceByIPAndLocation = `-- name: LiveDeviceByIPAndLocation :one
SELECT id, location_id, primary_ip, hostname, name, vendor, model, serial, os_version, category, status, driver, credential_id, last_discovery_at, last_monitoring_at, metadata, created_at, updated_at, deleted_at, vlan, device_class, location FROM devices
WHERE primary_ip = $1 AND location_id IS NOT DISTINCT FROM $2 AND deleted_at IS NULL
`

type LiveDeviceByIPAndLocationParams struct {
	PrimaryIp  *netip.Addr `json:"primary_ip"`
	LocationID *uuid.UUID  `json:"location_id"`
}

// Identity reconciliation key (multi-hotel safe): same IP can recur across
// hotels, so a live device is unique by (primary_ip, location). location_id is
// matched NULL-safe (IS NOT DISTINCT FROM) so an unscoped scan (no site
// selected, location_id = NULL) still reconciles instead of duplicating.
func (q *Queries) LiveDeviceByIPAndLocation(ctx context.Context, arg LiveDeviceByIPAndLocationParams) (Device, error) {
	row := q.db.QueryRow(ctx, liveDeviceByIPAndLocation, arg.PrimaryIp, arg.LocationID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PrimaryIp,
		&i.Hostname,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.OsVersion,
		&i.Category,
		&i.Status,
		&i.Driver,
		&i.CredentialID,
		&i.LastDiscoveryAt,
		&i.LastMonitoringAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Vlan,
		&i.DeviceClass,
		&i.Location,
	)
	return i, err
}

const roleSummary = `-- name: RoleSummary :many
SELECT role, COUNT(*) AS count
FROM device_roles
GROUP BY role
ORDER BY count DESC, role
`

type RoleSummaryRow struct {
	Role  string `json:"role"`
	Count int64  `json:"count"`
}

// Fleet-wide role rollup: how many devices hold each role (the CMDB role cut).
func (q *Queries) RoleSummary(ctx context.Context) ([]RoleSummaryRow, error) {
	rows, err := q.db.Query(ctx, roleSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleSummaryRow{}
	for rows.Next() {
		var i RoleSummaryRow
		if err := rows.Scan(&i.Role, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceCredential = `-- name: SetDeviceCredential :exec
UPDATE devices SET credential_id = $2, updated_at = now() WHERE id = $1
`

type SetDeviceCredentialParams struct {
	ID           uuid.UUID  `json:"id"`
	CredentialID *uuid.UUID `json:"credential_id"`
}

// Bind-on-success: record the credential that last authenticated.
func (q *Queries) SetDeviceCredential(ctx context.Context, arg SetDeviceCredentialParams) error {
	_, err := q.db.Exec(ctx, setDeviceCredential, arg.ID, arg.CredentialID)
	return err
}

const touchDeviceDiscovery = `-- name: TouchDeviceDiscovery :exec
UPDATE devices SET last_discovery_at = $2, updated_at = now() WHERE id = $1
`

type TouchDeviceDiscoveryParams struct {
	ID              uuid.UUID  `json:"id"`
	LastDiscoveryAt *time.Time `json:"last_discovery_at"`
}

func (q *Queries) TouchDeviceDiscovery(ctx context.Context, arg TouchDeviceDiscoveryParams) error {
	_, err := q.db.Exec(ctx, touchDeviceDiscovery, arg.ID, arg.LastDiscoveryAt)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices SET
    name = $2, category = $3, vendor = $4, model = $5, serial = $6,
    os_version = $7, hostname = $8, vlan = $9, device_class = $10,
    location = $11, location_id = $12, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, location_id, primary_ip, hostname, name, vendor, model, serial, os_version, category, status, driver, credential_id, last_discovery_at, last_monitoring_at, metadata, created_at, updated_at, deleted_at, vlan, device_class, location
`

type UpdateDeviceParams struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Category    string     `json:"category"`
	Vendor      *string    `json:"vendor"`
	Model       *string    `json:"model"`
	Serial      *string    `json:"serial"`
	OsVersion   *string    `json:"os_version"`
	Hostname    *string    `json:"hostname"`
	Vlan        *string    `json:"vlan"`
	DeviceClass *string    `json:"device_class"`
	Location    *string    `json:"location"`
	LocationID  *uuid.UUID `json:"location_id"`
}

// Operator edit of a device's identity fields (Inventory CRUD).
func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Vendor,
		arg.Model,
		arg.Serial,
		arg.OsVersion,
		arg.Hostname,
		arg.Vlan,
		arg.DeviceClass,
		arg.Location,
		arg.LocationID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PrimaryIp,
		&i.Hostname,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.OsVersion,
		&i.Category,
		&i.Status,
		&i.Driver,
		&i.CredentialID,
		&i.LastDiscoveryAt,
		&i.LastMonitoringAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Vlan,
		&i.DeviceClass,
		&i.Location,
	)
	return i, err
}

const updateDiscoveredDevice = `-- name: UpdateDiscoveredDevice :one
UPDATE devices SET
    hostname = $2, name = $3, vendor = $4, model = $5, serial = $6,
    os_version = $7, category = $8, driver = $9, status = $10,
    last_discovery_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, location_id, primary_ip, hostname, name, vendor, model, serial, os_version, category, status, driver, credential_id, last_discovery_at, last_monitoring_at, metadata, created_at, updated_at, deleted_at, vlan, device_class, location
`

type UpdateDiscoveredDeviceParams struct {
	ID        uuid.UUID `json:"id"`
	Hostname  *string   `json:"hostname"`
	Name      string    `json:"name"`
	Vendor    *string   `json:"vendor"`
	Model     *string   `json:"model"`
	Serial    *string   `json:"serial"`
	OsVersion *string   `json:"os_version"`
	Category  string    `json:"category"`
	Driver    *string   `json:"driver"`
	Status    string    `json:"status"`
}

// Reconcile path: refresh a live device's mutable identity fields on
// re-discovery (keyed by the caller to the (primary_ip, location) match).
func (q *Queries) UpdateDiscoveredDevice(ctx context.Context, arg UpdateDiscoveredDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDiscoveredDevice,
		arg.ID,
		arg.Hostname,
		arg.Name,
		arg.Vendor,
		arg.Model,
		arg.Serial,
		arg.OsVersion,
		arg.Category,
		arg.Driver,
		arg.Status,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PrimaryIp,
		&i.Hostname,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.Serial,
		&i.OsVersion,
		&i.Category,
		&i.Status,
		&i.Driver,
		&i.CredentialID,
		&i.LastDiscoveryAt,
		&i.LastMonitoringAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Vlan,
		&i.DeviceClass,
		&i.Location,
	)
	return i, err
}

const upsertDeviceFact = `-- name: UpsertDeviceFact :exec
INSERT INTO device_facts (device_id, key, value, value_json, driver, observed_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (device_id, key) DO UPDATE SET
    value = EXCLUDED.value,
    value_json = EXCLUDED.value_json,
    driver = EXCLUDED.driver,
    observed_at = now()
`

type UpsertDeviceFactParams struct {
	DeviceID  uuid.UUID `json:"device_id"`
	Key       string    `json:"key"`
	Value     *string   `json:"value"`
	ValueJson []byte    `json:"value_json"`
	Driver    string    `json:"driver"`
}

func (q *Queries) UpsertDeviceFact(ctx context.Context, arg UpsertDeviceFactParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceFact,
		arg.DeviceID,
		arg.Key,
		arg.Value,
		arg.ValueJson,
		arg.Driver,
	)
	return err
}
