// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_categories.sql

package db

import (
	"context"
	"time"
)

const countDevicesInCategory = `-- name: CountDevicesInCategory :one
SELECT count(*) FROM devices WHERE category = $1 AND deleted_at IS NULL
`

func (q *Queries) CountDevicesInCategory(ctx context.Context, category string) (int64, error) {
	row := q.db.QueryRow(ctx, countDevicesInCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeviceCategory = `-- name: CreateDeviceCategory :one
INSERT INTO device_categories (value, label, icon, builtin, enabled, sort_order)
VALUES ($1, $2, $3, false, true, $4)
RETURNING value, label, icon, builtin, enabled, sort_order, created_at, updated_at
`

type CreateDeviceCategoryParams struct {
	Value     string `json:"value"`
	Label     string `json:"label"`
	Icon      string `json:"icon"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateDeviceCategory(ctx context.Context, arg CreateDeviceCategoryParams) (DeviceCategory, error) {
	row := q.db.QueryRow(ctx, createDeviceCategory,
		arg.Value,
		arg.Label,
		arg.Icon,
		arg.SortOrder,
	)
	var i DeviceCategory
	err := row.Scan(
		&i.Value,
		&i.Label,
		&i.Icon,
		&i.Builtin,
		&i.Enabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceCategory = `-- name: DeleteDeviceCategory :exec
DELETE FROM device_categories WHERE value = $1 AND builtin = false
`

// Guarded in the handler: only builtin=false rows are ever passed here.
func (q *Queries) DeleteDeviceCategory(ctx context.Context, value string) error {
	_, err := q.db.Exec(ctx, deleteDeviceCategory, value)
	return err
}

const getDeviceCategory = `-- name: GetDeviceCategory :one
SELECT value, label, icon, builtin, enabled, sort_order, created_at, updated_at FROM device_categories WHERE value = $1
`

func (q *Queries) GetDeviceCategory(ctx context.Context, value string) (DeviceCategory, error) {
	row := q.db.QueryRow(ctx, getDeviceCategory, value)
	var i DeviceCategory
	err := row.Scan(
		&i.Value,
		&i.Label,
		&i.Icon,
		&i.Builtin,
		&i.Enabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isCategoryValid = `-- name: IsCategoryValid :one
SELECT EXISTS(SELECT 1 FROM device_categories WHERE value = $1)
`

// App-level replacement for the dropped CHECK constraint: a category is valid if a
// row exists for it (built-in or custom). Enabled/disabled does not affect validity
// (a hidden built-in a device already has stays valid; hiding only removes it from pickers).
func (q *Queries) IsCategoryValid(ctx context.Context, value string) (bool, error) {
	row := q.db.QueryRow(ctx, isCategoryValid, value)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDeviceCategories = `-- name: ListDeviceCategories :many
SELECT c.value, c.label, c.icon, c.builtin, c.enabled, c.sort_order, c.created_at, c.updated_at,
       (SELECT count(*) FROM devices d WHERE d.category = c.value AND d.deleted_at IS NULL) AS device_count
FROM device_categories c
ORDER BY c.sort_order, c.value
`

type ListDeviceCategoriesRow struct {
	Value       string    `json:"value"`
	Label       string    `json:"label"`
	Icon        string    `json:"icon"`
	Builtin     bool      `json:"builtin"`
	Enabled     bool      `json:"enabled"`
	SortOrder   int32     `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	DeviceCount int64     `json:"device_count"`
}

// All categories with a live device count, ordered for the picker + settings UI.
func (q *Queries) ListDeviceCategories(ctx context.Context) ([]ListDeviceCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listDeviceCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceCategoriesRow{}
	for rows.Next() {
		var i ListDeviceCategoriesRow
		if err := rows.Scan(
			&i.Value,
			&i.Label,
			&i.Icon,
			&i.Builtin,
			&i.Enabled,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignDeviceCategory = `-- name: ReassignDeviceCategory :exec
UPDATE devices SET category = $2, updated_at = now() WHERE category = $1 AND deleted_at IS NULL
`

type ReassignDeviceCategoryParams struct {
	Category   string `json:"category"`
	Category_2 string `json:"category_2"`
}

func (q *Queries) ReassignDeviceCategory(ctx context.Context, arg ReassignDeviceCategoryParams) error {
	_, err := q.db.Exec(ctx, reassignDeviceCategory, arg.Category, arg.Category_2)
	return err
}

const updateDeviceCategory = `-- name: UpdateDeviceCategory :one
UPDATE device_categories
SET label = $2, icon = $3, enabled = $4, sort_order = $5, updated_at = now()
WHERE value = $1
RETURNING value, label, icon, builtin, enabled, sort_order, created_at, updated_at
`

type UpdateDeviceCategoryParams struct {
	Value     string `json:"value"`
	Label     string `json:"label"`
	Icon      string `json:"icon"`
	Enabled   bool   `json:"enabled"`
	SortOrder int32  `json:"sort_order"`
}

// Cosmetic/visibility fields only; value + builtin are immutable.
func (q *Queries) UpdateDeviceCategory(ctx context.Context, arg UpdateDeviceCategoryParams) (DeviceCategory, error) {
	row := q.db.QueryRow(ctx, updateDeviceCategory,
		arg.Value,
		arg.Label,
		arg.Icon,
		arg.Enabled,
		arg.SortOrder,
	)
	var i DeviceCategory
	err := row.Scan(
		&i.Value,
		&i.Label,
		&i.Icon,
		&i.Builtin,
		&i.Enabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
