// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: firewall.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const deleteStaleHAMembers = `-- name: DeleteStaleHAMembers :exec
DELETE FROM firewall_ha_members
WHERE device_id = $1 AND last_seen_at < $2 AND collection_source = $3
`

type DeleteStaleHAMembersParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CollectionSource string    `json:"collection_source"`
}

func (q *Queries) DeleteStaleHAMembers(ctx context.Context, arg DeleteStaleHAMembersParams) error {
	_, err := q.db.Exec(ctx, deleteStaleHAMembers, arg.DeviceID, arg.LastSeenAt, arg.CollectionSource)
	return err
}

const deleteStaleLicenses = `-- name: DeleteStaleLicenses :exec
DELETE FROM firewall_licenses
WHERE device_id = $1 AND last_seen_at < $2 AND collection_source = $3
`

type DeleteStaleLicensesParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CollectionSource string    `json:"collection_source"`
}

func (q *Queries) DeleteStaleLicenses(ctx context.Context, arg DeleteStaleLicensesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleLicenses, arg.DeviceID, arg.LastSeenAt, arg.CollectionSource)
	return err
}

const deleteStaleVpnTunnels = `-- name: DeleteStaleVpnTunnels :exec
DELETE FROM firewall_vpn_tunnels
WHERE device_id = $1 AND last_seen_at < $2 AND collection_source = $3
`

type DeleteStaleVpnTunnelsParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CollectionSource string    `json:"collection_source"`
}

func (q *Queries) DeleteStaleVpnTunnels(ctx context.Context, arg DeleteStaleVpnTunnelsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleVpnTunnels, arg.DeviceID, arg.LastSeenAt, arg.CollectionSource)
	return err
}

const getFirewallStatus = `-- name: GetFirewallStatus :one
SELECT id, device_id, ha_mode, ha_group_name, ha_member_count, session_count, collection_source, last_seen_at, created_at, updated_at FROM firewall_status WHERE device_id = $1
`

func (q *Queries) GetFirewallStatus(ctx context.Context, deviceID uuid.UUID) (FirewallStatus, error) {
	row := q.db.QueryRow(ctx, getFirewallStatus, deviceID)
	var i FirewallStatus
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.HaMode,
		&i.HaGroupName,
		&i.HaMemberCount,
		&i.SessionCount,
		&i.CollectionSource,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHAMembers = `-- name: ListHAMembers :many
SELECT id, device_id, serial, hostname, cpu_pct, mem_pct, session_count, sync_status, collection_source, last_seen_at, created_at, updated_at FROM firewall_ha_members WHERE device_id = $1 ORDER BY serial
`

func (q *Queries) ListHAMembers(ctx context.Context, deviceID uuid.UUID) ([]FirewallHaMember, error) {
	rows, err := q.db.Query(ctx, listHAMembers, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirewallHaMember{}
	for rows.Next() {
		var i FirewallHaMember
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Serial,
			&i.Hostname,
			&i.CpuPct,
			&i.MemPct,
			&i.SessionCount,
			&i.SyncStatus,
			&i.CollectionSource,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLicenses = `-- name: ListLicenses :many
SELECT id, device_id, contract, expiry, collection_source, last_seen_at, created_at, updated_at FROM firewall_licenses WHERE device_id = $1 ORDER BY contract
`

func (q *Queries) ListLicenses(ctx context.Context, deviceID uuid.UUID) ([]FirewallLicense, error) {
	rows, err := q.db.Query(ctx, listLicenses, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirewallLicense{}
	for rows.Next() {
		var i FirewallLicense
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Contract,
			&i.Expiry,
			&i.CollectionSource,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVpnTunnels = `-- name: ListVpnTunnels :many
SELECT id, device_id, tunnel_name, p1_name, remote_gw, status, in_octets, out_octets, collection_source, last_seen_at, created_at, updated_at FROM firewall_vpn_tunnels WHERE device_id = $1 ORDER BY tunnel_name
`

func (q *Queries) ListVpnTunnels(ctx context.Context, deviceID uuid.UUID) ([]FirewallVpnTunnel, error) {
	rows, err := q.db.Query(ctx, listVpnTunnels, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirewallVpnTunnel{}
	for rows.Next() {
		var i FirewallVpnTunnel
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.TunnelName,
			&i.P1Name,
			&i.RemoteGw,
			&i.Status,
			&i.InOctets,
			&i.OutOctets,
			&i.CollectionSource,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFirewallStatus = `-- name: UpsertFirewallStatus :exec
INSERT INTO firewall_status (
    device_id, ha_mode, ha_group_name, ha_member_count, session_count,
    collection_source, last_seen_at
) VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (device_id) DO UPDATE SET
    ha_mode = EXCLUDED.ha_mode,
    ha_group_name = EXCLUDED.ha_group_name,
    ha_member_count = EXCLUDED.ha_member_count,
    session_count = EXCLUDED.session_count,
    collection_source = EXCLUDED.collection_source,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now()
`

type UpsertFirewallStatusParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	HaMode           string    `json:"ha_mode"`
	HaGroupName      *string   `json:"ha_group_name"`
	HaMemberCount    int32     `json:"ha_member_count"`
	SessionCount     *int64    `json:"session_count"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertFirewallStatus(ctx context.Context, arg UpsertFirewallStatusParams) error {
	_, err := q.db.Exec(ctx, upsertFirewallStatus,
		arg.DeviceID,
		arg.HaMode,
		arg.HaGroupName,
		arg.HaMemberCount,
		arg.SessionCount,
		arg.CollectionSource,
		arg.LastSeenAt,
	)
	return err
}

const upsertHAMember = `-- name: UpsertHAMember :exec
INSERT INTO firewall_ha_members (
    device_id, serial, hostname, cpu_pct, mem_pct, session_count,
    sync_status, collection_source, last_seen_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (device_id, serial) DO UPDATE SET
    hostname = EXCLUDED.hostname,
    cpu_pct = EXCLUDED.cpu_pct,
    mem_pct = EXCLUDED.mem_pct,
    session_count = EXCLUDED.session_count,
    sync_status = EXCLUDED.sync_status,
    collection_source = EXCLUDED.collection_source,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now()
`

type UpsertHAMemberParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	Serial           string    `json:"serial"`
	Hostname         *string   `json:"hostname"`
	CpuPct           *int32    `json:"cpu_pct"`
	MemPct           *int32    `json:"mem_pct"`
	SessionCount     *int64    `json:"session_count"`
	SyncStatus       string    `json:"sync_status"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertHAMember(ctx context.Context, arg UpsertHAMemberParams) error {
	_, err := q.db.Exec(ctx, upsertHAMember,
		arg.DeviceID,
		arg.Serial,
		arg.Hostname,
		arg.CpuPct,
		arg.MemPct,
		arg.SessionCount,
		arg.SyncStatus,
		arg.CollectionSource,
		arg.LastSeenAt,
	)
	return err
}

const upsertLicense = `-- name: UpsertLicense :exec
INSERT INTO firewall_licenses (device_id, contract, expiry, collection_source, last_seen_at)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (device_id, contract) DO UPDATE SET
    expiry = EXCLUDED.expiry,
    collection_source = EXCLUDED.collection_source,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now()
`

type UpsertLicenseParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	Contract         string    `json:"contract"`
	Expiry           *string   `json:"expiry"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertLicense(ctx context.Context, arg UpsertLicenseParams) error {
	_, err := q.db.Exec(ctx, upsertLicense,
		arg.DeviceID,
		arg.Contract,
		arg.Expiry,
		arg.CollectionSource,
		arg.LastSeenAt,
	)
	return err
}

const upsertVpnTunnel = `-- name: UpsertVpnTunnel :exec
INSERT INTO firewall_vpn_tunnels (
    device_id, tunnel_name, p1_name, remote_gw, status,
    in_octets, out_octets, collection_source, last_seen_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (device_id, tunnel_name) DO UPDATE SET
    p1_name = EXCLUDED.p1_name,
    remote_gw = EXCLUDED.remote_gw,
    status = EXCLUDED.status,
    in_octets = EXCLUDED.in_octets,
    out_octets = EXCLUDED.out_octets,
    collection_source = EXCLUDED.collection_source,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now()
`

type UpsertVpnTunnelParams struct {
	DeviceID         uuid.UUID   `json:"device_id"`
	TunnelName       string      `json:"tunnel_name"`
	P1Name           *string     `json:"p1_name"`
	RemoteGw         *netip.Addr `json:"remote_gw"`
	Status           string      `json:"status"`
	InOctets         *int64      `json:"in_octets"`
	OutOctets        *int64      `json:"out_octets"`
	CollectionSource string      `json:"collection_source"`
	LastSeenAt       time.Time   `json:"last_seen_at"`
}

func (q *Queries) UpsertVpnTunnel(ctx context.Context, arg UpsertVpnTunnelParams) error {
	_, err := q.db.Exec(ctx, upsertVpnTunnel,
		arg.DeviceID,
		arg.TunnelName,
		arg.P1Name,
		arg.RemoteGw,
		arg.Status,
		arg.InOctets,
		arg.OutOctets,
		arg.CollectionSource,
		arg.LastSeenAt,
	)
	return err
}
