// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type ArpEntry struct {
	ID               uuid.UUID  `json:"id"`
	DeviceID         uuid.UUID  `json:"device_id"`
	IpAddress        netip.Addr `json:"ip_address"`
	Mac              string     `json:"mac"`
	IfIndex          *int32     `json:"if_index"`
	CollectionSource string     `json:"collection_source"`
	LastSeenAt       time.Time  `json:"last_seen_at"`
}

type Credential struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Kind          string    `json:"kind"`
	EncryptedBlob []byte    `json:"encrypted_blob"`
	KeyID         string    `json:"key_id"`
	Weak          bool      `json:"weak"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type CredentialBinding struct {
	ID         uuid.UUID  `json:"id"`
	GroupID    uuid.UUID  `json:"group_id"`
	LocationID *uuid.UUID `json:"location_id"`
	SubnetID   *uuid.UUID `json:"subnet_id"`
	CreatedAt  time.Time  `json:"created_at"`
}

type CredentialGroup struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type CredentialGroupMember struct {
	GroupID      uuid.UUID `json:"group_id"`
	CredentialID uuid.UUID `json:"credential_id"`
	Priority     int32     `json:"priority"`
}

type Device struct {
	ID               uuid.UUID   `json:"id"`
	LocationID       *uuid.UUID  `json:"location_id"`
	PrimaryIp        *netip.Addr `json:"primary_ip"`
	Hostname         *string     `json:"hostname"`
	Name             string      `json:"name"`
	Vendor           *string     `json:"vendor"`
	Model            *string     `json:"model"`
	Serial           *string     `json:"serial"`
	OsVersion        *string     `json:"os_version"`
	Category         string      `json:"category"`
	Status           string      `json:"status"`
	Driver           *string     `json:"driver"`
	CredentialID     *uuid.UUID  `json:"credential_id"`
	LastDiscoveryAt  *time.Time  `json:"last_discovery_at"`
	LastMonitoringAt *time.Time  `json:"last_monitoring_at"`
	Metadata         []byte      `json:"metadata"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	DeletedAt        *time.Time  `json:"deleted_at"`
}

type DeviceFact struct {
	ID         uuid.UUID `json:"id"`
	DeviceID   uuid.UUID `json:"device_id"`
	Key        string    `json:"key"`
	Value      *string   `json:"value"`
	ValueJson  []byte    `json:"value_json"`
	Driver     string    `json:"driver"`
	ObservedAt time.Time `json:"observed_at"`
}

type DeviceRole struct {
	DeviceID  uuid.UUID `json:"device_id"`
	Role      string    `json:"role"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

type DiscoveryJob struct {
	ID         uuid.UUID     `json:"id"`
	LocationID *uuid.UUID    `json:"location_id"`
	SubnetID   *uuid.UUID    `json:"subnet_id"`
	ScopeCidr  *netip.Prefix `json:"scope_cidr"`
	Status     string        `json:"status"`
	StartedAt  *time.Time    `json:"started_at"`
	FinishedAt *time.Time    `json:"finished_at"`
	HostCount  int32         `json:"host_count"`
	FoundCount int32         `json:"found_count"`
	Error      *string       `json:"error"`
	Metadata   []byte        `json:"metadata"`
	CreatedAt  time.Time     `json:"created_at"`
}

type DiscoveryResult struct {
	ID        uuid.UUID  `json:"id"`
	JobID     uuid.UUID  `json:"job_id"`
	Ip        netip.Addr `json:"ip"`
	Outcome   string     `json:"outcome"`
	DeviceID  *uuid.UUID `json:"device_id"`
	Driver    *string    `json:"driver"`
	Category  *string    `json:"category"`
	ProbeData []byte     `json:"probe_data"`
	Error     *string    `json:"error"`
	ProbedAt  time.Time  `json:"probed_at"`
}

type FirewallHaMember struct {
	ID               uuid.UUID `json:"id"`
	DeviceID         uuid.UUID `json:"device_id"`
	Serial           string    `json:"serial"`
	Hostname         *string   `json:"hostname"`
	CpuPct           *int32    `json:"cpu_pct"`
	MemPct           *int32    `json:"mem_pct"`
	SessionCount     *int64    `json:"session_count"`
	SyncStatus       string    `json:"sync_status"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type FirewallLicense struct {
	ID               uuid.UUID `json:"id"`
	DeviceID         uuid.UUID `json:"device_id"`
	Contract         string    `json:"contract"`
	Expiry           *string   `json:"expiry"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type FirewallStatus struct {
	ID               uuid.UUID `json:"id"`
	DeviceID         uuid.UUID `json:"device_id"`
	HaMode           string    `json:"ha_mode"`
	HaGroupName      *string   `json:"ha_group_name"`
	HaMemberCount    int32     `json:"ha_member_count"`
	SessionCount     *int64    `json:"session_count"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type FirewallVpnTunnel struct {
	ID               uuid.UUID   `json:"id"`
	DeviceID         uuid.UUID   `json:"device_id"`
	TunnelName       string      `json:"tunnel_name"`
	P1Name           *string     `json:"p1_name"`
	RemoteGw         *netip.Addr `json:"remote_gw"`
	Status           string      `json:"status"`
	InOctets         *int64      `json:"in_octets"`
	OutOctets        *int64      `json:"out_octets"`
	CollectionSource string      `json:"collection_source"`
	LastSeenAt       time.Time   `json:"last_seen_at"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type Interface struct {
	ID               uuid.UUID `json:"id"`
	DeviceID         uuid.UUID `json:"device_id"`
	IfIndex          int32     `json:"if_index"`
	IfName           *string   `json:"if_name"`
	IfDescr          *string   `json:"if_descr"`
	IfAlias          *string   `json:"if_alias"`
	IfType           *int32    `json:"if_type"`
	Mac              *string   `json:"mac"`
	SpeedMbps        *int32    `json:"speed_mbps"`
	AdminStatus      *int16    `json:"admin_status"`
	OperStatus       *int16    `json:"oper_status"`
	PortRole         string    `json:"port_role"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Location struct {
	ID        uuid.UUID  `json:"id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Kind      string     `json:"kind"`
	Name      string     `json:"name"`
	Code      *string    `json:"code"`
	Metadata  []byte     `json:"metadata"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type MacAddress struct {
	ID               uuid.UUID `json:"id"`
	DeviceID         uuid.UUID `json:"device_id"`
	Mac              string    `json:"mac"`
	VlanID           int32     `json:"vlan_id"`
	IfIndex          *int32    `json:"if_index"`
	FdbStatus        int16     `json:"fdb_status"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}

type Neighbor struct {
	ID               uuid.UUID   `json:"id"`
	DeviceID         uuid.UUID   `json:"device_id"`
	LocalIfIndex     *int32      `json:"local_if_index"`
	LocalIfName      *string     `json:"local_if_name"`
	RemChassisID     *string     `json:"rem_chassis_id"`
	RemSysName       *string     `json:"rem_sys_name"`
	RemSysDesc       *string     `json:"rem_sys_desc"`
	RemPortID        *string     `json:"rem_port_id"`
	RemPortDesc      *string     `json:"rem_port_desc"`
	RemMgmtIp        *netip.Addr `json:"rem_mgmt_ip"`
	Protocol         string      `json:"protocol"`
	CollectionSource string      `json:"collection_source"`
	LastSeenAt       time.Time   `json:"last_seen_at"`
}

type PortVlan struct {
	ID               uuid.UUID `json:"id"`
	DeviceID         uuid.UUID `json:"device_id"`
	IfIndex          int32     `json:"if_index"`
	VlanID           int32     `json:"vlan_id"`
	Tagged           bool      `json:"tagged"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}

type ServerStorage struct {
	ID               uuid.UUID `json:"id"`
	DeviceID         uuid.UUID `json:"device_id"`
	HrIndex          int32     `json:"hr_index"`
	Descr            *string   `json:"descr"`
	StorageType      string    `json:"storage_type"`
	TotalBytes       *int64    `json:"total_bytes"`
	UsedBytes        *int64    `json:"used_bytes"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Subnet struct {
	ID         uuid.UUID    `json:"id"`
	LocationID uuid.UUID    `json:"location_id"`
	Cidr       netip.Prefix `json:"cidr"`
	Name       *string      `json:"name"`
	VlanID     *int32       `json:"vlan_id"`
	Metadata   []byte       `json:"metadata"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type TopologyLink struct {
	ID             uuid.UUID   `json:"id"`
	LocalDeviceID  uuid.UUID   `json:"local_device_id"`
	LocalIfIndex   *int32      `json:"local_if_index"`
	LocalIfName    *string     `json:"local_if_name"`
	RemoteDeviceID *uuid.UUID  `json:"remote_device_id"`
	RemoteIp       *netip.Addr `json:"remote_ip"`
	RemoteSysName  *string     `json:"remote_sys_name"`
	LinkSource     string      `json:"link_source"`
	LastSeenAt     time.Time   `json:"last_seen_at"`
}

type Vlan struct {
	ID               uuid.UUID `json:"id"`
	DeviceID         uuid.UUID `json:"device_id"`
	VlanID           int32     `json:"vlan_id"`
	Name             *string   `json:"name"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}
