// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Credential struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Kind          string    `json:"kind"`
	EncryptedBlob []byte    `json:"encrypted_blob"`
	KeyID         string    `json:"key_id"`
	Weak          bool      `json:"weak"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type CredentialBinding struct {
	ID         uuid.UUID  `json:"id"`
	GroupID    uuid.UUID  `json:"group_id"`
	LocationID *uuid.UUID `json:"location_id"`
	SubnetID   *uuid.UUID `json:"subnet_id"`
	CreatedAt  time.Time  `json:"created_at"`
}

type CredentialGroup struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type CredentialGroupMember struct {
	GroupID      uuid.UUID `json:"group_id"`
	CredentialID uuid.UUID `json:"credential_id"`
	Priority     int32     `json:"priority"`
}

type Device struct {
	ID               uuid.UUID   `json:"id"`
	LocationID       *uuid.UUID  `json:"location_id"`
	PrimaryIp        *netip.Addr `json:"primary_ip"`
	Hostname         *string     `json:"hostname"`
	Name             string      `json:"name"`
	Vendor           *string     `json:"vendor"`
	Model            *string     `json:"model"`
	Serial           *string     `json:"serial"`
	OsVersion        *string     `json:"os_version"`
	Category         string      `json:"category"`
	Status           string      `json:"status"`
	Driver           *string     `json:"driver"`
	CredentialID     *uuid.UUID  `json:"credential_id"`
	LastDiscoveryAt  *time.Time  `json:"last_discovery_at"`
	LastMonitoringAt *time.Time  `json:"last_monitoring_at"`
	Metadata         []byte      `json:"metadata"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	DeletedAt        *time.Time  `json:"deleted_at"`
}

type DeviceFact struct {
	ID         uuid.UUID `json:"id"`
	DeviceID   uuid.UUID `json:"device_id"`
	Key        string    `json:"key"`
	Value      *string   `json:"value"`
	ValueJson  []byte    `json:"value_json"`
	Driver     string    `json:"driver"`
	ObservedAt time.Time `json:"observed_at"`
}

type DeviceRole struct {
	DeviceID  uuid.UUID `json:"device_id"`
	Role      string    `json:"role"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

type Location struct {
	ID        uuid.UUID  `json:"id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Kind      string     `json:"kind"`
	Name      string     `json:"name"`
	Code      *string    `json:"code"`
	Metadata  []byte     `json:"metadata"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type Subnet struct {
	ID         uuid.UUID    `json:"id"`
	LocationID uuid.UUID    `json:"location_id"`
	Cidr       netip.Prefix `json:"cidr"`
	Name       *string      `json:"name"`
	VlanID     *int32       `json:"vlan_id"`
	Metadata   []byte       `json:"metadata"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}
