// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: monitoring.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const deleteDeviceReachabilityChecks = `-- name: DeleteDeviceReachabilityChecks :exec
DELETE FROM monitoring_checks WHERE device_id = $1 AND kind = 'tcp'
`

// Remove a device's TCP reachability checks so a fresh, evidence-based one can
// replace them (used when a scan re-points the check at a port the host
// actually answered on). SNMP/metric checks are left untouched.
func (q *Queries) DeleteDeviceReachabilityChecks(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceReachabilityChecks, deviceID)
	return err
}

const deleteMonitoringCheck = `-- name: DeleteMonitoringCheck :exec
DELETE FROM monitoring_checks WHERE id = $1
`

func (q *Queries) DeleteMonitoringCheck(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitoringCheck, id)
	return err
}

const getMonitoringCheck = `-- name: GetMonitoringCheck :one
SELECT id, device_id, kind, target_port, oid, interval_seconds, down_threshold, enabled, last_run_at, last_status, last_latency_ms, consecutive_failures, created_at, updated_at, role FROM monitoring_checks WHERE id = $1
`

func (q *Queries) GetMonitoringCheck(ctx context.Context, id uuid.UUID) (MonitoringCheck, error) {
	row := q.db.QueryRow(ctx, getMonitoringCheck, id)
	var i MonitoringCheck
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Kind,
		&i.TargetPort,
		&i.Oid,
		&i.IntervalSeconds,
		&i.DownThreshold,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const insertMonitoringSample = `-- name: InsertMonitoringSample :exec
INSERT INTO monitoring_samples (check_id, device_id, status, latency_ms, value_num, error)
VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertMonitoringSampleParams struct {
	CheckID   uuid.UUID `json:"check_id"`
	DeviceID  uuid.UUID `json:"device_id"`
	Status    string    `json:"status"`
	LatencyMs *float64  `json:"latency_ms"`
	ValueNum  *float64  `json:"value_num"`
	Error     *string   `json:"error"`
}

func (q *Queries) InsertMonitoringSample(ctx context.Context, arg InsertMonitoringSampleParams) error {
	_, err := q.db.Exec(ctx, insertMonitoringSample,
		arg.CheckID,
		arg.DeviceID,
		arg.Status,
		arg.LatencyMs,
		arg.ValueNum,
		arg.Error,
	)
	return err
}

const listDevicesNeedingDefaultCheck = `-- name: ListDevicesNeedingDefaultCheck :many
SELECT id, primary_ip, category, os_family FROM devices
WHERE primary_ip IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM monitoring_checks c WHERE c.device_id = devices.id)
LIMIT 1000
`

type ListDevicesNeedingDefaultCheckRow struct {
	ID        uuid.UUID   `json:"id"`
	PrimaryIp *netip.Addr `json:"primary_ip"`
	Category  string      `json:"category"`
	OsFamily  string      `json:"os_family"`
}

// Devices with a reachable IP but no monitoring check yet — the seeder turns
// each into a default TCP check (port chosen by category + os_family).
func (q *Queries) ListDevicesNeedingDefaultCheck(ctx context.Context) ([]ListDevicesNeedingDefaultCheckRow, error) {
	rows, err := q.db.Query(ctx, listDevicesNeedingDefaultCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesNeedingDefaultCheckRow{}
	for rows.Next() {
		var i ListDevicesNeedingDefaultCheckRow
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryIp,
			&i.Category,
			&i.OsFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueMonitoringChecks = `-- name: ListDueMonitoringChecks :many
SELECT id, device_id, kind, target_port, oid, interval_seconds, down_threshold, enabled, last_run_at, last_status, last_latency_ms, consecutive_failures, created_at, updated_at, role FROM monitoring_checks
WHERE enabled
  AND (last_run_at IS NULL
       OR last_run_at + make_interval(secs => interval_seconds) <= now())
ORDER BY last_run_at NULLS FIRST
LIMIT 500
`

// A check is due when enabled and either never run or its interval elapsed.
func (q *Queries) ListDueMonitoringChecks(ctx context.Context) ([]MonitoringCheck, error) {
	rows, err := q.db.Query(ctx, listDueMonitoringChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringCheck{}
	for rows.Next() {
		var i MonitoringCheck
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Kind,
			&i.TargetPort,
			&i.Oid,
			&i.IntervalSeconds,
			&i.DownThreshold,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoringChecks = `-- name: ListMonitoringChecks :many
SELECT c.id, c.device_id, c.kind, c.target_port, c.oid, c.interval_seconds, c.down_threshold, c.enabled, c.last_run_at, c.last_status, c.last_latency_ms, c.consecutive_failures, c.created_at, c.updated_at, c.role,
       d.name AS device_name,
       d.primary_ip AS device_ip,
       d.category AS device_category
FROM monitoring_checks c
JOIN devices d ON d.id = c.device_id AND d.deleted_at IS NULL
ORDER BY d.name, (c.role <> 'reachability'), c.kind, c.target_port
LIMIT 500
`

type ListMonitoringChecksRow struct {
	ID                  uuid.UUID   `json:"id"`
	DeviceID            uuid.UUID   `json:"device_id"`
	Kind                string      `json:"kind"`
	TargetPort          *int32      `json:"target_port"`
	Oid                 *string     `json:"oid"`
	IntervalSeconds     int32       `json:"interval_seconds"`
	DownThreshold       int32       `json:"down_threshold"`
	Enabled             bool        `json:"enabled"`
	LastRunAt           *time.Time  `json:"last_run_at"`
	LastStatus          string      `json:"last_status"`
	LastLatencyMs       *float64    `json:"last_latency_ms"`
	ConsecutiveFailures int32       `json:"consecutive_failures"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	Role                string      `json:"role"`
	DeviceName          string      `json:"device_name"`
	DeviceIp            *netip.Addr `json:"device_ip"`
	DeviceCategory      string      `json:"device_category"`
}

// Global checks list (Health Overview). Joined to the device so the UI can
// identify each check by device name / IP (not just a bare port), and ordered
// by device then reachability-first so a device's checks group together.
func (q *Queries) ListMonitoringChecks(ctx context.Context) ([]ListMonitoringChecksRow, error) {
	rows, err := q.db.Query(ctx, listMonitoringChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonitoringChecksRow{}
	for rows.Next() {
		var i ListMonitoringChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Kind,
			&i.TargetPort,
			&i.Oid,
			&i.IntervalSeconds,
			&i.DownThreshold,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.DeviceName,
			&i.DeviceIp,
			&i.DeviceCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoringChecksByDevice = `-- name: ListMonitoringChecksByDevice :many
SELECT id, device_id, kind, target_port, oid, interval_seconds, down_threshold, enabled, last_run_at, last_status, last_latency_ms, consecutive_failures, created_at, updated_at, role FROM monitoring_checks WHERE device_id = $1 ORDER BY kind, target_port
`

func (q *Queries) ListMonitoringChecksByDevice(ctx context.Context, deviceID uuid.UUID) ([]MonitoringCheck, error) {
	rows, err := q.db.Query(ctx, listMonitoringChecksByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringCheck{}
	for rows.Next() {
		var i MonitoringCheck
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Kind,
			&i.TargetPort,
			&i.Oid,
			&i.IntervalSeconds,
			&i.DownThreshold,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoringSamplesByCheck = `-- name: ListMonitoringSamplesByCheck :many
SELECT time, check_id, device_id, status, latency_ms, value_num, error FROM monitoring_samples
WHERE check_id = $1
ORDER BY time DESC
LIMIT $2
`

type ListMonitoringSamplesByCheckParams struct {
	CheckID uuid.UUID `json:"check_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) ListMonitoringSamplesByCheck(ctx context.Context, arg ListMonitoringSamplesByCheckParams) ([]MonitoringSample, error) {
	rows, err := q.db.Query(ctx, listMonitoringSamplesByCheck, arg.CheckID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringSample{}
	for rows.Next() {
		var i MonitoringSample
		if err := rows.Scan(
			&i.Time,
			&i.CheckID,
			&i.DeviceID,
			&i.Status,
			&i.LatencyMs,
			&i.ValueNum,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoringSamplesByDevice = `-- name: ListMonitoringSamplesByDevice :many
SELECT time, check_id, device_id, status, latency_ms, value_num, error FROM monitoring_samples
WHERE device_id = $1
ORDER BY time DESC
LIMIT $2
`

type ListMonitoringSamplesByDeviceParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListMonitoringSamplesByDevice(ctx context.Context, arg ListMonitoringSamplesByDeviceParams) ([]MonitoringSample, error) {
	rows, err := q.db.Query(ctx, listMonitoringSamplesByDevice, arg.DeviceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringSample{}
	for rows.Next() {
		var i MonitoringSample
		if err := rows.Scan(
			&i.Time,
			&i.CheckID,
			&i.DeviceID,
			&i.Status,
			&i.LatencyMs,
			&i.ValueNum,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monitoringStatusOverview = `-- name: MonitoringStatusOverview :many
SELECT
    (CASE d.status
        WHEN 'up' THEN 'up'
        WHEN 'down' THEN 'down'
        WHEN 'warning' THEN 'warning'
        WHEN 'needs_attention' THEN 'warning'
        ELSE 'unknown'
     END)::text AS status,
    COUNT(*)::bigint AS count
FROM devices d
WHERE d.deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM monitoring_checks c WHERE c.device_id = d.id AND c.enabled)
GROUP BY 1
`

type MonitoringStatusOverviewRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Fleet health rollup, DEVICE-based: how many MONITORED devices sit in each
// reachability bucket. We count devices (not checks) and map the device's
// rolled-up status onto the up/down/warning/unknown vocabulary, so the KPI
// counts match the inventory reachability filter exactly (a click lands on the
// same devices). A failing SUPPLEMENTAL check surfaces here as "warning" (the
// rollup degrades the device to warning, never down) — it lowers the health
// score and is clickable, but never inflates the "down"/offline bucket. A device
// is "monitored" when it has at least one enabled check.
func (q *Queries) MonitoringStatusOverview(ctx context.Context) ([]MonitoringStatusOverviewRow, error) {
	rows, err := q.db.Query(ctx, monitoringStatusOverview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringStatusOverviewRow{}
	for rows.Next() {
		var i MonitoringStatusOverviewRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMonitoringResult = `-- name: RecordMonitoringResult :one
UPDATE monitoring_checks SET
    last_run_at = now(),
    last_status = $2,
    last_latency_ms = $3,
    consecutive_failures = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, device_id, kind, target_port, oid, interval_seconds, down_threshold, enabled, last_run_at, last_status, last_latency_ms, consecutive_failures, created_at, updated_at, role
`

type RecordMonitoringResultParams struct {
	ID                  uuid.UUID `json:"id"`
	LastStatus          string    `json:"last_status"`
	LastLatencyMs       *float64  `json:"last_latency_ms"`
	ConsecutiveFailures int32     `json:"consecutive_failures"`
}

// Persist the rollup the engine computed (status + failure counter) onto the
// check after a poll. History rows go to monitoring_samples separately.
func (q *Queries) RecordMonitoringResult(ctx context.Context, arg RecordMonitoringResultParams) (MonitoringCheck, error) {
	row := q.db.QueryRow(ctx, recordMonitoringResult,
		arg.ID,
		arg.LastStatus,
		arg.LastLatencyMs,
		arg.ConsecutiveFailures,
	)
	var i MonitoringCheck
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Kind,
		&i.TargetPort,
		&i.Oid,
		&i.IntervalSeconds,
		&i.DownThreshold,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const setMonitoringCheckEnabled = `-- name: SetMonitoringCheckEnabled :one
UPDATE monitoring_checks SET enabled = $2, updated_at = now()
WHERE id = $1 RETURNING id, device_id, kind, target_port, oid, interval_seconds, down_threshold, enabled, last_run_at, last_status, last_latency_ms, consecutive_failures, created_at, updated_at, role
`

type SetMonitoringCheckEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetMonitoringCheckEnabled(ctx context.Context, arg SetMonitoringCheckEnabledParams) (MonitoringCheck, error) {
	row := q.db.QueryRow(ctx, setMonitoringCheckEnabled, arg.ID, arg.Enabled)
	var i MonitoringCheck
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Kind,
		&i.TargetPort,
		&i.Oid,
		&i.IntervalSeconds,
		&i.DownThreshold,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const setMonitoringCheckRole = `-- name: SetMonitoringCheckRole :exec
UPDATE monitoring_checks SET role = $2, updated_at = now() WHERE id = $1
`

type SetMonitoringCheckRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

// Mark a check as reachability (drives device status) or supplemental (extra,
// informational only). Used when an operator adds a check beyond the default.
func (q *Queries) SetMonitoringCheckRole(ctx context.Context, arg SetMonitoringCheckRoleParams) error {
	_, err := q.db.Exec(ctx, setMonitoringCheckRole, arg.ID, arg.Role)
	return err
}

const updateDeviceMonitoringStatus = `-- name: UpdateDeviceMonitoringStatus :exec
UPDATE devices SET
    status = $2,
    last_monitoring_at = now(),
    updated_at = now()
WHERE id = $1
`

type UpdateDeviceMonitoringStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// Reflect the worst current check status onto the device row so device lists
// show a live health badge without a per-row sample query.
func (q *Queries) UpdateDeviceMonitoringStatus(ctx context.Context, arg UpdateDeviceMonitoringStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeviceMonitoringStatus, arg.ID, arg.Status)
	return err
}

const upsertMonitoringCheck = `-- name: UpsertMonitoringCheck :one
INSERT INTO monitoring_checks (device_id, kind, target_port, oid, interval_seconds, down_threshold, enabled)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (device_id, kind, target_port) DO UPDATE SET
    oid = EXCLUDED.oid,
    interval_seconds = EXCLUDED.interval_seconds,
    down_threshold = EXCLUDED.down_threshold,
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, device_id, kind, target_port, oid, interval_seconds, down_threshold, enabled, last_run_at, last_status, last_latency_ms, consecutive_failures, created_at, updated_at, role
`

type UpsertMonitoringCheckParams struct {
	DeviceID        uuid.UUID `json:"device_id"`
	Kind            string    `json:"kind"`
	TargetPort      *int32    `json:"target_port"`
	Oid             *string   `json:"oid"`
	IntervalSeconds int32     `json:"interval_seconds"`
	DownThreshold   int32     `json:"down_threshold"`
	Enabled         bool      `json:"enabled"`
}

// Idempotent registration: re-registering the same (device, kind, port)
// updates the schedule knobs without resetting the live status counters.
func (q *Queries) UpsertMonitoringCheck(ctx context.Context, arg UpsertMonitoringCheckParams) (MonitoringCheck, error) {
	row := q.db.QueryRow(ctx, upsertMonitoringCheck,
		arg.DeviceID,
		arg.Kind,
		arg.TargetPort,
		arg.Oid,
		arg.IntervalSeconds,
		arg.DownThreshold,
		arg.Enabled,
	)
	var i MonitoringCheck
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Kind,
		&i.TargetPort,
		&i.Oid,
		&i.IntervalSeconds,
		&i.DownThreshold,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}
