// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: nas.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteStaleNASDisks = `-- name: DeleteStaleNASDisks :exec
DELETE FROM nas_disks WHERE device_id = $1 AND last_seen_at < $2
`

type DeleteStaleNASDisksParams struct {
	DeviceID   uuid.UUID `json:"device_id"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

func (q *Queries) DeleteStaleNASDisks(ctx context.Context, arg DeleteStaleNASDisksParams) error {
	_, err := q.db.Exec(ctx, deleteStaleNASDisks, arg.DeviceID, arg.LastSeenAt)
	return err
}

const deleteStaleNASVolumes = `-- name: DeleteStaleNASVolumes :exec
DELETE FROM nas_volumes WHERE device_id = $1 AND last_seen_at < $2
`

type DeleteStaleNASVolumesParams struct {
	DeviceID   uuid.UUID `json:"device_id"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

func (q *Queries) DeleteStaleNASVolumes(ctx context.Context, arg DeleteStaleNASVolumesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleNASVolumes, arg.DeviceID, arg.LastSeenAt)
	return err
}

const getNASInfo = `-- name: GetNASInfo :one
SELECT device_id, vendor, model, firmware, serial, hostname, cpu_pct, mem_total_bytes, mem_used_bytes, cpu_temp_c, sys_temp_c, uptime_seconds, disk_count, volume_count, health, collection_source, last_seen_at FROM nas_info WHERE device_id = $1
`

func (q *Queries) GetNASInfo(ctx context.Context, deviceID uuid.UUID) (NasInfo, error) {
	row := q.db.QueryRow(ctx, getNASInfo, deviceID)
	var i NasInfo
	err := row.Scan(
		&i.DeviceID,
		&i.Vendor,
		&i.Model,
		&i.Firmware,
		&i.Serial,
		&i.Hostname,
		&i.CpuPct,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.CpuTempC,
		&i.SysTempC,
		&i.UptimeSeconds,
		&i.DiskCount,
		&i.VolumeCount,
		&i.Health,
		&i.CollectionSource,
		&i.LastSeenAt,
	)
	return i, err
}

const listNASDisks = `-- name: ListNASDisks :many
SELECT device_id, slot, vendor, model, serial, interface_type, capacity_bytes, temp_c, health, last_seen_at FROM nas_disks WHERE device_id = $1 ORDER BY slot
`

func (q *Queries) ListNASDisks(ctx context.Context, deviceID uuid.UUID) ([]NasDisk, error) {
	rows, err := q.db.Query(ctx, listNASDisks, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NasDisk{}
	for rows.Next() {
		var i NasDisk
		if err := rows.Scan(
			&i.DeviceID,
			&i.Slot,
			&i.Vendor,
			&i.Model,
			&i.Serial,
			&i.InterfaceType,
			&i.CapacityBytes,
			&i.TempC,
			&i.Health,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNASVolumes = `-- name: ListNASVolumes :many
SELECT device_id, idx, name, fs_type, total_bytes, used_bytes, last_seen_at FROM nas_volumes WHERE device_id = $1 ORDER BY total_bytes DESC, idx
`

func (q *Queries) ListNASVolumes(ctx context.Context, deviceID uuid.UUID) ([]NasVolume, error) {
	rows, err := q.db.Query(ctx, listNASVolumes, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NasVolume{}
	for rows.Next() {
		var i NasVolume
		if err := rows.Scan(
			&i.DeviceID,
			&i.Idx,
			&i.Name,
			&i.FsType,
			&i.TotalBytes,
			&i.UsedBytes,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNASDisk = `-- name: UpsertNASDisk :exec
INSERT INTO nas_disks (device_id, slot, vendor, model, serial, interface_type,
    capacity_bytes, temp_c, health, last_seen_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (device_id, slot) DO UPDATE SET
    vendor = EXCLUDED.vendor,
    model = EXCLUDED.model,
    serial = EXCLUDED.serial,
    interface_type = EXCLUDED.interface_type,
    capacity_bytes = EXCLUDED.capacity_bytes,
    temp_c = EXCLUDED.temp_c,
    health = EXCLUDED.health,
    last_seen_at = EXCLUDED.last_seen_at
`

type UpsertNASDiskParams struct {
	DeviceID      uuid.UUID `json:"device_id"`
	Slot          int32     `json:"slot"`
	Vendor        *string   `json:"vendor"`
	Model         *string   `json:"model"`
	Serial        *string   `json:"serial"`
	InterfaceType *string   `json:"interface_type"`
	CapacityBytes *int64    `json:"capacity_bytes"`
	TempC         *int32    `json:"temp_c"`
	Health        *string   `json:"health"`
	LastSeenAt    time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertNASDisk(ctx context.Context, arg UpsertNASDiskParams) error {
	_, err := q.db.Exec(ctx, upsertNASDisk,
		arg.DeviceID,
		arg.Slot,
		arg.Vendor,
		arg.Model,
		arg.Serial,
		arg.InterfaceType,
		arg.CapacityBytes,
		arg.TempC,
		arg.Health,
		arg.LastSeenAt,
	)
	return err
}

const upsertNASInfo = `-- name: UpsertNASInfo :exec
INSERT INTO nas_info (device_id, vendor, model, firmware, serial, hostname, cpu_pct,
    mem_total_bytes, mem_used_bytes, cpu_temp_c, sys_temp_c, uptime_seconds,
    disk_count, volume_count, health, collection_source, last_seen_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
ON CONFLICT (device_id) DO UPDATE SET
    vendor = EXCLUDED.vendor,
    model = EXCLUDED.model,
    firmware = EXCLUDED.firmware,
    serial = EXCLUDED.serial,
    hostname = EXCLUDED.hostname,
    cpu_pct = EXCLUDED.cpu_pct,
    mem_total_bytes = EXCLUDED.mem_total_bytes,
    mem_used_bytes = EXCLUDED.mem_used_bytes,
    cpu_temp_c = EXCLUDED.cpu_temp_c,
    sys_temp_c = EXCLUDED.sys_temp_c,
    uptime_seconds = EXCLUDED.uptime_seconds,
    disk_count = EXCLUDED.disk_count,
    volume_count = EXCLUDED.volume_count,
    health = EXCLUDED.health,
    collection_source = EXCLUDED.collection_source,
    last_seen_at = EXCLUDED.last_seen_at
`

type UpsertNASInfoParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	Vendor           *string   `json:"vendor"`
	Model            *string   `json:"model"`
	Firmware         *string   `json:"firmware"`
	Serial           *string   `json:"serial"`
	Hostname         *string   `json:"hostname"`
	CpuPct           *float64  `json:"cpu_pct"`
	MemTotalBytes    *int64    `json:"mem_total_bytes"`
	MemUsedBytes     *int64    `json:"mem_used_bytes"`
	CpuTempC         *int32    `json:"cpu_temp_c"`
	SysTempC         *int32    `json:"sys_temp_c"`
	UptimeSeconds    *int64    `json:"uptime_seconds"`
	DiskCount        int32     `json:"disk_count"`
	VolumeCount      int32     `json:"volume_count"`
	Health           *string   `json:"health"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertNASInfo(ctx context.Context, arg UpsertNASInfoParams) error {
	_, err := q.db.Exec(ctx, upsertNASInfo,
		arg.DeviceID,
		arg.Vendor,
		arg.Model,
		arg.Firmware,
		arg.Serial,
		arg.Hostname,
		arg.CpuPct,
		arg.MemTotalBytes,
		arg.MemUsedBytes,
		arg.CpuTempC,
		arg.SysTempC,
		arg.UptimeSeconds,
		arg.DiskCount,
		arg.VolumeCount,
		arg.Health,
		arg.CollectionSource,
		arg.LastSeenAt,
	)
	return err
}

const upsertNASVolume = `-- name: UpsertNASVolume :exec
INSERT INTO nas_volumes (device_id, idx, name, fs_type, total_bytes, used_bytes, last_seen_at)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (device_id, idx) DO UPDATE SET
    name = EXCLUDED.name,
    fs_type = EXCLUDED.fs_type,
    total_bytes = EXCLUDED.total_bytes,
    used_bytes = EXCLUDED.used_bytes,
    last_seen_at = EXCLUDED.last_seen_at
`

type UpsertNASVolumeParams struct {
	DeviceID   uuid.UUID `json:"device_id"`
	Idx        int32     `json:"idx"`
	Name       string    `json:"name"`
	FsType     *string   `json:"fs_type"`
	TotalBytes *int64    `json:"total_bytes"`
	UsedBytes  *int64    `json:"used_bytes"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertNASVolume(ctx context.Context, arg UpsertNASVolumeParams) error {
	_, err := q.db.Exec(ctx, upsertNASVolume,
		arg.DeviceID,
		arg.Idx,
		arg.Name,
		arg.FsType,
		arg.TotalBytes,
		arg.UsedBytes,
		arg.LastSeenAt,
	)
	return err
}
