// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNotificationChannel = `-- name: CreateNotificationChannel :one

INSERT INTO notification_channels (name, type, target_encrypted, key_id, min_severity, quiet_start_min, quiet_end_min, enabled)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, name, type, target_encrypted, key_id, min_severity, quiet_start_min, quiet_end_min, enabled, created_at, updated_at
`

type CreateNotificationChannelParams struct {
	Name            string `json:"name"`
	Type            string `json:"type"`
	TargetEncrypted []byte `json:"target_encrypted"`
	KeyID           string `json:"key_id"`
	MinSeverity     string `json:"min_severity"`
	QuietStartMin   *int32 `json:"quiet_start_min"`
	QuietEndMin     *int32 `json:"quiet_end_min"`
	Enabled         bool   `json:"enabled"`
}

// ---- Notification channels ------------------------------------------------
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.Name,
		arg.Type,
		arg.TargetEncrypted,
		arg.KeyID,
		arg.MinSeverity,
		arg.QuietStartMin,
		arg.QuietEndMin,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.TargetEncrypted,
		&i.KeyID,
		&i.MinSeverity,
		&i.QuietStartMin,
		&i.QuietEndMin,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels WHERE id = $1
`

func (q *Queries) DeleteNotificationChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotificationChannel, id)
	return err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, name, type, target_encrypted, key_id, min_severity, quiet_start_min, quiet_end_min, enabled, created_at, updated_at FROM notification_channels WHERE id = $1
`

func (q *Queries) GetNotificationChannel(ctx context.Context, id uuid.UUID) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.TargetEncrypted,
		&i.KeyID,
		&i.MinSeverity,
		&i.QuietStartMin,
		&i.QuietEndMin,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotificationLog = `-- name: InsertNotificationLog :one

INSERT INTO notification_log (channel_id, alert_id, status, detail)
VALUES ($1,$2,$3,$4)
ON CONFLICT (channel_id, alert_id) WHERE status = 'sent' AND alert_id IS NOT NULL DO NOTHING
RETURNING id, channel_id, alert_id, at, status, detail
`

type InsertNotificationLogParams struct {
	ChannelID uuid.UUID  `json:"channel_id"`
	AlertID   *uuid.UUID `json:"alert_id"`
	Status    string     `json:"status"`
	Detail    string     `json:"detail"`
}

// ---- Delivery log ---------------------------------------------------------
// The unique index idx_notif_once makes a duplicate 'sent' for the same
// (channel, alert) a no-op, so RETURNING yields a row only on a real insert.
func (q *Queries) InsertNotificationLog(ctx context.Context, arg InsertNotificationLogParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, insertNotificationLog,
		arg.ChannelID,
		arg.AlertID,
		arg.Status,
		arg.Detail,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AlertID,
		&i.At,
		&i.Status,
		&i.Detail,
	)
	return i, err
}

const listNotifiableAlerts = `-- name: ListNotifiableAlerts :many
SELECT a.id, a.severity, a.message, a.escalated, a.opened_at, a.device_id
FROM alerts a
WHERE a.status <> 'resolved' AND a.opened_at > now() - interval '24 hours'
ORDER BY a.opened_at DESC
LIMIT 500
`

type ListNotifiableAlertsRow struct {
	ID        uuid.UUID `json:"id"`
	Severity  string    `json:"severity"`
	Message   string    `json:"message"`
	Escalated bool      `json:"escalated"`
	OpenedAt  time.Time `json:"opened_at"`
	DeviceID  uuid.UUID `json:"device_id"`
}

// Alerts worth notifying about: still open or escalated, opened recently.
func (q *Queries) ListNotifiableAlerts(ctx context.Context) ([]ListNotifiableAlertsRow, error) {
	rows, err := q.db.Query(ctx, listNotifiableAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotifiableAlertsRow{}
	for rows.Next() {
		var i ListNotifiableAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Severity,
			&i.Message,
			&i.Escalated,
			&i.OpenedAt,
			&i.DeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, name, type, target_encrypted, key_id, min_severity, quiet_start_min, quiet_end_min, enabled, created_at, updated_at FROM notification_channels ORDER BY created_at
`

func (q *Queries) ListNotificationChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.TargetEncrypted,
			&i.KeyID,
			&i.MinSeverity,
			&i.QuietStartMin,
			&i.QuietEndMin,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLog = `-- name: ListNotificationLog :many
SELECT id, channel_id, alert_id, at, status, detail FROM notification_log ORDER BY at DESC LIMIT 200
`

func (q *Queries) ListNotificationLog(ctx context.Context) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotificationLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AlertID,
			&i.At,
			&i.Status,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentNotificationPairs = `-- name: ListSentNotificationPairs :many
SELECT channel_id, alert_id FROM notification_log WHERE status = 'sent' AND alert_id IS NOT NULL
`

type ListSentNotificationPairsRow struct {
	ChannelID uuid.UUID  `json:"channel_id"`
	AlertID   *uuid.UUID `json:"alert_id"`
}

// (channel_id, alert_id) pairs already delivered, so the dispatcher skips them.
func (q *Queries) ListSentNotificationPairs(ctx context.Context) ([]ListSentNotificationPairsRow, error) {
	rows, err := q.db.Query(ctx, listSentNotificationPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSentNotificationPairsRow{}
	for rows.Next() {
		var i ListSentNotificationPairsRow
		if err := rows.Scan(&i.ChannelID, &i.AlertID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNotificationChannelEnabled = `-- name: SetNotificationChannelEnabled :one
UPDATE notification_channels SET enabled = $2, updated_at = now() WHERE id = $1 RETURNING id, name, type, target_encrypted, key_id, min_severity, quiet_start_min, quiet_end_min, enabled, created_at, updated_at
`

type SetNotificationChannelEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetNotificationChannelEnabled(ctx context.Context, arg SetNotificationChannelEnabledParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, setNotificationChannelEnabled, arg.ID, arg.Enabled)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.TargetEncrypted,
		&i.KeyID,
		&i.MinSeverity,
		&i.QuietStartMin,
		&i.QuietEndMin,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
