// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: operations_b.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFreeWorkOrderPart = `-- name: AddFreeWorkOrderPart :one
INSERT INTO work_order_parts (work_order_id, spare_part_id, description, quantity, unit_cost)
VALUES ($1, NULL, $2, $3, $4)
RETURNING id, work_order_id, spare_part_id, description, quantity, unit_cost, created_at
`

type AddFreeWorkOrderPartParams struct {
	WorkOrderID uuid.UUID `json:"work_order_id"`
	Description string    `json:"description"`
	Quantity    int32     `json:"quantity"`
	UnitCost    float64   `json:"unit_cost"`
}

// A part not tracked in stock (free-text): just record it, no decrement.
func (q *Queries) AddFreeWorkOrderPart(ctx context.Context, arg AddFreeWorkOrderPartParams) (WorkOrderPart, error) {
	row := q.db.QueryRow(ctx, addFreeWorkOrderPart,
		arg.WorkOrderID,
		arg.Description,
		arg.Quantity,
		arg.UnitCost,
	)
	var i WorkOrderPart
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.SparePartID,
		&i.Description,
		&i.Quantity,
		&i.UnitCost,
		&i.CreatedAt,
	)
	return i, err
}

const adjustSparePartStock = `-- name: AdjustSparePartStock :one
UPDATE spare_parts SET quantity = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, sku, category, location_id, quantity, min_quantity, unit_cost, notes, created_at, updated_at
`

type AdjustSparePartStockParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

// Absolute set of on-hand quantity (a stock count / receiving correction).
// The CHECK (quantity >= 0) constraint rejects negative results.
func (q *Queries) AdjustSparePartStock(ctx context.Context, arg AdjustSparePartStockParams) (SparePart, error) {
	row := q.db.QueryRow(ctx, adjustSparePartStock, arg.ID, arg.Quantity)
	var i SparePart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.LocationID,
		&i.Quantity,
		&i.MinQuantity,
		&i.UnitCost,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumePartToWorkOrder = `-- name: ConsumePartToWorkOrder :one

WITH dec AS (
    UPDATE spare_parts SET quantity = quantity - $3, updated_at = now()
    WHERE spare_parts.id = $2 AND spare_parts.quantity >= $3
    RETURNING spare_parts.id AS part_id, spare_parts.unit_cost AS part_cost
)
INSERT INTO work_order_parts (work_order_id, spare_part_id, description, quantity, unit_cost)
SELECT $1, dec.part_id, $4, $3, dec.part_cost FROM dec
RETURNING id, work_order_id, spare_part_id, description, quantity, unit_cost, created_at
`

type ConsumePartToWorkOrderParams struct {
	WorkOrderID uuid.UUID `json:"work_order_id"`
	ID          uuid.UUID `json:"id"`
	Quantity    int32     `json:"quantity"`
	Description string    `json:"description"`
}

// ---- Work-order parts (stock consumption) ---------------------------------
// Atomic: decrement stock AND record the consumption in ONE statement. The
// UPDATE's WHERE quantity >= $3 is the precondition; if it fails to match,
// the CTE yields no row, the INSERT inserts nothing, and :one returns
// ErrNoRows — which the handler maps to "insufficient stock" (409). This is
// the atomic-DB-signal pattern: no SELECT-then-UPDATE TOCTOU window.
func (q *Queries) ConsumePartToWorkOrder(ctx context.Context, arg ConsumePartToWorkOrderParams) (WorkOrderPart, error) {
	row := q.db.QueryRow(ctx, consumePartToWorkOrder,
		arg.WorkOrderID,
		arg.ID,
		arg.Quantity,
		arg.Description,
	)
	var i WorkOrderPart
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.SparePartID,
		&i.Description,
		&i.Quantity,
		&i.UnitCost,
		&i.CreatedAt,
	)
	return i, err
}

const createPurchase = `-- name: CreatePurchase :one

INSERT INTO purchases (description, vendor, category, location_id, system_id, device_id, amount, purchased_at, invoice_ref, notes)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, description, vendor, category, location_id, system_id, device_id, amount, purchased_at, invoice_ref, notes, created_at
`

type CreatePurchaseParams struct {
	Description string     `json:"description"`
	Vendor      *string    `json:"vendor"`
	Category    string     `json:"category"`
	LocationID  *uuid.UUID `json:"location_id"`
	SystemID    *uuid.UUID `json:"system_id"`
	DeviceID    *uuid.UUID `json:"device_id"`
	Amount      float64    `json:"amount"`
	PurchasedAt time.Time  `json:"purchased_at"`
	InvoiceRef  *string    `json:"invoice_ref"`
	Notes       *string    `json:"notes"`
}

// ---- Purchases ------------------------------------------------------------
func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, createPurchase,
		arg.Description,
		arg.Vendor,
		arg.Category,
		arg.LocationID,
		arg.SystemID,
		arg.DeviceID,
		arg.Amount,
		arg.PurchasedAt,
		arg.InvoiceRef,
		arg.Notes,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Vendor,
		&i.Category,
		&i.LocationID,
		&i.SystemID,
		&i.DeviceID,
		&i.Amount,
		&i.PurchasedAt,
		&i.InvoiceRef,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createSparePart = `-- name: CreateSparePart :one

INSERT INTO spare_parts (name, sku, category, location_id, quantity, min_quantity, unit_cost, notes)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, name, sku, category, location_id, quantity, min_quantity, unit_cost, notes, created_at, updated_at
`

type CreateSparePartParams struct {
	Name        string     `json:"name"`
	Sku         *string    `json:"sku"`
	Category    string     `json:"category"`
	LocationID  *uuid.UUID `json:"location_id"`
	Quantity    int32      `json:"quantity"`
	MinQuantity int32      `json:"min_quantity"`
	UnitCost    float64    `json:"unit_cost"`
	Notes       *string    `json:"notes"`
}

// ---- Spare parts ----------------------------------------------------------
func (q *Queries) CreateSparePart(ctx context.Context, arg CreateSparePartParams) (SparePart, error) {
	row := q.db.QueryRow(ctx, createSparePart,
		arg.Name,
		arg.Sku,
		arg.Category,
		arg.LocationID,
		arg.Quantity,
		arg.MinQuantity,
		arg.UnitCost,
		arg.Notes,
	)
	var i SparePart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.LocationID,
		&i.Quantity,
		&i.MinQuantity,
		&i.UnitCost,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePurchase = `-- name: DeletePurchase :exec
DELETE FROM purchases WHERE id = $1
`

func (q *Queries) DeletePurchase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePurchase, id)
	return err
}

const deleteSparePart = `-- name: DeleteSparePart :exec
DELETE FROM spare_parts WHERE id = $1
`

func (q *Queries) DeleteSparePart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSparePart, id)
	return err
}

const expensesByCategory = `-- name: ExpensesByCategory :many

SELECT category, COALESCE(SUM(amount),0)::double precision AS total, COUNT(*) AS count
FROM purchases
GROUP BY category
ORDER BY total DESC
`

type ExpensesByCategoryRow struct {
	Category string  `json:"category"`
	Total    float64 `json:"total"`
	Count    int64   `json:"count"`
}

// ---- Expenses (aggregation over the purchases ledger) ---------------------
// Expenses derive from the purchases ledger so the totals can never drift
// from their source rows. Work-order cost + system cost stay on their own
// pages (not merged here, to avoid double-counting a purchase logged for the
// same repair/license).
func (q *Queries) ExpensesByCategory(ctx context.Context) ([]ExpensesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, expensesByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpensesByCategoryRow{}
	for rows.Next() {
		var i ExpensesByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expensesByLocation = `-- name: ExpensesByLocation :many
SELECT p.location_id, l.name AS location_name,
       COALESCE(SUM(p.amount),0)::double precision AS total, COUNT(*) AS count
FROM purchases p
LEFT JOIN locations l ON l.id = p.location_id
GROUP BY p.location_id, l.name
ORDER BY total DESC
`

type ExpensesByLocationRow struct {
	LocationID   *uuid.UUID `json:"location_id"`
	LocationName *string    `json:"location_name"`
	Total        float64    `json:"total"`
	Count        int64      `json:"count"`
}

func (q *Queries) ExpensesByLocation(ctx context.Context) ([]ExpensesByLocationRow, error) {
	rows, err := q.db.Query(ctx, expensesByLocation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpensesByLocationRow{}
	for rows.Next() {
		var i ExpensesByLocationRow
		if err := rows.Scan(
			&i.LocationID,
			&i.LocationName,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSparePart = `-- name: GetSparePart :one
SELECT id, name, sku, category, location_id, quantity, min_quantity, unit_cost, notes, created_at, updated_at FROM spare_parts WHERE id = $1
`

func (q *Queries) GetSparePart(ctx context.Context, id uuid.UUID) (SparePart, error) {
	row := q.db.QueryRow(ctx, getSparePart, id)
	var i SparePart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.LocationID,
		&i.Quantity,
		&i.MinQuantity,
		&i.UnitCost,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLowStockParts = `-- name: ListLowStockParts :many
SELECT id, name, sku, category, location_id, quantity, min_quantity, unit_cost, notes, created_at, updated_at FROM spare_parts WHERE quantity <= min_quantity ORDER BY name
`

func (q *Queries) ListLowStockParts(ctx context.Context) ([]SparePart, error) {
	rows, err := q.db.Query(ctx, listLowStockParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SparePart{}
	for rows.Next() {
		var i SparePart
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Category,
			&i.LocationID,
			&i.Quantity,
			&i.MinQuantity,
			&i.UnitCost,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchases = `-- name: ListPurchases :many
SELECT id, description, vendor, category, location_id, system_id, device_id, amount, purchased_at, invoice_ref, notes, created_at FROM purchases ORDER BY purchased_at DESC, created_at DESC LIMIT 500
`

func (q *Queries) ListPurchases(ctx context.Context) ([]Purchase, error) {
	rows, err := q.db.Query(ctx, listPurchases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Purchase{}
	for rows.Next() {
		var i Purchase
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Vendor,
			&i.Category,
			&i.LocationID,
			&i.SystemID,
			&i.DeviceID,
			&i.Amount,
			&i.PurchasedAt,
			&i.InvoiceRef,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpareParts = `-- name: ListSpareParts :many
SELECT id, name, sku, category, location_id, quantity, min_quantity, unit_cost, notes, created_at, updated_at FROM spare_parts ORDER BY name LIMIT 500
`

func (q *Queries) ListSpareParts(ctx context.Context) ([]SparePart, error) {
	rows, err := q.db.Query(ctx, listSpareParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SparePart{}
	for rows.Next() {
		var i SparePart
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Category,
			&i.LocationID,
			&i.Quantity,
			&i.MinQuantity,
			&i.UnitCost,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrderParts = `-- name: ListWorkOrderParts :many
SELECT id, work_order_id, spare_part_id, description, quantity, unit_cost, created_at FROM work_order_parts WHERE work_order_id = $1 ORDER BY created_at
`

func (q *Queries) ListWorkOrderParts(ctx context.Context, workOrderID uuid.UUID) ([]WorkOrderPart, error) {
	rows, err := q.db.Query(ctx, listWorkOrderParts, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrderPart{}
	for rows.Next() {
		var i WorkOrderPart
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.SparePartID,
			&i.Description,
			&i.Quantity,
			&i.UnitCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSparePart = `-- name: UpdateSparePart :one
UPDATE spare_parts SET
    name = $2, sku = $3, category = $4, location_id = $5,
    min_quantity = $6, unit_cost = $7, notes = $8, updated_at = now()
WHERE id = $1
RETURNING id, name, sku, category, location_id, quantity, min_quantity, unit_cost, notes, created_at, updated_at
`

type UpdateSparePartParams struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Sku         *string    `json:"sku"`
	Category    string     `json:"category"`
	LocationID  *uuid.UUID `json:"location_id"`
	MinQuantity int32      `json:"min_quantity"`
	UnitCost    float64    `json:"unit_cost"`
	Notes       *string    `json:"notes"`
}

func (q *Queries) UpdateSparePart(ctx context.Context, arg UpdateSparePartParams) (SparePart, error) {
	row := q.db.QueryRow(ctx, updateSparePart,
		arg.ID,
		arg.Name,
		arg.Sku,
		arg.Category,
		arg.LocationID,
		arg.MinQuantity,
		arg.UnitCost,
		arg.Notes,
	)
	var i SparePart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.LocationID,
		&i.Quantity,
		&i.MinQuantity,
		&i.UnitCost,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
