// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pbx.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteStalePbxPhones = `-- name: DeleteStalePbxPhones :exec
DELETE FROM pbx_phones
WHERE device_id = $1 AND last_seen_at < $2 AND collection_source = $3
`

type DeleteStalePbxPhonesParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CollectionSource string    `json:"collection_source"`
}

func (q *Queries) DeleteStalePbxPhones(ctx context.Context, arg DeleteStalePbxPhonesParams) error {
	_, err := q.db.Exec(ctx, deleteStalePbxPhones, arg.DeviceID, arg.LastSeenAt, arg.CollectionSource)
	return err
}

const listPbxPhones = `-- name: ListPbxPhones :many
SELECT id, device_id, name, model, description, device_pool, collection_source, last_seen_at, extension, mac_address, ip_address FROM pbx_phones WHERE device_id = $1 ORDER BY name
`

func (q *Queries) ListPbxPhones(ctx context.Context, deviceID uuid.UUID) ([]PbxPhone, error) {
	rows, err := q.db.Query(ctx, listPbxPhones, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PbxPhone{}
	for rows.Next() {
		var i PbxPhone
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Name,
			&i.Model,
			&i.Description,
			&i.DevicePool,
			&i.CollectionSource,
			&i.LastSeenAt,
			&i.Extension,
			&i.MacAddress,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPbxPhone = `-- name: UpsertPbxPhone :exec
INSERT INTO pbx_phones (device_id, name, model, description, device_pool, collection_source, last_seen_at, extension, mac_address, ip_address)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (device_id, name) DO UPDATE SET
    model = EXCLUDED.model,
    description = EXCLUDED.description,
    device_pool = EXCLUDED.device_pool,
    collection_source = EXCLUDED.collection_source,
    last_seen_at = EXCLUDED.last_seen_at,
    extension = COALESCE(NULLIF(EXCLUDED.extension,''), pbx_phones.extension),
    mac_address = COALESCE(NULLIF(EXCLUDED.mac_address,''), pbx_phones.mac_address),
    ip_address = COALESCE(NULLIF(EXCLUDED.ip_address,''), pbx_phones.ip_address)
`

type UpsertPbxPhoneParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	Name             string    `json:"name"`
	Model            *string   `json:"model"`
	Description      *string   `json:"description"`
	DevicePool       *string   `json:"device_pool"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	Extension        *string   `json:"extension"`
	MacAddress       *string   `json:"mac_address"`
	IpAddress        *string   `json:"ip_address"`
}

func (q *Queries) UpsertPbxPhone(ctx context.Context, arg UpsertPbxPhoneParams) error {
	_, err := q.db.Exec(ctx, upsertPbxPhone,
		arg.DeviceID,
		arg.Name,
		arg.Model,
		arg.Description,
		arg.DevicePool,
		arg.CollectionSource,
		arg.LastSeenAt,
		arg.Extension,
		arg.MacAddress,
		arg.IpAddress,
	)
	return err
}
