// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: printer.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteStalePrinterSupplies = `-- name: DeleteStalePrinterSupplies :exec
DELETE FROM printer_supplies
WHERE device_id = $1 AND last_seen_at < $2 AND collection_source = $3
`

type DeleteStalePrinterSuppliesParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	LastSeenAt       time.Time `json:"last_seen_at"`
	CollectionSource string    `json:"collection_source"`
}

func (q *Queries) DeleteStalePrinterSupplies(ctx context.Context, arg DeleteStalePrinterSuppliesParams) error {
	_, err := q.db.Exec(ctx, deleteStalePrinterSupplies, arg.DeviceID, arg.LastSeenAt, arg.CollectionSource)
	return err
}

const listPrinterSupplies = `-- name: ListPrinterSupplies :many
SELECT id, device_id, supply_index, description, level, max_capacity, pct, collection_source, last_seen_at FROM printer_supplies WHERE device_id = $1 ORDER BY supply_index
`

func (q *Queries) ListPrinterSupplies(ctx context.Context, deviceID uuid.UUID) ([]PrinterSupply, error) {
	rows, err := q.db.Query(ctx, listPrinterSupplies, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrinterSupply{}
	for rows.Next() {
		var i PrinterSupply
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.SupplyIndex,
			&i.Description,
			&i.Level,
			&i.MaxCapacity,
			&i.Pct,
			&i.CollectionSource,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrinterSupply = `-- name: UpsertPrinterSupply :exec
INSERT INTO printer_supplies (device_id, supply_index, description, level, max_capacity, pct, collection_source, last_seen_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (device_id, supply_index) DO UPDATE SET
    description = EXCLUDED.description,
    level = EXCLUDED.level,
    max_capacity = EXCLUDED.max_capacity,
    pct = EXCLUDED.pct,
    collection_source = EXCLUDED.collection_source,
    last_seen_at = EXCLUDED.last_seen_at
`

type UpsertPrinterSupplyParams struct {
	DeviceID         uuid.UUID `json:"device_id"`
	SupplyIndex      int32     `json:"supply_index"`
	Description      *string   `json:"description"`
	Level            *int64    `json:"level"`
	MaxCapacity      *int64    `json:"max_capacity"`
	Pct              *int32    `json:"pct"`
	CollectionSource string    `json:"collection_source"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertPrinterSupply(ctx context.Context, arg UpsertPrinterSupplyParams) error {
	_, err := q.db.Exec(ctx, upsertPrinterSupply,
		arg.DeviceID,
		arg.SupplyIndex,
		arg.Description,
		arg.Level,
		arg.MaxCapacity,
		arg.Pct,
		arg.CollectionSource,
		arg.LastSeenAt,
	)
	return err
}
