// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AcknowledgeAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	AcknowledgeAlertBy(ctx context.Context, arg AcknowledgeAlertByParams) (Alert, error)
	// ---- Alert lifecycle timeline ---------------------------------------------
	AddAlertEvent(ctx context.Context, arg AddAlertEventParams) (AlertEvent, error)
	AddCredentialGroupMember(ctx context.Context, arg AddCredentialGroupMemberParams) error
	AddDeviceRole(ctx context.Context, arg AddDeviceRoleParams) error
	// A part not tracked in stock (free-text): just record it, no decrement.
	AddFreeWorkOrderPart(ctx context.Context, arg AddFreeWorkOrderPartParams) (WorkOrderPart, error)
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	AddSubnetCredential(ctx context.Context, arg AddSubnetCredentialParams) error
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	AddWorkOrderEvent(ctx context.Context, arg AddWorkOrderEventParams) (WorkOrderEvent, error)
	// Absolute set of on-hand quantity (a stock count / receiving correction).
	// The CHECK (quantity >= 0) constraint rejects negative results.
	AdjustSparePartStock(ctx context.Context, arg AdjustSparePartStockParams) (SparePart, error)
	// Fleet-wide collect-job rollup by status (acceptance / queue-visibility report).
	AgentJobStatusCounts(ctx context.Context) ([]AgentJobStatusCountsRow, error)
	// Alert volume + responsiveness over the window. MTTA/MTTR are NULL until alerts
	// with acknowledged/resolved timestamps exist (honest empty state). $1 = window.
	AlertAnalyticsSummary(ctx context.Context, dollar_1 string) (AlertAnalyticsSummaryRow, error)
	// Alerts opened per time bucket, split by severity, for the alert-rate trend.
	// $1 = granularity, $2 = window.
	AlertOpenedSeries(ctx context.Context, arg AlertOpenedSeriesParams) ([]AlertOpenedSeriesRow, error)
	// Distinct filter values (+counts) for the audit filter UI, in one round-trip.
	AuditFacets(ctx context.Context) ([]AuditFacetsRow, error)
	BindCredentialGroup(ctx context.Context, arg BindCredentialGroupParams) (CredentialBinding, error)
	// Assign vlan/device_class/location to many devices at once (multi-select).
	// Only the provided (non-null) fields are changed — COALESCE keeps the rest —
	// so an operator can set just location, just class, just vlan, or any combo.
	BulkAssignClassification(ctx context.Context, arg BulkAssignClassificationParams) (int64, error)
	// Lost-key recovery: wipe only the secret fields; preserve the record,
	// metadata, assignments and group memberships. Flag for re-entry.
	ClearAllCredentialSecrets(ctx context.Context) error
	ClearReentryFlag(ctx context.Context, id uuid.UUID) error
	ClearSubnetCredentials(ctx context.Context, subnetID uuid.UUID) error
	// Collect-job rollup for the devices a discovery job enrolled — lets the UI/API show
	// "Discovery complete · collecting N" while deep collection drains AFTER the scan's
	// probe/enroll phase finishes. retry_waiting (backoff) is split from queued so the
	// operator sees jobs that are waiting vs ready. The scan is "settled" when
	// queued + retry_waiting + running all reach 0.
	CollectionProgressForJob(ctx context.Context, jobID uuid.UUID) (CollectionProgressForJobRow, error)
	CompleteAgentJob(ctx context.Context, arg CompleteAgentJobParams) error
	// ---- Work-order parts (stock consumption) ---------------------------------
	// Atomic: decrement stock AND record the consumption in ONE statement. The
	// UPDATE's WHERE quantity >= $3 is the precondition; if it fails to match,
	// the CTE yields no row, the INSERT inserts nothing, and :one returns
	// ErrNoRows — which the handler maps to "insufficient stock" (409). This is
	// the atomic-DB-signal pattern: no SELECT-then-UPDATE TOCTOU window.
	ConsumePartToWorkOrder(ctx context.Context, arg ConsumePartToWorkOrderParams) (WorkOrderPart, error)
	// In-flight collection jobs for a device (queued or dispatched) — used to avoid
	// enqueuing a duplicate when a scan re-routes the same device to its site agent.
	CountActiveDeviceAgentJobs(ctx context.Context, deviceID *uuid.UUID) (int64, error)
	// Per-agent job rollup by status (queued / dispatched / done / failed).
	CountAgentJobsByStatusForAgent(ctx context.Context, agentID uuid.UUID) ([]CountAgentJobsByStatusForAgentRow, error)
	// Count of this agent's collect_os jobs currently waiting on a LOAD-INDUCED transient
	// backoff (winrm negotiate / connect-timeout requeued, next_attempt_at in the future).
	// A high count means the agent's WinRM listeners are saturated under a from-zero
	// storm; the dispatcher uses it to throttle new work (shrink the poll budget) so the
	// listeners recover instead of being fed more concurrent negotiations. As the backoff
	// queue drains the count falls and the budget reopens — a self-regulating governor.
	CountAgentLoadBackoff(ctx context.Context, agentID uuid.UUID) (int64, error)
	// Overview KPIs: total versions, distinct devices backed up, and changes today.
	CountConfigBackupStats(ctx context.Context) (CountConfigBackupStatsRow, error)
	CountCredentialsNeedingReentry(ctx context.Context) (int64, error)
	// Total live devices (for the dashboard total / discovered split).
	CountDevices(ctx context.Context) (int64, error)
	CountDevicesNeedingAttention(ctx context.Context) (int64, error)
	// Jobs currently handed to the agent and not yet reported back — the in-flight
	// count subtracted from the dispatch cap to compute the poll budget.
	CountDispatchedAgentJobs(ctx context.Context, agentID uuid.UUID) (int64, error)
	// ===== Credential secret accounting / recovery =============================
	CountEncryptedCredentials(ctx context.Context) (int64, error)
	// Systems whose license OR support expires within 90 days (or already has).
	CountExpiringSystems(ctx context.Context) (int64, error)
	// Failed jobs for one agent (for the agent detail page + Data Quality count).
	CountFailedAgentJobs(ctx context.Context, agentID uuid.UUID) (int64, error)
	// Channels whose camera IP matched an already-discovered standalone camera device.
	CountLinkedNVRChannels(ctx context.Context) (int64, error)
	CountMibPacksBySource(ctx context.Context) ([]CountMibPacksBySourceRow, error)
	CountMibWalkRows(ctx context.Context, deviceID uuid.UUID) (int64, error)
	// Total camera channels collected across all recorders (CCTV summary). Channels
	// are NOT inventory devices, so this is reported separately and never folded into
	// the device count.
	CountNVRChannels(ctx context.Context) (int64, error)
	CountOpenAlerts(ctx context.Context) (int64, error)
	CountOpenWorkOrders(ctx context.Context) (int64, error)
	CountSSHCliBySource(ctx context.Context, deviceID uuid.UUID) ([]CountSSHCliBySourceRow, error)
	// Count of a job's enrolled devices still eligible for automatic self-heal (terminal
	// load-induced transient failure, no evidence, round budget remaining). Drives the
	// job-detail phase: > 0 keeps the job "self-heal" (not "complete") even while no
	// collect_os job is in flight (the self-heal cooldown window).
	CountSelfHealEligibleForJob(ctx context.Context, jobID uuid.UUID) (int64, error)
	// Blobs sealed under a key id other than the one currently loaded.
	CountUndecryptableCredentials(ctx context.Context, keyID string) (int64, error)
	CountUnknownMACs(ctx context.Context) (int32, error)
	CountUsersWithPassword(ctx context.Context) (int64, error)
	// How many profiles still reference a credential (for orphan-credential cleanup on
	// profile delete).
	CountVendorProfilesUsingCredential(ctx context.Context, credentialID *uuid.UUID) (int64, error)
	// Headline count for the "N devices, M virtual" indicator.
	CountVirtualDevices(ctx context.Context) (int64, error)
	CreateAgentJob(ctx context.Context, arg CreateAgentJobParams) (AgentJob, error)
	// ---- Alert rules ----------------------------------------------------------
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	CreateCredentialGroup(ctx context.Context, arg CreateCredentialGroupParams) (CredentialGroup, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateDeviceTemplate(ctx context.Context, arg CreateDeviceTemplateParams) (DeviceTemplate, error)
	CreateDiscoveryJob(ctx context.Context, arg CreateDiscoveryJobParams) (DiscoveryJob, error)
	// Persist one live-discovery event for completed-job playback (the live SSE feed
	// is served from the in-memory hub; this is the durable history).
	CreateDiscoveryJobEvent(ctx context.Context, arg CreateDiscoveryJobEventParams) (int64, error)
	CreateDiscoveryResult(ctx context.Context, arg CreateDiscoveryResultParams) (DiscoveryResult, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateLookup(ctx context.Context, arg CreateLookupParams) (Lookup, error)
	// ---- Maintenance windows (alert suppression) ------------------------------
	CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (MaintenanceWindow, error)
	CreateMibFile(ctx context.Context, arg CreateMibFileParams) (MibFile, error)
	CreateMibPack(ctx context.Context, arg CreateMibPackParams) (MibPack, error)
	// ---- Notification channels ------------------------------------------------
	CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error)
	CreateOIDMapping(ctx context.Context, arg CreateOIDMappingParams) (OidMapping, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	// ---- Purchases ------------------------------------------------------------
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	// Relay Agent / Site Collector persistence. No secrets stored here; the agent
	// token is stored only as a SHA-256 hash.
	CreateRelayAgent(ctx context.Context, arg CreateRelayAgentParams) (RelayAgent, error)
	CreateReportSchedule(ctx context.Context, arg CreateReportScheduleParams) (ReportSchedule, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// ---- Spare parts ----------------------------------------------------------
	CreateSparePart(ctx context.Context, arg CreateSparePartParams) (SparePart, error)
	CreateSubnet(ctx context.Context, arg CreateSubnetParams) (Subnet, error)
	CreateSystem(ctx context.Context, arg CreateSystemParams) (System, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVendorFingerprint(ctx context.Context, arg CreateVendorFingerprintParams) (VendorFingerprint, error)
	// Vendor connection profile CRUD + resolution. No secrets are stored here; the
	// credential reference points at the encrypted credentials table.
	CreateVendorProfile(ctx context.Context, arg CreateVendorProfileParams) (VendorConnectionProfile, error)
	CreateWebPortCandidate(ctx context.Context, arg CreateWebPortCandidateParams) (WebPortCandidate, error)
	CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error)
	// Whether a group is already bound to a location (guards duplicate binds).
	CredentialGroupLocationBound(ctx context.Context, arg CredentialGroupLocationBoundParams) (bool, error)
	DatastoreSummaryByHost(ctx context.Context) ([]DatastoreSummaryByHostRow, error)
	DeleteAlertRule(ctx context.Context, id uuid.UUID) error
	DeleteAllMibWalkRows(ctx context.Context, deviceID uuid.UUID) error
	DeleteBackupRun(ctx context.Context, id int64) error
	// Removing a credential un-binds it from devices (FK ON DELETE SET NULL) and
	// drops its group memberships (FK ON DELETE CASCADE).
	DeleteCredential(ctx context.Context, id uuid.UUID) error
	// Hard delete (cascades to inventory child rows via FK ON DELETE CASCADE).
	DeleteDevice(ctx context.Context, id uuid.UUID) error
	DeleteDeviceLifecycle(ctx context.Context, deviceID uuid.UUID) error
	// Remove a device's TCP reachability checks so a fresh, evidence-based one can
	// replace them (used when a scan re-points the check at a port the host
	// actually answered on). SNMP/metric checks are left untouched.
	DeleteDeviceReachabilityChecks(ctx context.Context, deviceID uuid.UUID) error
	DeleteDeviceTemplate(ctx context.Context, id uuid.UUID) error
	// Bulk hard delete (multi-select). Returns the number of rows removed.
	DeleteDevices(ctx context.Context, dollar_1 []uuid.UUID) (int64, error)
	// Removes a job and its results (discovery_results FK ON DELETE CASCADE).
	DeleteDiscoveryJob(ctx context.Context, id uuid.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteLocation(ctx context.Context, id uuid.UUID) error
	DeleteLookup(ctx context.Context, id uuid.UUID) error
	DeleteMaintenanceWindow(ctx context.Context, id uuid.UUID) error
	// Clear operator-entered roles before re-writing them (virtual-device edit).
	DeleteManualDeviceRoles(ctx context.Context, deviceID uuid.UUID) error
	DeleteMibPack(ctx context.Context, id uuid.UUID) error
	DeleteMibPackTable(ctx context.Context, id uuid.UUID) error
	DeleteMibWalkRows(ctx context.Context, arg DeleteMibWalkRowsParams) error
	DeleteMonitoringCheck(ctx context.Context, id uuid.UUID) error
	DeleteNotificationChannel(ctx context.Context, id uuid.UUID) error
	DeleteOIDMapping(ctx context.Context, id uuid.UUID) error
	DeletePermission(ctx context.Context, id uuid.UUID) error
	DeletePurchase(ctx context.Context, id uuid.UUID) error
	DeleteRelayAgent(ctx context.Context, id uuid.UUID) error
	DeleteReportSchedule(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, id uuid.UUID) error
	DeleteSSHCliResultsForSource(ctx context.Context, arg DeleteSSHCliResultsForSourceParams) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteSnooze(ctx context.Context, arg DeleteSnoozeParams) error
	DeleteSparePart(ctx context.Context, id uuid.UUID) error
	DeleteStaleARP(ctx context.Context, arg DeleteStaleARPParams) error
	// Prune APs for a controller not refreshed in the latest collection of a source.
	DeleteStaleAccessPoints(ctx context.Context, arg DeleteStaleAccessPointsParams) error
	DeleteStaleBMCSensors(ctx context.Context, arg DeleteStaleBMCSensorsParams) error
	DeleteStaleDatastores(ctx context.Context, arg DeleteStaleDatastoresParams) error
	DeleteStaleHAMembers(ctx context.Context, arg DeleteStaleHAMembersParams) error
	DeleteStaleHostNics(ctx context.Context, arg DeleteStaleHostNicsParams) error
	DeleteStaleInterfaces(ctx context.Context, arg DeleteStaleInterfacesParams) error
	DeleteStaleLicenses(ctx context.Context, arg DeleteStaleLicensesParams) error
	DeleteStaleMACEntries(ctx context.Context, arg DeleteStaleMACEntriesParams) error
	DeleteStaleNeighbors(ctx context.Context, arg DeleteStaleNeighborsParams) error
	DeleteStaleNetworks(ctx context.Context, arg DeleteStaleNetworksParams) error
	DeleteStaleOSDisks(ctx context.Context, arg DeleteStaleOSDisksParams) error
	DeleteStaleOSNics(ctx context.Context, arg DeleteStaleOSNicsParams) error
	DeleteStaleOSProcesses(ctx context.Context, arg DeleteStaleOSProcessesParams) error
	DeleteStaleOSRoles(ctx context.Context, arg DeleteStaleOSRolesParams) error
	DeleteStaleOSServices(ctx context.Context, arg DeleteStaleOSServicesParams) error
	DeleteStaleOSSoftware(ctx context.Context, arg DeleteStaleOSSoftwareParams) error
	DeleteStalePbxPhones(ctx context.Context, arg DeleteStalePbxPhonesParams) error
	DeleteStalePortVlans(ctx context.Context, arg DeleteStalePortVlansParams) error
	DeleteStalePrinterSupplies(ctx context.Context, arg DeleteStalePrinterSuppliesParams) error
	DeleteStaleServerStorage(ctx context.Context, arg DeleteStaleServerStorageParams) error
	// Prune links not re-seen since the cutoff (a neighbor that stopped reporting).
	DeleteStaleTopologyLinks(ctx context.Context, lastSeenAt time.Time) (int64, error)
	DeleteStaleVMDisks(ctx context.Context, arg DeleteStaleVMDisksParams) error
	DeleteStaleVMNics(ctx context.Context, arg DeleteStaleVMNicsParams) error
	DeleteStaleVlans(ctx context.Context, arg DeleteStaleVlansParams) error
	DeleteStaleVpnTunnels(ctx context.Context, arg DeleteStaleVpnTunnelsParams) error
	DeleteStaleWirelessClients(ctx context.Context, arg DeleteStaleWirelessClientsParams) error
	DeleteStaleWirelessRadios(ctx context.Context, arg DeleteStaleWirelessRadiosParams) error
	DeleteStaleWirelessSSIDs(ctx context.Context, arg DeleteStaleWirelessSSIDsParams) error
	DeleteSubnet(ctx context.Context, id uuid.UUID) error
	DeleteSystem(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	DeleteVendorFingerprint(ctx context.Context, id uuid.UUID) error
	DeleteVendorProfile(ctx context.Context, id uuid.UUID) error
	DeleteWebPortCandidate(ctx context.Context, id uuid.UUID) error
	// Replace an event set for a source (collectors re-publish the current window).
	DeleteWirelessEventsForSource(ctx context.Context, arg DeleteWirelessEventsForSourceParams) error
	// Most recent successful collection signal per device (deep OS inventory, ok virtualization
	// collection, or a successful credential test) — feeds the collection-stale state alert.
	DeviceCollectionRecency(ctx context.Context) ([]DeviceCollectionRecencyRow, error)
	DeviceCountByCategory(ctx context.Context) ([]DeviceCountByCategoryRow, error)
	DeviceCountByStatus(ctx context.Context) ([]DeviceCountByStatusRow, error)
	// Per-device aggregate over ALL credential-test outcomes (every credential, every kind),
	// so management classification NEVER loses a signal to latest-per-kind masking (e.g. a
	// legacy WSMan auth_ok_operation_fault hidden behind a sibling .\administrator auth_failed,
	// or an http_basic success hidden behind a winrm auth_failed). This is the read model for
	// the classification rule: a host is credential_failed ONLY if some credential was cleanly
	// auth-rejected AND nothing authenticated by any supported method. Booleans:
	//   any_success   — any credential succeeded (deep OR web)
	//   web_success   — a WEB/identity login succeeded (http_basic/http) — authenticates but is
	//                   not deep management
	//   legacy_authok — a credential AUTHENTICATED but the WSMan op faulted (legacy WSMan 2.0)
	//                   — valid cred, needs an agent/deep collector
	//   not_authorized— a credential AUTHENTICATED but the host denied access (UAC / DCOM /
	//                   policy) — distinct from a wrong password
	//   auth_rejected — a credential was cleanly rejected (wrong username/password)
	DeviceCredentialSignals(ctx context.Context) ([]DeviceCredentialSignalsRow, error)
	// Per-device hypervisor.type fact (esxi/hyperv) — feeds the derived server_role so the UI
	// can distinguish an ESXi host from a Hyper-V host without re-reading every device's facts.
	DeviceHypervisorTypes(ctx context.Context) ([]DeviceHypervisorTypesRow, error)
	// A discovered (non-virtual) device whose collected NIC MAC matches, normalized so
	// colon/dash/case differences don't matter — used to reverse-link a Hyper-V guest VM to
	// an existing device by MAC when its guest IP is unavailable (no integration services).
	DeviceIDByMAC(ctx context.Context, mac string) (uuid.UUID, error)
	// Per-device availability over the window: sample/up counts (for uptime %),
	// latency, and flap count (status transitions). Ordered worst-first so the UI can
	// show "worst performers" and a flapping list. $1 = window (e.g. '24 hours').
	DeviceUptimeRanking(ctx context.Context, dollar_1 string) ([]DeviceUptimeRankingRow, error)
	// Mark open, unacknowledged, not-yet-escalated alerts as escalated once they
	// have aged past their rule's escalate_after_minutes (0 = never).
	EscalateStaleAlerts(ctx context.Context) ([]EscalateStaleAlertsRow, error)
	// ---- Expenses (aggregation over the purchases ledger) ---------------------
	// Expenses derive from the purchases ledger so the totals can never drift
	// from their source rows. Work-order cost + system cost stay on their own
	// pages (not merged here, to avoid double-counting a purchase logged for the
	// same repair/license).
	ExpensesByCategory(ctx context.Context) ([]ExpensesByCategoryRow, error)
	ExpensesByLocation(ctx context.Context) ([]ExpensesByLocationRow, error)
	// Reconcile orphaned scans: a scan runs as an in-process goroutine, so any job
	// still 'running'/'pending' after a restart (or that hangs past a max duration)
	// has no live worker and must be failed. $1 = cutoff (started/created before
	// this), $2 = error message. Returns the number of jobs reconciled.
	FailStaleScanJobs(ctx context.Context, arg FailStaleScanJobsParams) (int64, error)
	// First step of the IP→MAC→port→path search.
	FindMACByIP(ctx context.Context, ipAddress netip.Addr) ([]FindMACByIPRow, error)
	// Topology search: which switch + port + VLAN carries a MAC?
	FindMACOnSwitches(ctx context.Context, mac string) ([]FindMACOnSwitchesRow, error)
	// Path Finder: which NVR/DVR(s) record this camera device, with the channel +
	// recording status, so a camera's path shows the recorder it feeds.
	FindNVRsForCamera(ctx context.Context, cameraDeviceID *uuid.UUID) ([]FindNVRsForCameraRow, error)
	// Path Finder: which phone(s) carry this IP, the directory number, registration
	// status + the CM node (registrar), and the owning PBX device (CUCM cluster).
	FindPhoneByIP(ctx context.Context, ipAddress *string) ([]FindPhoneByIPRow, error)
	// Path Finder: resolve a MAC to the IP phone that carries it (CUCM SEP<mac>),
	// with directory number, registration + registrar. Compares the MAC ignoring
	// separators/case so 00:23:eb:.. , 0023eb.. and 00-23-.. all match.
	FindPhoneByMAC(ctx context.Context, translate string) ([]FindPhoneByMACRow, error)
	// Path Finder: exact-match a search term (MAC / IP / hostname) to an associated
	// wireless client that has a known AP, so the traced path can START at the access
	// point the client is connected to. Exact (not substring) match avoids tracing an
	// unrelated client. Only rows with a known ap_name qualify (we need an AP to start
	// at; without one the normal FDB path still applies).
	FindWirelessClient(ctx context.Context, lower string) ([]FindWirelessClientRow, error)
	// Analytics aggregations powering the enterprise dashboards (Dashboard, NOC
	// Wallboard, Health Overview). All grounded in real collected data:
	// monitoring_samples (reachability time-series) and alerts. Bucket granularity
	// and window are passed as text params so one query serves 24h/7d/30d.
	//
	// Percentages are intentionally NOT computed in SQL (kept as raw up/total int
	// counts) so the result types stay clean float8/bigint; the handler derives %.
	// Latency / MTTA / MTTR are nullable: avg() over no rows is NULL, which must
	// read as "no data" (not a fake 0) — hence bare aggregates, no ::float8 cast.
	// Fleet-wide reachability over time: one row per time bucket with up/down/warning
	// sample counts and latency stats. $1 = date_trunc granularity ('hour'|'day'),
	// $2 = window (e.g. '24 hours', '7 days'). Powers the availability trend chart.
	FleetAvailabilitySeries(ctx context.Context, arg FleetAvailabilitySeriesParams) ([]FleetAvailabilitySeriesRow, error)
	// Single-row rollup over the same window: sample counts (for uptime %), distinct
	// devices, and latency stats. Used for the headline availability KPI / SLA figure.
	FleetAvailabilitySummary(ctx context.Context, dollar_1 string) (FleetAvailabilitySummaryRow, error)
	FlowOverview(ctx context.Context, at time.Time) (FlowOverviewRow, error)
	// Path Finder: the AP a wireless client is associated to (scoped to its
	// controller), to read the AP's MAC/IP and resolve its wired uplink switch via the
	// FDB.
	GetAccessPointByName(ctx context.Context, arg GetAccessPointByNameParams) (GetAccessPointByNameRow, error)
	GetAgentJob(ctx context.Context, id uuid.UUID) (AgentJob, error)
	GetAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	GetBMCInfo(ctx context.Context, deviceID uuid.UUID) (BmcInfo, error)
	GetBackupRunContent(ctx context.Context, id int64) (GetBackupRunContentRow, error)
	GetCameraInfo(ctx context.Context, deviceID uuid.UUID) (CameraInfo, error)
	GetCollectionHealth(ctx context.Context, deviceID uuid.UUID) ([]VhCollectionHealth, error)
	// Full row including the encrypted blob — used only by the key-gated
	// content/diff endpoints, never by list responses.
	GetConfigBackupContent(ctx context.Context, id uuid.UUID) (GetConfigBackupContentRow, error)
	GetCredential(ctx context.Context, id uuid.UUID) (Credential, error)
	GetDevice(ctx context.Context, id uuid.UUID) (Device, error)
	GetDeviceLifecycle(ctx context.Context, deviceID uuid.UUID) (DeviceLifecycle, error)
	GetDeviceTemplate(ctx context.Context, id uuid.UUID) (DeviceTemplate, error)
	GetDiscoveryJob(ctx context.Context, id uuid.UUID) (DiscoveryJob, error)
	// ===== Encryption key lifecycle (metadata only — never the key) ===========
	GetEncryptionMetadata(ctx context.Context) (EncryptionMetadatum, error)
	GetFirewallStatus(ctx context.Context, deviceID uuid.UUID) (FirewallStatus, error)
	// Drift lookup: the most recent backup's hash for this device.
	GetLatestConfigBackup(ctx context.Context, deviceID uuid.UUID) (GetLatestConfigBackupRow, error)
	GetLocation(ctx context.Context, id uuid.UUID) (Location, error)
	GetMibPack(ctx context.Context, id uuid.UUID) (MibPack, error)
	GetMonitoringCheck(ctx context.Context, id uuid.UUID) (MonitoringCheck, error)
	GetNVRInfo(ctx context.Context, deviceID uuid.UUID) (NvrInfo, error)
	GetNotificationChannel(ctx context.Context, id uuid.UUID) (NotificationChannel, error)
	// Deep OS Inventory queries. The 1:1 summary is upserted per device; the 1:N
	// collections follow the prune-on-poll pattern (Upsert all rows with last_seen_at
	// = poll, then DeleteStale* removes rows from the same source not seen this poll).
	GetOSInventory(ctx context.Context, deviceID uuid.UUID) (OsInventory, error)
	GetRelayAgent(ctx context.Context, id uuid.UUID) (RelayAgent, error)
	GetRelayAgentByToken(ctx context.Context, tokenHash string) (RelayAgent, error)
	GetReportSchedule(ctx context.Context, id uuid.UUID) (ReportSchedule, error)
	// Resolve a live session to its user (joined), enforcing expiry.
	GetSession(ctx context.Context, tokenHash string) (GetSessionRow, error)
	GetSparePart(ctx context.Context, id uuid.UUID) (SparePart, error)
	GetSystem(ctx context.Context, id uuid.UUID) (System, error)
	GetUPSStatus(ctx context.Context, deviceID uuid.UUID) (UpsStatus, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVendorProfile(ctx context.Context, id uuid.UUID) (VendorConnectionProfile, error)
	// The (device, vendor_type) profile if one exists (any enabled state) — keeps the
	// "Add controller" flow idempotent (update in place rather than create a duplicate).
	GetVendorProfileForDeviceVendor(ctx context.Context, arg GetVendorProfileForDeviceVendorParams) (VendorConnectionProfile, error)
	GetWLANControllerInfo(ctx context.Context, deviceID uuid.UUID) (WlanControllerInfo, error)
	GetWirelessControllerSummary(ctx context.Context, deviceID uuid.UUID) (WirelessControllerSummary, error)
	GetWorkOrder(ctx context.Context, id uuid.UUID) (WorkOrder, error)
	// Atomically bump the per-host scan progress counter (safe under the concurrent
	// per-host workers). Drives the running-scan 0→100% progress bar.
	IncrDiscoveryJobScanned(ctx context.Context, id uuid.UUID) error
	// ===== Audit log ===========================================================
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertBackupRun(ctx context.Context, arg InsertBackupRunParams) (InsertBackupRunRow, error)
	InsertBackupRunWithContent(ctx context.Context, arg InsertBackupRunWithContentParams) (InsertBackupRunWithContentRow, error)
	InsertConfigBackup(ctx context.Context, arg InsertConfigBackupParams) (InsertConfigBackupRow, error)
	InsertCredentialTestResult(ctx context.Context, arg InsertCredentialTestResultParams) error
	// Credential test history persistence + read models. No secrets are ever stored
	// or returned — only outcome metadata.
	InsertCredentialTestRun(ctx context.Context, arg InsertCredentialTestRunParams) (CredentialTestRun, error)
	InsertFlowRecord(ctx context.Context, arg InsertFlowRecordParams) error
	InsertMibObject(ctx context.Context, arg InsertMibObjectParams) error
	// ===== Pack files =====
	InsertMibPackFile(ctx context.Context, arg InsertMibPackFileParams) error
	// ===== Raw walk rows =====
	InsertMibWalkRow(ctx context.Context, arg InsertMibWalkRowParams) error
	InsertMonitoringSample(ctx context.Context, arg InsertMonitoringSampleParams) error
	// ---- Delivery log ---------------------------------------------------------
	// The unique index idx_notif_once makes a duplicate 'sent' for the same
	// (channel, alert) a no-op, so RETURNING yields a row only on a real insert.
	InsertNotificationLog(ctx context.Context, arg InsertNotificationLogParams) (NotificationLog, error)
	InsertWirelessEvent(ctx context.Context, arg InsertWirelessEventParams) error
	// Per discovery job: how many of its devices still have a collect_os job IN FLIGHT
	// (pending) and how many are still ELIGIBLE for automatic self-heal (healing). A job is
	// NOT fully settled while either is > 0 — so the Scan Jobs LIST shows "collecting" or
	// "self-heal" instead of a premature "complete", honestly reflecting that the self-heal
	// sweep will still re-collect terminal transient failures. Each device is attributed to
	// its MOST RECENT scan job (a device has one row, reconciled by IP across re-scans).
	// Self-heal eligible = latest collect_os job failed with a load-induced transient
	// category, no os_inventory evidence, and the 4-round/24h budget is not yet burned
	// (mirrors ListSelfHealCandidates without the cooldown — the job is unsettled for the
	// whole window, not only after the cooldown elapses). Returns only unsettled jobs.
	JobsCollectionState(ctx context.Context) ([]JobsCollectionStateRow, error)
	LastSuccessfulBackup(ctx context.Context) (LastSuccessfulBackupRow, error)
	// The most recent ONVIF/ISAPI credential-test outcome for a device — the CCTV
	// fleet skip-guard reads this to avoid re-attempting a device that recently
	// auth-failed (which would accumulate failed logins toward a Hikvision IP
	// lockout). When two attempts share a timestamp (ONVIF + ISAPI in one batch) the
	// auth_failed row wins the tie, so a transport failure on one protocol never
	// masks an auth rejection on the other. No rows ⇒ never tested ⇒ safe to attempt.
	LatestCCTVCredTest(ctx context.Context, deviceID uuid.UUID) (LatestCCTVCredTestRow, error)
	// Latest collect_os agent job per device (status/category/error/finished) — feeds the
	// relay-job-failed queue + "superseded by later success" detection.
	LatestCollectJobs(ctx context.Context) ([]LatestCollectJobsRow, error)
	// The most recent result per (device, credential-kind). This is the read model
	// behind Management Access Coverage's test-result source, the unmanaged reasons
	// (failed / not-tested / stale), and the Inventory access filters. One row per
	// (device, kind) — the latest outcome for that protocol on that device.
	LatestDeviceKindResults(ctx context.Context) ([]LatestDeviceKindResultsRow, error)
	// The most recent scan probe_data for a device (open ports, evidence, etc.) —
	// used to repair its reachability check from the ports it actually answered on.
	LatestDeviceProbeData(ctx context.Context, deviceID *uuid.UUID) ([]byte, error)
	// Every VM that is linked to a discovered device, with its parent host — so a device that IS
	// a VM derives server_role=virtual_machine and shows "hosted on <host>" (reverse link).
	LinkedVMParents(ctx context.Context) ([]LinkedVMParentsRow, error)
	ListARPForDevice(ctx context.Context, deviceID uuid.UUID) ([]ListARPForDeviceRow, error)
	ListAccessPoints(ctx context.Context, controllerDeviceID uuid.UUID) ([]AccessPoint, error)
	ListActiveMaintenanceWindows(ctx context.Context) ([]MaintenanceWindow, error)
	ListActiveSnoozes(ctx context.Context) ([]ListActiveSnoozesRow, error)
	ListAgentJobs(ctx context.Context, arg ListAgentJobsParams) ([]ListAgentJobsRow, error)
	ListAlertEvents(ctx context.Context, alertID uuid.UUID) ([]AlertEvent, error)
	ListAlertRules(ctx context.Context) ([]AlertRule, error)
	ListAlerts(ctx context.Context) ([]Alert, error)
	// Alerts whose auto-bridge (or manual link) points at this work order.
	ListAlertsByWorkOrder(ctx context.Context, workOrderID *uuid.UUID) ([]ListAlertsByWorkOrderRow, error)
	// Alerts joined with their rule (name + condition) and device (name/ip/category/site) so the
	// Alerts page can group, filter, and show clear per-alert context without extra round-trips.
	ListAlertsEnriched(ctx context.Context) ([]ListAlertsEnrichedRow, error)
	ListAllCollectionHealth(ctx context.Context) ([]ListAllCollectionHealthRow, error)
	ListAllDatastores(ctx context.Context) ([]ListAllDatastoresRow, error)
	// Every live device (the Inventory page), ordered for grouped display.
	ListAllDevices(ctx context.Context) ([]Device, error)
	// Used by the topology graph to build the full picture.
	ListAllTopologyLinks(ctx context.Context) ([]ListAllTopologyLinksRow, error)
	// The asset register: every tracked asset (has a lifecycle row) with its device
	// identity, ordered by soonest warranty expiry.
	ListAssetLifecycle(ctx context.Context) ([]ListAssetLifecycleRow, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	// Deep filtering: any subset of category / actor / entity_type / action / free
	// text (summary) / time range. NULL args are ignored.
	ListAuditLogFiltered(ctx context.Context, arg ListAuditLogFilteredParams) ([]AuditLog, error)
	ListBMCSensors(ctx context.Context, deviceID uuid.UUID) ([]BmcSensor, error)
	// Excludes the content blob (can be large); content is fetched on demand for download.
	ListBackupRuns(ctx context.Context) ([]ListBackupRunsRow, error)
	ListChildLocations(ctx context.Context, parentID *uuid.UUID) ([]Location, error)
	// Metadata only (no content_encrypted) — newest first.
	ListConfigBackupsByDevice(ctx context.Context, arg ListConfigBackupsByDeviceParams) ([]ListConfigBackupsByDeviceRow, error)
	// Per (device, protocol): whether ANY attempt succeeded and how many were tried.
	// Drives the trust audit's "attempted vs succeeded collectors" per device.
	ListCredTestProtocols(ctx context.Context) ([]ListCredTestProtocolsRow, error)
	ListCredentialBlobs(ctx context.Context) ([]ListCredentialBlobsRow, error)
	// All credentials as resolver candidates (the "try everything" default for a
	// scan when the operator selects none). Metadata only — no secret.
	ListCredentialCandidates(ctx context.Context) ([]ListCredentialCandidatesRow, error)
	// The operator-selected credentials for a scan, as resolver candidates.
	ListCredentialCandidatesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCredentialCandidatesByIDsRow, error)
	// Recent test history for one credential (Credential Detail).
	ListCredentialCredentialTests(ctx context.Context, arg ListCredentialCredentialTestsParams) ([]ListCredentialCredentialTestsRow, error)
	// Members of an explicit set of groups (the operator-selected scan groups),
	// returned in the resolver-input shape. priority orders within the explicit
	// tier; the scan injects these above scope-resolved candidates.
	ListCredentialGroupMembers(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCredentialGroupMembersRow, error)
	// Groups with member + binding counts for the scan-time group multi-select.
	ListCredentialGroups(ctx context.Context) ([]ListCredentialGroupsRow, error)
	ListCredentialTestResultsByRun(ctx context.Context, runID uuid.UUID) ([]ListCredentialTestResultsByRunRow, error)
	ListCredentialTestRuns(ctx context.Context, limit int32) ([]CredentialTestRun, error)
	ListCredentials(ctx context.Context) ([]Credential, error)
	ListCredentialsNeedingReentry(ctx context.Context) ([]ListCredentialsNeedingReentryRow, error)
	ListDatastoresByHost(ctx context.Context, hostDeviceID uuid.UUID) ([]VhDatastore, error)
	// One row per (device, protocol, source) describing a REAL way HIMS can manage
	// the device. "Managed access" means an authenticated/working method — a bound
	// credential or proof of a successful authenticated collection — NOT merely an
	// open port. Open-port classification evidence is deliberately excluded here.
	//
	// source values: 'bound_credential' (devices.credential_id) outranks 'evidence'
	// (a child table that only exists because an authenticated collection succeeded).
	// Aggregation/normalisation of protocol tokens happens in Go (access_coverage.go).
	ListDeviceAccessSignals(ctx context.Context) ([]ListDeviceAccessSignalsRow, error)
	// Full recent test history for one device (Device Detail → Credential Health).
	ListDeviceCredentialTests(ctx context.Context, arg ListDeviceCredentialTestsParams) ([]CredentialTestResult, error)
	ListDeviceFacts(ctx context.Context, deviceID uuid.UUID) ([]DeviceFact, error)
	// All topology links touching a device from EITHER endpoint, with both ends
	// enriched (name/ip/vendor/category) and an `inbound` flag set when the device
	// is the link's remote side. The handler normalizes this so the per-device
	// Topology tab always shows the OTHER device — including links that point AT it
	// (e.g. a MAC/FDB-derived cross-vendor uplink stored from the neighbour's side).
	ListDeviceLinksBidirectional(ctx context.Context, localDeviceID uuid.UUID) ([]ListDeviceLinksBidirectionalRow, error)
	ListDeviceRoles(ctx context.Context, deviceID uuid.UUID) ([]DeviceRole, error)
	// ===== Device templates ====================================================
	ListDeviceTemplates(ctx context.Context) ([]DeviceTemplate, error)
	ListDevicesByCategory(ctx context.Context, category string) ([]Device, error)
	ListDevicesByOSFamily(ctx context.Context, osFamily string) ([]Device, error)
	ListDevicesByRole(ctx context.Context, role string) ([]Device, error)
	// Devices with a reachable IP but no monitoring check yet — the seeder turns
	// each into a default TCP check (port chosen by category + os_family).
	ListDevicesNeedingDefaultCheck(ctx context.Context) ([]ListDevicesNeedingDefaultCheckRow, error)
	// Device ids with an in-flight collect_os job (queued or dispatched). Feeds the
	// pending_collection management state so an in-flight host is not misreported as a
	// terminal failure from its stale direct-probe attempt.
	ListDevicesWithActiveAgentJobs(ctx context.Context) ([]*uuid.UUID, error)
	// Credentialed device classes (server/endpoint) that have never been OS-inventoried.
	ListDevicesWithoutOSInventory(ctx context.Context) ([]ListDevicesWithoutOSInventoryRow, error)
	ListDiscoveryJobEvents(ctx context.Context, jobID uuid.UUID) ([]ListDiscoveryJobEventsRow, error)
	ListDiscoveryJobs(ctx context.Context) ([]DiscoveryJob, error)
	ListDiscoveryResults(ctx context.Context, jobID uuid.UUID) ([]DiscoveryResult, error)
	// A check is due when enabled and either never run or its interval elapsed.
	ListDueMonitoringChecks(ctx context.Context) ([]MonitoringCheck, error)
	// Check-status rules only — the check engine matches these against monitoring checks.
	ListEnabledAlertRules(ctx context.Context) ([]AlertRule, error)
	// ---- Monitoring state for evaluation --------------------------------------
	// The evaluator's input: every enabled check joined to its device so rules
	// can filter by category and alerts can carry a readable device name.
	ListEnabledChecksWithDevice(ctx context.Context) ([]ListEnabledChecksWithDeviceRow, error)
	// State-based rules — evaluated by the device-state evaluator (api/alert_state.go), not checks.
	ListEnabledStateRules(ctx context.Context) ([]AlertRule, error)
	ListEnabledWebPortCandidates(ctx context.Context) ([]WebPortCandidate, error)
	// Every interface MAC belonging to a topology-capable fabric device (switch /
	// router / ISP router). Used to map an observed FDB MAC back to the device that
	// owns it, for vendor-neutral L2 link inference (FDB-based topology).
	ListFabricInterfaceMACs(ctx context.Context) ([]ListFabricInterfaceMACsRow, error)
	ListHAMembers(ctx context.Context, deviceID uuid.UUID) ([]FirewallHaMember, error)
	ListHostNicsByHost(ctx context.Context, hostDeviceID uuid.UUID) ([]VhHostNic, error)
	ListInterfaces(ctx context.Context, deviceID uuid.UUID) ([]Interface, error)
	// Per-device scan dispositions across recent jobs (newest first). Powers the
	// scan-stability Data Quality issues: missed-last-scan, flapping (recovered by
	// retry), and frequently-missed-known-device. Bounded so the scan history of a
	// long-lived deployment cannot blow up the query.
	ListKnownDeviceScanDispositions(ctx context.Context) ([]ListKnownDeviceScanDispositionsRow, error)
	ListLicenses(ctx context.Context, deviceID uuid.UUID) ([]FirewallLicense, error)
	// Camera device_ids that are an NVR/DVR channel (recorded by a recorder). These
	// are managed VIA the recorder even when they expose no directly-authenticable
	// web/ONVIF interface (RTSP-only feeds) — so they must not show credential_failed.
	ListLinkedCameraDeviceIDs(ctx context.Context) ([]*uuid.UUID, error)
	// Full flat list for building the location tree client-side.
	ListLocations(ctx context.Context) ([]Location, error)
	ListLookups(ctx context.Context, kind string) ([]Lookup, error)
	ListLowStockParts(ctx context.Context) ([]SparePart, error)
	// ---- Read APIs for the device detail Ports / MAC / ARP tabs --------------
	// The switch FDB with the local port name and, when the MAC belongs to a
	// known device interface, that owner device's name + vendor (real correlation,
	// no OUI guesswork).
	ListMACForDevice(ctx context.Context, deviceID uuid.UUID) ([]ListMACForDeviceRow, error)
	ListMaintenanceWindows(ctx context.Context) ([]MaintenanceWindow, error)
	ListMibFiles(ctx context.Context) ([]MibFile, error)
	ListMibObjects(ctx context.Context, mibFileID uuid.UUID) ([]MibObject, error)
	ListMibPackFiles(ctx context.Context, packID uuid.UUID) ([]ListMibPackFilesRow, error)
	ListMibPackTables(ctx context.Context, packID uuid.UUID) ([]MibPackTable, error)
	ListMibPacks(ctx context.Context) ([]MibPack, error)
	ListMibWalkRows(ctx context.Context, arg ListMibWalkRowsParams) ([]MibWalkRow, error)
	// Global checks list (Health Overview). Joined to the device so the UI can
	// identify each check by device name / IP (not just a bare port), and ordered
	// by device then reachability-first so a device's checks group together.
	ListMonitoringChecks(ctx context.Context) ([]ListMonitoringChecksRow, error)
	ListMonitoringChecksByDevice(ctx context.Context, deviceID uuid.UUID) ([]MonitoringCheck, error)
	ListMonitoringSamplesByCheck(ctx context.Context, arg ListMonitoringSamplesByCheckParams) ([]MonitoringSample, error)
	ListMonitoringSamplesByDevice(ctx context.Context, arg ListMonitoringSamplesByDeviceParams) ([]MonitoringSample, error)
	ListNVRChannels(ctx context.Context, nvrDeviceID uuid.UUID) ([]NvrChannel, error)
	ListNVRStorage(ctx context.Context, nvrDeviceID uuid.UUID) ([]NvrStorage, error)
	ListNeighbors(ctx context.Context, deviceID uuid.UUID) ([]Neighbor, error)
	ListNetworksByHost(ctx context.Context, hostDeviceID uuid.UUID) ([]VhNetwork, error)
	// Alerts worth notifying about: still open or escalated, opened recently.
	ListNotifiableAlerts(ctx context.Context) ([]ListNotifiableAlertsRow, error)
	ListNotificationChannels(ctx context.Context) ([]NotificationChannel, error)
	ListNotificationLog(ctx context.Context) ([]NotificationLog, error)
	ListOIDMappings(ctx context.Context) ([]OidMapping, error)
	// --- disks ---
	ListOSDisks(ctx context.Context, deviceID uuid.UUID) ([]OsDisk, error)
	// --- nics ---
	ListOSNics(ctx context.Context, deviceID uuid.UUID) ([]OsNic, error)
	// --- processes ---
	ListOSProcesses(ctx context.Context, deviceID uuid.UUID) ([]OsProcess, error)
	// --- os roles (free-form, OS-detected) ---
	ListOSRoles(ctx context.Context, deviceID uuid.UUID) ([]OsRole, error)
	// --- services ---
	ListOSServices(ctx context.Context, deviceID uuid.UUID) ([]OsService, error)
	// --- software ---
	ListOSSoftware(ctx context.Context, deviceID uuid.UUID) ([]OsSoftware, error)
	ListOpenStateAlertsByRule(ctx context.Context, ruleID uuid.UUID) ([]ListOpenStateAlertsByRuleRow, error)
	ListPbxPhones(ctx context.Context, deviceID uuid.UUID) ([]PbxPhone, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPortVlans(ctx context.Context, deviceID uuid.UUID) ([]PortVlan, error)
	ListPrinterSupplies(ctx context.Context, deviceID uuid.UUID) ([]PrinterSupply, error)
	ListPurchases(ctx context.Context) ([]Purchase, error)
	// Recent jobs across all agents (fleet-wide failed-job / Data Quality views).
	ListRecentAgentJobsAll(ctx context.Context, limit int32) ([]ListRecentAgentJobsAllRow, error)
	// Fleet activity feed for the Config page: recent captures with device name.
	ListRecentConfigBackups(ctx context.Context, limit int32) ([]ListRecentConfigBackupsRow, error)
	ListRelayAgents(ctx context.Context) ([]RelayAgent, error)
	ListReportSchedules(ctx context.Context) ([]ReportSchedule, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListRootLocations(ctx context.Context) ([]Location, error)
	// The next queued jobs for an agent that are ready to run now (backoff elapsed),
	// capped by $2 = the per-agent dispatch budget (cap - in-flight dispatched). This
	// is what bounds the thundering herd: the server never hands one agent more than
	// the cap of concurrent collect jobs.
	ListRunnableAgentJobs(ctx context.Context, arg ListRunnableAgentJobsParams) ([]AgentJob, error)
	// Bulk fetch of the raw SNMP system-group identity facts across ALL devices, for
	// Data Quality checks that re-evaluate fingerprints against stored evidence
	// without re-probing. Only the identity keys, not the full fact set.
	ListSNMPIdentityFacts(ctx context.Context) ([]ListSNMPIdentityFactsRow, error)
	ListSSHCliResults(ctx context.Context, deviceID uuid.UUID) ([]SshCliResult, error)
	// Devices stranded in a TERMINAL transient collect_os failure that should be
	// automatically re-collected once the storm that caused it has passed. A candidate's
	// latest collect_os job failed with a load-induced transient category, it has no
	// os_inventory evidence (was never successfully collected), no collect_os job is in
	// flight, the failure is older than the cooldown ($1 minutes), and it has not already
	// burned the self-heal round budget ($2 = max failed transient jobs in the last 24h).
	// Auth/authz failures are EXCLUDED (operator must fix the credential) — self-heal
	// never re-sprays a rejected credential or loops forever on a genuinely broken host.
	ListSelfHealCandidates(ctx context.Context, arg ListSelfHealCandidatesParams) ([]ListSelfHealCandidatesRow, error)
	// (channel_id, alert_id) pairs already delivered, so the dispatcher skips them.
	ListSentNotificationPairs(ctx context.Context) ([]ListSentNotificationPairsRow, error)
	ListServerStorage(ctx context.Context, deviceID uuid.UUID) ([]ServerStorage, error)
	ListSettings(ctx context.Context) ([]ListSettingsRow, error)
	ListSpareParts(ctx context.Context) ([]SparePart, error)
	// Credentials assigned to a subnet (for the editor + indicators).
	ListSubnetCredentials(ctx context.Context, subnetID uuid.UUID) ([]ListSubnetCredentialsRow, error)
	ListSubnets(ctx context.Context) ([]Subnet, error)
	ListSubnetsByLocation(ctx context.Context, locationID uuid.UUID) ([]Subnet, error)
	ListSystems(ctx context.Context) ([]System, error)
	ListTopologyLinks(ctx context.Context, localDeviceID uuid.UUID) ([]TopologyLink, error)
	// MACs learned in a switch FDB that map to NO inventory device: not a known device
	// NIC (interfaces/os_nics/vm_nics) AND whose ARP-derived IP (if any) is not an
	// inventory device's primary IP. One row per (mac) — the EDGE port (fewest MACs)
	// where it was seen — with the switch, port, VLAN, last-seen and a possible IP from
	// ARP. No fake devices are created; this is pure visibility into unmapped endpoints.
	ListUnknownMACs(ctx context.Context) ([]ListUnknownMACsRow, error)
	// ===== RBAC: users / roles / permissions ==================================
	ListUsers(ctx context.Context) ([]User, error)
	ListVMDisksByHost(ctx context.Context, hostDeviceID uuid.UUID) ([]VmDisk, error)
	ListVMDisksByVM(ctx context.Context, vmID uuid.UUID) ([]VmDisk, error)
	ListVMNicsByHost(ctx context.Context, hostDeviceID uuid.UUID) ([]VmNic, error)
	ListVMNicsByVM(ctx context.Context, vmID uuid.UUID) ([]VmNic, error)
	ListVMsByHost(ctx context.Context, hostDeviceID uuid.UUID) ([]VirtualMachine, error)
	ListVMsByHostDetail(ctx context.Context, hostDeviceID uuid.UUID) ([]ListVMsByHostDetailRow, error)
	// ===== Vendor fingerprints =================================================
	// Ordered so the matching engine's stable sort favours, among equal-confidence
	// ties: user rules over builtin (source asc: 'builtin'<'user' → invert), then
	// the operator's priority (lower first). Display reads the same order.
	ListVendorFingerprints(ctx context.Context) ([]VendorFingerprint, error)
	ListVendorProfiles(ctx context.Context) ([]VendorConnectionProfile, error)
	ListVlans(ctx context.Context, deviceID uuid.UUID) ([]Vlan, error)
	ListVpnTunnels(ctx context.Context, deviceID uuid.UUID) ([]FirewallVpnTunnel, error)
	ListWebPortCandidates(ctx context.Context) ([]WebPortCandidate, error)
	ListWirelessClients(ctx context.Context, controllerDeviceID uuid.UUID) ([]WirelessClient, error)
	ListWirelessEvents(ctx context.Context, arg ListWirelessEventsParams) ([]WirelessEvent, error)
	ListWirelessRadios(ctx context.Context, controllerDeviceID uuid.UUID) ([]WirelessRadioStatus, error)
	ListWirelessSSIDs(ctx context.Context, controllerDeviceID uuid.UUID) ([]WirelessSsid, error)
	ListWorkOrderEvents(ctx context.Context, workOrderID uuid.UUID) ([]WorkOrderEvent, error)
	ListWorkOrderParts(ctx context.Context, workOrderID uuid.UUID) ([]WorkOrderPart, error)
	ListWorkOrders(ctx context.Context) ([]WorkOrder, error)
	ListWorkOrdersByDevice(ctx context.Context, deviceID *uuid.UUID) ([]WorkOrder, error)
	// Enriched list for the Work Orders page: joins the linked device name.
	ListWorkOrdersWithDevice(ctx context.Context) ([]ListWorkOrdersWithDeviceRow, error)
	// Reconcile key for an UNSCOPED scan (no site selected): match by primary_ip
	// alone so a re-scan updates the existing device regardless of an
	// operator-assigned location_id, instead of duplicating it. Most-recent wins.
	LiveDeviceByIP(ctx context.Context, primaryIp *netip.Addr) (Device, error)
	// Identity reconciliation key (multi-hotel safe): same IP can recur across
	// hotels, so a live device is unique by (primary_ip, location). location_id is
	// matched NULL-safe (IS NOT DISTINCT FROM) so an unscoped scan (no site
	// selected, location_id = NULL) still reconciles instead of duplicating.
	LiveDeviceByIPAndLocation(ctx context.Context, arg LiveDeviceByIPAndLocationParams) (Device, error)
	MACCountByPort(ctx context.Context, deviceID uuid.UUID) ([]MACCountByPortRow, error)
	MarkAgentJobDispatched(ctx context.Context, id uuid.UUID) error
	// Flag (or unflag) a device as a manually-entered virtual placeholder.
	MarkDeviceVirtual(ctx context.Context, arg MarkDeviceVirtualParams) error
	// Freshness of the most recent LLDP/CDP neighbor observation (topology age).
	MaxNeighborSeenAt(ctx context.Context) (time.Time, error)
	// Fleet health rollup, DEVICE-based: how many MONITORED devices sit in each
	// reachability bucket. We count devices (not checks) and map the device's
	// rolled-up status onto the up/down/warning/unknown vocabulary, so the KPI
	// counts match the inventory reachability filter exactly (a click lands on the
	// same devices). A failing SUPPLEMENTAL check surfaces here as "warning" (the
	// rollup degrades the device to warning, never down) — it lowers the health
	// score and is clickable, but never inflates the "down"/offline bucket. A device
	// is "monitored" when it has at least one enabled check.
	MonitoringStatusOverview(ctx context.Context) ([]MonitoringStatusOverviewRow, error)
	// Path Finder: per-NVR channel totals (and how many are linked to a camera device).
	NVRChannelStats(ctx context.Context, nvrDeviceID uuid.UUID) (NVRChannelStatsRow, error)
	NetworkCountByHost(ctx context.Context) ([]NetworkCountByHostRow, error)
	// ---- Alerts ---------------------------------------------------------------
	// Atomic open: ON CONFLICT against idx_alerts_one_open means a second open
	// for the same (rule, check) is a no-op. RETURNING yields a row ONLY on a
	// real insert, so the engine fires the work-order bridge exactly once.
	OpenAlert(ctx context.Context, arg OpenAlertParams) (Alert, error)
	// Open (unresolved) alert counts per device, for site rollups.
	OpenAlertCountsByDevice(ctx context.Context) ([]OpenAlertCountsByDeviceRow, error)
	// ---- State-based alerts (no check_id; dedup on rule_id + fingerprint) ------
	// Opens a state alert. The evaluator checks existence first (single-threaded sweep), and the
	// partial unique index (rule_id, fingerprint) WHERE check_id IS NULL is the race backstop.
	OpenStateAlert(ctx context.Context, arg OpenStateAlertParams) (Alert, error)
	PermissionsForRole(ctx context.Context, roleID uuid.UUID) ([]Permission, error)
	// All permission codes a user holds via any of their roles.
	PermissionsForUser(ctx context.Context, userID uuid.UUID) ([]string, error)
	// Link every NVR/DVR channel to the live device at its camera_ip, so a channel
	// and the standalone camera device cross-reference regardless of the order they
	// were discovered/collected. The per-channel link is computed once at NVR-collect
	// time (persistNVR via LiveDeviceByIP), so a camera discovered AFTER its NVR was
	// collected — or one whose apply raced the NVR collect — would otherwise stay
	// unlinked forever. Idempotent + set-based: exact primary_ip match, never links a
	// channel to its own NVR, picks the most-recently-updated device when an IP
	// recurs. Device deletes clear links via the FK (ON DELETE SET NULL), so this
	// only ADDS/repoints. Returns the number of channels (re)linked.
	ReconcileNVRChannelLinks(ctx context.Context) (int64, error)
	// Persist the rollup the engine computed (status + failure counter) onto the
	// check after a poll. History rows go to monitoring_samples separately.
	RecordMonitoringResult(ctx context.Context, arg RecordMonitoringResultParams) (MonitoringCheck, error)
	RecordReportScheduleRun(ctx context.Context, arg RecordReportScheduleRunParams) error
	// Bump version + stamp the rotation; sets the new key's fingerprint.
	RecordRotation(ctx context.Context, arg RecordRotationParams) error
	// Refresh shipped catalog metadata onto an EXISTING built-in row so newer
	// built-in knowledge (notably exclusions added after the row was first seeded)
	// reaches the live DB the classifier reads. The `source='builtin'` guard makes
	// this structurally unable to clobber an operator-created rule — even a user rule
	// that happens to share (kind,pattern). Operator knobs (enabled, priority) are
	// preserved; only descriptive metadata + exclusions are refreshed. Row id is kept.
	RefreshBuiltinVendorFingerprint(ctx context.Context, arg RefreshBuiltinVendorFingerprintParams) (int64, error)
	RelayAgentHeartbeat(ctx context.Context, arg RelayAgentHeartbeatParams) error
	// Return a transiently-failed job to the queue with an incremented attempt and a
	// backoff deadline ($2). Clears dispatched_at so it can be re-dispatched once the
	// backoff elapses. Used for retryable (non-auth) collection failures.
	RequeueAgentJob(ctx context.Context, arg RequeueAgentJobParams) error
	// Recover jobs stuck 'dispatched' whose agent never reported back (agent crash /
	// dropped connection): requeue (bumped attempt) if attempts remain, else mark
	// failed so they never block re-enqueue forever. $1 = dispatched-before cutoff.
	RequeueStaleAgentJobs(ctx context.Context, dispatchedAt *time.Time) (int64, error)
	ResolveAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	ResolveAlertByID(ctx context.Context, id uuid.UUID) (Alert, error)
	// The resolver-assembly query: for a device IP, return every credential in a
	// group bound to either a subnet that contains the IP (more specific) or a
	// location anchor, with the binding specificity + member priority so the
	// pure resolver (internal/credresolver) can order them.
	//   specificity 2 = subnet binding, 1 = location binding.
	ResolveCandidatesForIP(ctx context.Context, arg ResolveCandidatesForIPParams) ([]ResolveCandidatesForIPRow, error)
	// Path Finder fallback for when the ARP table is empty/sparse: resolve an IP to a
	// MAC (and an identity) from the wireless-client roster and the AP inventory, so a
	// wireless endpoint's IP still traces to its switch port via the FDB. Clients are
	// preferred over APs ($1 = IP as text).
	ResolveIPToMAC(ctx context.Context, ip string) ([]ResolveIPToMACRow, error)
	// Per FDB entry on a switch, resolve the learned MAC to an inventory device (by switch-interface
	// MAC, by OS NIC, or by ARP-derived IP), to a VM (by vNIC MAC), and to an IP (latest ARP). Each
	// candidate is returned separately and NULLable; the API coalesces with a priority + confidence.
	// No fake devices: a NULL device_id means the MAC is unmapped.
	ResolvePortMap(ctx context.Context, deviceID uuid.UUID) ([]ResolvePortMapRow, error)
	// Auto-resolve: any un-resolved alert whose check has recovered to 'up'.
	ResolveRecoveredAlerts(ctx context.Context) ([]ResolveRecoveredAlertsRow, error)
	// The newest enabled, recently-online agent assigned to a location — used to
	// prefer agent collection for devices in that site.
	ResolveSiteAgent(ctx context.Context, locationID *uuid.UUID) (RelayAgent, error)
	// Profiles applicable to a device during a scan: a profile bound to this exact
	// device, or one bound to this location (site-level), or an unbound global
	// profile — for the given vendor_type. Most specific first.
	ResolveVendorProfiles(ctx context.Context, arg ResolveVendorProfilesParams) ([]VendorConnectionProfile, error)
	// Fleet-wide role rollup: how many devices hold each role (the CMDB role cut).
	RoleSummary(ctx context.Context) ([]RoleSummaryRow, error)
	RolesForUser(ctx context.Context, userID uuid.UUID) ([]Role, error)
	// Global-search: access points by name / MAC / IP / serial / model. Returns the
	// owning controller so an AP MAC or IP found anywhere resolves to a device.
	SearchAccessPoints(ctx context.Context, dollar_1 *string) ([]SearchAccessPointsRow, error)
	// Global-search: ARP table (IP↔MAC) by IP or MAC — which L3 device resolved an IP.
	SearchArpEntries(ctx context.Context, dollar_1 *string) ([]SearchArpEntriesRow, error)
	SearchByHostname(ctx context.Context, hostname *string) ([]SearchByHostnameRow, error)
	// Primary search entry point for the IP → MAC → port path resolution.
	SearchByIP(ctx context.Context, primaryIp *netip.Addr) (SearchByIPRow, error)
	// Finds the switch(es) that have this MAC in their FDB, then joins the
	// interface for port + VLAN detail.
	SearchByMAC(ctx context.Context, mac string) ([]SearchByMACRow, error)
	// Global-search: learned MAC addresses (bridge FDB) by MAC — which switch + port
	// a MAC was seen on, anywhere in the fabric.
	SearchFdbMacs(ctx context.Context, dollar_1 *string) ([]SearchFdbMacsRow, error)
	SearchMibObjects(ctx context.Context, name string) ([]MibObject, error)
	// Global-search: NVR/DVR camera channels by channel name / camera IP / channel
	// number / recorder (NVR) name. Returns the owning recorder so a channel found
	// anywhere links back to the NVR detail page, plus any linked standalone camera
	// device. Channels are recorder-owned rows, not separate inventory devices.
	SearchNVRChannels(ctx context.Context, dollar_1 *string) ([]SearchNVRChannelsRow, error)
	// Global search: IP phones / PBX subscribers by extension / SEP name / MAC / IP.
	// Deduped across the CUCM pub/sub pair (the same phone appears under each node).
	SearchPhones(ctx context.Context, dollar_1 *string) ([]SearchPhonesRow, error)
	// Global-search: associated wireless clients by MAC / IP / hostname / SSID / AP.
	SearchWirelessClients(ctx context.Context, dollar_1 *string) ([]SearchWirelessClientsRow, error)
	SetAlertRuleEnabled(ctx context.Context, arg SetAlertRuleEnabledParams) (AlertRule, error)
	SetAlertWorkOrder(ctx context.Context, arg SetAlertWorkOrderParams) error
	// Operator manual override: lock (true) freezes auto-classification for this
	// device; unlock (false) lets the next discovery re-classify it.
	SetClassificationLock(ctx context.Context, arg SetClassificationLockParams) (Device, error)
	// Bind the WEB credential that last authenticated for CCTV (ONVIF/ISAPI)
	// collection. Kept separate from credential_id so an SNMP discovery/monitor
	// success can never overwrite the credential CCTV collection depends on.
	SetDeviceCCTVCredential(ctx context.Context, arg SetDeviceCCTVCredentialParams) error
	// Bind-on-success: record the credential that last authenticated.
	SetDeviceCredential(ctx context.Context, arg SetDeviceCredentialParams) error
	// Operator-set per-device web-access override: preferred scheme/port, alternate
	// ports (comma-separated), preferred protocol, and a free-text note. Collectors
	// try these first.
	SetDeviceWebOverride(ctx context.Context, arg SetDeviceWebOverrideParams) error
	// Record EXACTLY what worked on the last successful web/CCTV collection: the
	// protocol (isapi/onvif/http/…), scheme, port, base endpoint, and the credential
	// that authenticated. Drives the accurate "Managed via X" source in the UI and
	// lets the next collect/scan prefer the known-good endpoint instead of guessing.
	SetDeviceWebSuccess(ctx context.Context, arg SetDeviceWebSuccessParams) error
	// Stores the scan spec (mode/targets/creds) so the job can be re-run as-is.
	SetDiscoveryJobMetadata(ctx context.Context, arg SetDiscoveryJobMetadataParams) error
	SetMibPackCollected(ctx context.Context, arg SetMibPackCollectedParams) error
	SetMibPackEnabled(ctx context.Context, arg SetMibPackEnabledParams) error
	SetMibPackParseMeta(ctx context.Context, arg SetMibPackParseMetaParams) error
	SetMibPackTested(ctx context.Context, arg SetMibPackTestedParams) error
	SetMonitoringCheckEnabled(ctx context.Context, arg SetMonitoringCheckEnabledParams) (MonitoringCheck, error)
	// Mark a check as reachability (drives device status) or supplemental (extra,
	// informational only). Used when an operator adds a check beyond the default.
	SetMonitoringCheckRole(ctx context.Context, arg SetMonitoringCheckRoleParams) error
	SetNotificationChannelEnabled(ctx context.Context, arg SetNotificationChannelEnabledParams) (NotificationChannel, error)
	SetRelayAgentEnabled(ctx context.Context, arg SetRelayAgentEnabledParams) error
	SetRelayAgentLocation(ctx context.Context, arg SetRelayAgentLocationParams) error
	// Rotate an agent's enrollment token (only the new hash is stored). The previous
	// token stops working immediately; the operator re-downloads a fresh installer.
	SetRelayAgentToken(ctx context.Context, arg SetRelayAgentTokenParams) error
	SetReportScheduleEnabled(ctx context.Context, arg SetReportScheduleEnabledParams) (ReportSchedule, error)
	SetRolePermissionsClear(ctx context.Context, roleID uuid.UUID) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SetUserRolesClear(ctx context.Context, userID uuid.UUID) error
	// Platform-specific extra VM attributes; COALESCE(NULLIF...) so a collector that doesn't
	// supply a field (e.g. vSphere has no generation) never wipes another platform's value.
	SetVMExtra(ctx context.Context, arg SetVMExtraParams) error
	SetVendorProfileCollection(ctx context.Context, arg SetVendorProfileCollectionParams) error
	SetVendorProfileTest(ctx context.Context, arg SetVendorProfileTestParams) error
	// Per-subnet assignment count + distinct kinds for a location (UI row badges).
	SubnetCredentialCounts(ctx context.Context, locationID uuid.UUID) ([]SubnetCredentialCountsRow, error)
	// The EXCLUSIVE credential set for the most-specific site subnet that (a) contains
	// the IP and (b) has assignments. Empty result ⇒ no subnet scoping ⇒ caller falls
	// back to normal resolution.
	//
	// location_id is a PREFERENCE, NOT a hard filter. The anti-spray/lockout-safety
	// contract is "any IP inside an assigned subnet is tried with ONLY that subnet's
	// credentials" — independent of which site the operator happened to select for the
	// scan. Gating the match on an exact location_id match silently disengaged that
	// protection whenever the scan carried a location other than the subnet's own
	// (e.g. a child/parent/sibling node, or a different hotel), falling back to
	// spraying every stored credential. So we match on the CIDR alone and only use the
	// scan's location to break ties between overlapping subnets at different sites:
	// a subnet at the scan's location outranks one elsewhere, then narrower mask wins.
	SubnetScopedCredentialsForIP(ctx context.Context, arg SubnetScopedCredentialsForIPParams) ([]SubnetScopedCredentialsForIPRow, error)
	// Roll up aggregate rows of one kind over a recent window, highest bytes first.
	TopFlowEntries(ctx context.Context, arg TopFlowEntriesParams) ([]TopFlowEntriesRow, error)
	TotalExpenses(ctx context.Context) (float64, error)
	TouchDeviceDiscovery(ctx context.Context, arg TouchDeviceDiscoveryParams) error
	TouchSession(ctx context.Context, tokenHash string) error
	TouchValidation(ctx context.Context) error
	// Rename + weak-flag update (Credentials CRUD edit).
	UpdateCredentialMeta(ctx context.Context, arg UpdateCredentialMetaParams) (Credential, error)
	// Used by key rotation: re-seal the secret under a new key + KeyID.
	UpdateCredentialSecret(ctx context.Context, arg UpdateCredentialSecretParams) error
	// Operator edit of a device's identity + management attributes (Edit Device).
	// classification_locked, when set, also protects identity (category/vendor/model/
	// serial) from being overwritten by future discovery scans (see the reconcile
	// path UpdateDiscoveredDeviceRespectingLock).
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
	// Auto-classification write: set category + OS family + subtype + confidence +
	// evidence trail in one shot. The `classification_locked = false` guard makes
	// this an atomic no-op on operator-overridden devices (0 rows affected →
	// pgx.ErrNoRows), so a manual classification is never silently overwritten.
	UpdateDeviceClassification(ctx context.Context, arg UpdateDeviceClassificationParams) (Device, error)
	// Fill the device's identity/hardware fields from an authenticated deep-OS
	// collection (manufacturer/model/serial/OS caption/hostname). COALESCE(NULLIF…)
	// means a blank incoming value never wipes an existing one — collection only
	// ENRICHES the row, so the Inventory list columns (Vendor/Model/OS) populate
	// without clobbering anything a prior SNMP probe or operator edit set.
	UpdateDeviceHardwareInfo(ctx context.Context, arg UpdateDeviceHardwareInfoParams) error
	// Reflect the worst current check status onto the device row so device lists
	// show a live health badge without a per-row sample query.
	UpdateDeviceMonitoringStatus(ctx context.Context, arg UpdateDeviceMonitoringStatusParams) error
	UpdateDeviceTemplate(ctx context.Context, arg UpdateDeviceTemplateParams) (DeviceTemplate, error)
	// Reconcile path: refresh a live device's mutable identity fields on
	// re-discovery (keyed by the caller to the (primary_ip, location) match).
	// location_id is FILLED when the device has none (a site-scoped scan adopts a
	// previously site-less device — e.g. first found by an unscoped CIDR scan, later
	// re-scanned under a site) but never OVERWRITES an operator-set location:
	// COALESCE keeps any existing value. A NULL fill arg (site-less scan) is a no-op.
	UpdateDiscoveredDevice(ctx context.Context, arg UpdateDiscoveredDeviceParams) (Device, error)
	UpdateDiscoveryJobStatus(ctx context.Context, arg UpdateDiscoveryJobStatusParams) error
	UpdateDiscoveryResult(ctx context.Context, arg UpdateDiscoveryResultParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateMibPack(ctx context.Context, arg UpdateMibPackParams) (MibPack, error)
	UpdateRelayAgentIdentity(ctx context.Context, arg UpdateRelayAgentIdentityParams) error
	UpdateSparePart(ctx context.Context, arg UpdateSparePartParams) (SparePart, error)
	UpdateSystem(ctx context.Context, arg UpdateSystemParams) (System, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVendorFingerprint(ctx context.Context, arg UpdateVendorFingerprintParams) (VendorFingerprint, error)
	UpdateVendorProfile(ctx context.Context, arg UpdateVendorProfileParams) (VendorConnectionProfile, error)
	UpdateWebPortCandidate(ctx context.Context, arg UpdateWebPortCandidateParams) (WebPortCandidate, error)
	UpdateWorkOrder(ctx context.Context, arg UpdateWorkOrderParams) (WorkOrder, error)
	// ---- ARP entries ---------------------------------------------------------
	UpsertARP(ctx context.Context, arg UpsertARPParams) error
	UpsertAccessPoint(ctx context.Context, arg UpsertAccessPointParams) (AccessPoint, error)
	UpsertBMCInfo(ctx context.Context, arg UpsertBMCInfoParams) error
	UpsertBMCSensor(ctx context.Context, arg UpsertBMCSensorParams) error
	// Enriched read-only camera facts from ISAPI (NIC + time + firmware/serial).
	// COALESCE keeps an existing value when a re-collect doesn't re-resolve a field.
	UpsertCameraEnrichment(ctx context.Context, arg UpsertCameraEnrichmentParams) error
	UpsertCameraInfo(ctx context.Context, arg UpsertCameraInfoParams) (CameraInfo, error)
	UpsertCollectionHealth(ctx context.Context, arg UpsertCollectionHealthParams) error
	// ===== Stage 2: rich virtualization detail (durable tables) =====
	UpsertDatastore(ctx context.Context, arg UpsertDatastoreParams) error
	UpsertDeviceFact(ctx context.Context, arg UpsertDeviceFactParams) error
	UpsertDeviceLifecycle(ctx context.Context, arg UpsertDeviceLifecycleParams) (DeviceLifecycle, error)
	// Adopt / record the current key's fingerprint (generate + first-run adopt).
	UpsertEncryptionMetadata(ctx context.Context, arg UpsertEncryptionMetadataParams) error
	UpsertFirewallStatus(ctx context.Context, arg UpsertFirewallStatusParams) error
	UpsertHAMember(ctx context.Context, arg UpsertHAMemberParams) error
	UpsertHostNic(ctx context.Context, arg UpsertHostNicParams) error
	// ---- Interfaces -----------------------------------------------------------
	UpsertInterface(ctx context.Context, arg UpsertInterfaceParams) (Interface, error)
	UpsertLicense(ctx context.Context, arg UpsertLicenseParams) error
	// ---- MAC address table ---------------------------------------------------
	UpsertMAC(ctx context.Context, arg UpsertMACParams) error
	// ===== Pack tables (mappings) =====
	UpsertMibPackTable(ctx context.Context, arg UpsertMibPackTableParams) (MibPackTable, error)
	// Idempotent registration: re-registering the same (device, kind, port)
	// updates the schedule knobs without resetting the live status counters.
	UpsertMonitoringCheck(ctx context.Context, arg UpsertMonitoringCheckParams) (MonitoringCheck, error)
	UpsertNVRChannel(ctx context.Context, arg UpsertNVRChannelParams) (NvrChannel, error)
	UpsertNVRInfo(ctx context.Context, arg UpsertNVRInfoParams) (NvrInfo, error)
	UpsertNVRStorage(ctx context.Context, arg UpsertNVRStorageParams) (NvrStorage, error)
	// ---- Neighbors (LLDP/CDP) -----------------------------------------------
	UpsertNeighbor(ctx context.Context, arg UpsertNeighborParams) (Neighbor, error)
	UpsertOSDisk(ctx context.Context, arg UpsertOSDiskParams) error
	UpsertOSInventory(ctx context.Context, arg UpsertOSInventoryParams) (OsInventory, error)
	UpsertOSNic(ctx context.Context, arg UpsertOSNicParams) error
	UpsertOSProcess(ctx context.Context, arg UpsertOSProcessParams) error
	UpsertOSRole(ctx context.Context, arg UpsertOSRoleParams) error
	UpsertOSService(ctx context.Context, arg UpsertOSServiceParams) error
	UpsertOSSoftware(ctx context.Context, arg UpsertOSSoftwareParams) error
	UpsertPbxPhone(ctx context.Context, arg UpsertPbxPhoneParams) error
	UpsertPortVlan(ctx context.Context, arg UpsertPortVlanParams) error
	UpsertPrinterSupply(ctx context.Context, arg UpsertPrinterSupplyParams) error
	UpsertSSHCliResult(ctx context.Context, arg UpsertSSHCliResultParams) error
	UpsertServerStorage(ctx context.Context, arg UpsertServerStorageParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertSnooze(ctx context.Context, arg UpsertSnoozeParams) error
	// ---- Topology links ------------------------------------------------------
	UpsertTopologyLink(ctx context.Context, arg UpsertTopologyLinkParams) error
	UpsertUPSStatus(ctx context.Context, arg UpsertUPSStatusParams) error
	UpsertVHNetwork(ctx context.Context, arg UpsertVHNetworkParams) error
	// Upsert keyed on (host, name): re-collecting refreshes state without dups. COALESCE on
	// vm_id/mac so a later collection that lacks them (e.g. vSphere) never wipes Hyper-V values.
	UpsertVM(ctx context.Context, arg UpsertVMParams) (VirtualMachine, error)
	UpsertVMDisk(ctx context.Context, arg UpsertVMDiskParams) error
	UpsertVMNic(ctx context.Context, arg UpsertVMNicParams) error
	// Import path: idempotent by (kind, pattern). Re-importing updates the existing
	// rule's vendor/type/confidence/model/priority/source/exclusions rather than duplicating it.
	UpsertVendorFingerprint(ctx context.Context, arg UpsertVendorFingerprintParams) (VendorFingerprint, error)
	// ---- VLANs ----------------------------------------------------------------
	UpsertVlan(ctx context.Context, arg UpsertVlanParams) (Vlan, error)
	UpsertVpnTunnel(ctx context.Context, arg UpsertVpnTunnelParams) error
	UpsertWLANControllerInfo(ctx context.Context, arg UpsertWLANControllerInfoParams) (WlanControllerInfo, error)
	UpsertWirelessClient(ctx context.Context, arg UpsertWirelessClientParams) (WirelessClient, error)
	UpsertWirelessControllerSummary(ctx context.Context, arg UpsertWirelessControllerSummaryParams) error
	UpsertWirelessRadio(ctx context.Context, arg UpsertWirelessRadioParams) (WirelessRadioStatus, error)
	UpsertWirelessSSID(ctx context.Context, arg UpsertWirelessSSIDParams) (WirelessSsid, error)
	VMCountsByHost(ctx context.Context) ([]VMCountsByHostRow, error)
	VMLinkSummary(ctx context.Context) (VMLinkSummaryRow, error)
}

var _ Querier = (*Queries)(nil)
