// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

type Querier interface {
	AcknowledgeAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	AddCredentialGroupMember(ctx context.Context, arg AddCredentialGroupMemberParams) error
	AddDeviceRole(ctx context.Context, arg AddDeviceRoleParams) error
	// A part not tracked in stock (free-text): just record it, no decrement.
	AddFreeWorkOrderPart(ctx context.Context, arg AddFreeWorkOrderPartParams) (WorkOrderPart, error)
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	AddWorkOrderEvent(ctx context.Context, arg AddWorkOrderEventParams) (WorkOrderEvent, error)
	// Absolute set of on-hand quantity (a stock count / receiving correction).
	// The CHECK (quantity >= 0) constraint rejects negative results.
	AdjustSparePartStock(ctx context.Context, arg AdjustSparePartStockParams) (SparePart, error)
	BindCredentialGroup(ctx context.Context, arg BindCredentialGroupParams) (CredentialBinding, error)
	// Assign vlan/device_class/location to many devices at once (multi-select).
	// Only the provided (non-null) fields are changed — COALESCE keeps the rest —
	// so an operator can set just location, just class, just vlan, or any combo.
	BulkAssignClassification(ctx context.Context, arg BulkAssignClassificationParams) (int64, error)
	// Lost-key recovery: wipe only the secret fields; preserve the record,
	// metadata, assignments and group memberships. Flag for re-entry.
	ClearAllCredentialSecrets(ctx context.Context) error
	ClearReentryFlag(ctx context.Context, id uuid.UUID) error
	// ---- Work-order parts (stock consumption) ---------------------------------
	// Atomic: decrement stock AND record the consumption in ONE statement. The
	// UPDATE's WHERE quantity >= $3 is the precondition; if it fails to match,
	// the CTE yields no row, the INSERT inserts nothing, and :one returns
	// ErrNoRows — which the handler maps to "insufficient stock" (409). This is
	// the atomic-DB-signal pattern: no SELECT-then-UPDATE TOCTOU window.
	ConsumePartToWorkOrder(ctx context.Context, arg ConsumePartToWorkOrderParams) (WorkOrderPart, error)
	CountCredentialsNeedingReentry(ctx context.Context) (int64, error)
	CountDevicesNeedingAttention(ctx context.Context) (int64, error)
	// ===== Credential secret accounting / recovery =============================
	CountEncryptedCredentials(ctx context.Context) (int64, error)
	// Systems whose license OR support expires within 90 days (or already has).
	CountExpiringSystems(ctx context.Context) (int64, error)
	CountOpenAlerts(ctx context.Context) (int64, error)
	CountOpenWorkOrders(ctx context.Context) (int64, error)
	// Blobs sealed under a key id other than the one currently loaded.
	CountUndecryptableCredentials(ctx context.Context, keyID string) (int64, error)
	// ---- Alert rules ----------------------------------------------------------
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	CreateCredentialGroup(ctx context.Context, arg CreateCredentialGroupParams) (CredentialGroup, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateDeviceTemplate(ctx context.Context, arg CreateDeviceTemplateParams) (DeviceTemplate, error)
	CreateDiscoveryJob(ctx context.Context, arg CreateDiscoveryJobParams) (DiscoveryJob, error)
	CreateDiscoveryResult(ctx context.Context, arg CreateDiscoveryResultParams) (DiscoveryResult, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateLookup(ctx context.Context, arg CreateLookupParams) (Lookup, error)
	CreateMibFile(ctx context.Context, arg CreateMibFileParams) (MibFile, error)
	CreateOIDMapping(ctx context.Context, arg CreateOIDMappingParams) (OidMapping, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	// ---- Purchases ------------------------------------------------------------
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// ---- Spare parts ----------------------------------------------------------
	CreateSparePart(ctx context.Context, arg CreateSparePartParams) (SparePart, error)
	CreateSubnet(ctx context.Context, arg CreateSubnetParams) (Subnet, error)
	CreateSystem(ctx context.Context, arg CreateSystemParams) (System, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVendorFingerprint(ctx context.Context, arg CreateVendorFingerprintParams) (VendorFingerprint, error)
	CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error)
	DeleteAlertRule(ctx context.Context, id uuid.UUID) error
	// Removing a credential un-binds it from devices (FK ON DELETE SET NULL) and
	// drops its group memberships (FK ON DELETE CASCADE).
	DeleteCredential(ctx context.Context, id uuid.UUID) error
	// Hard delete (cascades to inventory child rows via FK ON DELETE CASCADE).
	DeleteDevice(ctx context.Context, id uuid.UUID) error
	DeleteDeviceTemplate(ctx context.Context, id uuid.UUID) error
	// Bulk hard delete (multi-select). Returns the number of rows removed.
	DeleteDevices(ctx context.Context, dollar_1 []uuid.UUID) (int64, error)
	// Removes a job and its results (discovery_results FK ON DELETE CASCADE).
	DeleteDiscoveryJob(ctx context.Context, id uuid.UUID) error
	DeleteLocation(ctx context.Context, id uuid.UUID) error
	DeleteLookup(ctx context.Context, id uuid.UUID) error
	DeleteMonitoringCheck(ctx context.Context, id uuid.UUID) error
	DeleteOIDMapping(ctx context.Context, id uuid.UUID) error
	DeletePermission(ctx context.Context, id uuid.UUID) error
	DeletePurchase(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, id uuid.UUID) error
	DeleteSparePart(ctx context.Context, id uuid.UUID) error
	DeleteStaleARP(ctx context.Context, arg DeleteStaleARPParams) error
	DeleteStaleBMCSensors(ctx context.Context, arg DeleteStaleBMCSensorsParams) error
	DeleteStaleHAMembers(ctx context.Context, arg DeleteStaleHAMembersParams) error
	DeleteStaleInterfaces(ctx context.Context, arg DeleteStaleInterfacesParams) error
	DeleteStaleLicenses(ctx context.Context, arg DeleteStaleLicensesParams) error
	DeleteStaleMACEntries(ctx context.Context, arg DeleteStaleMACEntriesParams) error
	DeleteStaleNeighbors(ctx context.Context, arg DeleteStaleNeighborsParams) error
	DeleteStalePbxPhones(ctx context.Context, arg DeleteStalePbxPhonesParams) error
	DeleteStalePortVlans(ctx context.Context, arg DeleteStalePortVlansParams) error
	DeleteStalePrinterSupplies(ctx context.Context, arg DeleteStalePrinterSuppliesParams) error
	DeleteStaleServerStorage(ctx context.Context, arg DeleteStaleServerStorageParams) error
	DeleteStaleVlans(ctx context.Context, arg DeleteStaleVlansParams) error
	DeleteStaleVpnTunnels(ctx context.Context, arg DeleteStaleVpnTunnelsParams) error
	DeleteSubnet(ctx context.Context, id uuid.UUID) error
	DeleteSystem(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteVendorFingerprint(ctx context.Context, id uuid.UUID) error
	DeviceCountByCategory(ctx context.Context) ([]DeviceCountByCategoryRow, error)
	DeviceCountByStatus(ctx context.Context) ([]DeviceCountByStatusRow, error)
	// ---- Expenses (aggregation over the purchases ledger) ---------------------
	// Expenses derive from the purchases ledger so the totals can never drift
	// from their source rows. Work-order cost + system cost stay on their own
	// pages (not merged here, to avoid double-counting a purchase logged for the
	// same repair/license).
	ExpensesByCategory(ctx context.Context) ([]ExpensesByCategoryRow, error)
	ExpensesByLocation(ctx context.Context) ([]ExpensesByLocationRow, error)
	// First step of the IP→MAC→port→path search.
	FindMACByIP(ctx context.Context, ipAddress netip.Addr) ([]FindMACByIPRow, error)
	// Topology search: which switch + port + VLAN carries a MAC?
	FindMACOnSwitches(ctx context.Context, mac string) ([]FindMACOnSwitchesRow, error)
	GetBMCInfo(ctx context.Context, deviceID uuid.UUID) (BmcInfo, error)
	GetCameraInfo(ctx context.Context, deviceID uuid.UUID) (CameraInfo, error)
	GetCredential(ctx context.Context, id uuid.UUID) (Credential, error)
	GetDevice(ctx context.Context, id uuid.UUID) (Device, error)
	GetDiscoveryJob(ctx context.Context, id uuid.UUID) (DiscoveryJob, error)
	// ===== Encryption key lifecycle (metadata only — never the key) ===========
	GetEncryptionMetadata(ctx context.Context) (EncryptionMetadatum, error)
	GetFirewallStatus(ctx context.Context, deviceID uuid.UUID) (FirewallStatus, error)
	GetLocation(ctx context.Context, id uuid.UUID) (Location, error)
	GetMonitoringCheck(ctx context.Context, id uuid.UUID) (MonitoringCheck, error)
	GetSparePart(ctx context.Context, id uuid.UUID) (SparePart, error)
	GetSystem(ctx context.Context, id uuid.UUID) (System, error)
	GetUPSStatus(ctx context.Context, deviceID uuid.UUID) (UpsStatus, error)
	GetWLANControllerInfo(ctx context.Context, deviceID uuid.UUID) (WlanControllerInfo, error)
	GetWorkOrder(ctx context.Context, id uuid.UUID) (WorkOrder, error)
	// ===== Audit log ===========================================================
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertMibObject(ctx context.Context, arg InsertMibObjectParams) error
	InsertMonitoringSample(ctx context.Context, arg InsertMonitoringSampleParams) error
	ListARPForDevice(ctx context.Context, deviceID uuid.UUID) ([]ListARPForDeviceRow, error)
	ListAccessPoints(ctx context.Context, controllerDeviceID uuid.UUID) ([]AccessPoint, error)
	ListAlertRules(ctx context.Context) ([]AlertRule, error)
	ListAlerts(ctx context.Context) ([]Alert, error)
	// Every live device (the Inventory page), ordered for grouped display.
	ListAllDevices(ctx context.Context) ([]Device, error)
	// Used by the topology graph to build the full picture.
	ListAllTopologyLinks(ctx context.Context) ([]ListAllTopologyLinksRow, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	ListBMCSensors(ctx context.Context, deviceID uuid.UUID) ([]BmcSensor, error)
	ListChildLocations(ctx context.Context, parentID *uuid.UUID) ([]Location, error)
	ListCredentialBlobs(ctx context.Context) ([]ListCredentialBlobsRow, error)
	// All credentials as resolver candidates (the "try everything" default for a
	// scan when the operator selects none). Metadata only — no secret.
	ListCredentialCandidates(ctx context.Context) ([]ListCredentialCandidatesRow, error)
	// The operator-selected credentials for a scan, as resolver candidates.
	ListCredentialCandidatesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCredentialCandidatesByIDsRow, error)
	// Members of an explicit set of groups (the operator-selected scan groups),
	// returned in the resolver-input shape. priority orders within the explicit
	// tier; the scan injects these above scope-resolved candidates.
	ListCredentialGroupMembers(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCredentialGroupMembersRow, error)
	// Groups with member + binding counts for the scan-time group multi-select.
	ListCredentialGroups(ctx context.Context) ([]ListCredentialGroupsRow, error)
	ListCredentials(ctx context.Context) ([]Credential, error)
	ListCredentialsNeedingReentry(ctx context.Context) ([]ListCredentialsNeedingReentryRow, error)
	ListDeviceFacts(ctx context.Context, deviceID uuid.UUID) ([]DeviceFact, error)
	ListDeviceRoles(ctx context.Context, deviceID uuid.UUID) ([]DeviceRole, error)
	// ===== Device templates ====================================================
	ListDeviceTemplates(ctx context.Context) ([]DeviceTemplate, error)
	ListDevicesByCategory(ctx context.Context, category string) ([]Device, error)
	ListDevicesByRole(ctx context.Context, role string) ([]Device, error)
	// Devices with a reachable IP but no monitoring check yet — the seeder turns
	// each into a default TCP check (port chosen by category).
	ListDevicesNeedingDefaultCheck(ctx context.Context) ([]ListDevicesNeedingDefaultCheckRow, error)
	ListDiscoveryJobs(ctx context.Context) ([]DiscoveryJob, error)
	ListDiscoveryResults(ctx context.Context, jobID uuid.UUID) ([]DiscoveryResult, error)
	// A check is due when enabled and either never run or its interval elapsed.
	ListDueMonitoringChecks(ctx context.Context) ([]MonitoringCheck, error)
	ListEnabledAlertRules(ctx context.Context) ([]AlertRule, error)
	// ---- Monitoring state for evaluation --------------------------------------
	// The evaluator's input: every enabled check joined to its device so rules
	// can filter by category and alerts can carry a readable device name.
	ListEnabledChecksWithDevice(ctx context.Context) ([]ListEnabledChecksWithDeviceRow, error)
	ListHAMembers(ctx context.Context, deviceID uuid.UUID) ([]FirewallHaMember, error)
	ListInterfaces(ctx context.Context, deviceID uuid.UUID) ([]Interface, error)
	ListLicenses(ctx context.Context, deviceID uuid.UUID) ([]FirewallLicense, error)
	// Full flat list for building the location tree client-side.
	ListLocations(ctx context.Context) ([]Location, error)
	ListLookups(ctx context.Context, kind string) ([]Lookup, error)
	ListLowStockParts(ctx context.Context) ([]SparePart, error)
	// ---- Read APIs for the device detail Ports / MAC / ARP tabs --------------
	// The switch FDB with the local port name and, when the MAC belongs to a
	// known device interface, that owner device's name + vendor (real correlation,
	// no OUI guesswork).
	ListMACForDevice(ctx context.Context, deviceID uuid.UUID) ([]ListMACForDeviceRow, error)
	ListMibFiles(ctx context.Context) ([]MibFile, error)
	ListMibObjects(ctx context.Context, mibFileID uuid.UUID) ([]MibObject, error)
	ListMonitoringChecks(ctx context.Context) ([]MonitoringCheck, error)
	ListMonitoringChecksByDevice(ctx context.Context, deviceID uuid.UUID) ([]MonitoringCheck, error)
	ListMonitoringSamplesByCheck(ctx context.Context, arg ListMonitoringSamplesByCheckParams) ([]MonitoringSample, error)
	ListMonitoringSamplesByDevice(ctx context.Context, arg ListMonitoringSamplesByDeviceParams) ([]MonitoringSample, error)
	ListNVRChannels(ctx context.Context, nvrDeviceID uuid.UUID) ([]NvrChannel, error)
	ListNeighbors(ctx context.Context, deviceID uuid.UUID) ([]Neighbor, error)
	ListOIDMappings(ctx context.Context) ([]OidMapping, error)
	ListPbxPhones(ctx context.Context, deviceID uuid.UUID) ([]PbxPhone, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPortVlans(ctx context.Context, deviceID uuid.UUID) ([]PortVlan, error)
	ListPrinterSupplies(ctx context.Context, deviceID uuid.UUID) ([]PrinterSupply, error)
	ListPurchases(ctx context.Context) ([]Purchase, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListRootLocations(ctx context.Context) ([]Location, error)
	ListServerStorage(ctx context.Context, deviceID uuid.UUID) ([]ServerStorage, error)
	ListSettings(ctx context.Context) ([]ListSettingsRow, error)
	ListSpareParts(ctx context.Context) ([]SparePart, error)
	ListSubnets(ctx context.Context) ([]Subnet, error)
	ListSubnetsByLocation(ctx context.Context, locationID uuid.UUID) ([]Subnet, error)
	ListSystems(ctx context.Context) ([]System, error)
	ListTopologyLinks(ctx context.Context, localDeviceID uuid.UUID) ([]TopologyLink, error)
	// ===== RBAC: users / roles / permissions ==================================
	ListUsers(ctx context.Context) ([]User, error)
	ListVMsByHost(ctx context.Context, hostDeviceID uuid.UUID) ([]VirtualMachine, error)
	// ===== Vendor fingerprints =================================================
	ListVendorFingerprints(ctx context.Context) ([]VendorFingerprint, error)
	ListVlans(ctx context.Context, deviceID uuid.UUID) ([]Vlan, error)
	ListVpnTunnels(ctx context.Context, deviceID uuid.UUID) ([]FirewallVpnTunnel, error)
	ListWorkOrderEvents(ctx context.Context, workOrderID uuid.UUID) ([]WorkOrderEvent, error)
	ListWorkOrderParts(ctx context.Context, workOrderID uuid.UUID) ([]WorkOrderPart, error)
	ListWorkOrders(ctx context.Context) ([]WorkOrder, error)
	ListWorkOrdersByDevice(ctx context.Context, deviceID *uuid.UUID) ([]WorkOrder, error)
	// Reconcile key for an UNSCOPED scan (no site selected): match by primary_ip
	// alone so a re-scan updates the existing device regardless of an
	// operator-assigned location_id, instead of duplicating it. Most-recent wins.
	LiveDeviceByIP(ctx context.Context, primaryIp *netip.Addr) (Device, error)
	// Identity reconciliation key (multi-hotel safe): same IP can recur across
	// hotels, so a live device is unique by (primary_ip, location). location_id is
	// matched NULL-safe (IS NOT DISTINCT FROM) so an unscoped scan (no site
	// selected, location_id = NULL) still reconciles instead of duplicating.
	LiveDeviceByIPAndLocation(ctx context.Context, arg LiveDeviceByIPAndLocationParams) (Device, error)
	MACCountByPort(ctx context.Context, deviceID uuid.UUID) ([]MACCountByPortRow, error)
	// Live fleet rollup: how many checks sit in each status bucket.
	MonitoringStatusOverview(ctx context.Context) ([]MonitoringStatusOverviewRow, error)
	// ---- Alerts ---------------------------------------------------------------
	// Atomic open: ON CONFLICT against idx_alerts_one_open means a second open
	// for the same (rule, check) is a no-op. RETURNING yields a row ONLY on a
	// real insert, so the engine fires the work-order bridge exactly once.
	OpenAlert(ctx context.Context, arg OpenAlertParams) (Alert, error)
	PermissionsForRole(ctx context.Context, roleID uuid.UUID) ([]Permission, error)
	// Persist the rollup the engine computed (status + failure counter) onto the
	// check after a poll. History rows go to monitoring_samples separately.
	RecordMonitoringResult(ctx context.Context, arg RecordMonitoringResultParams) (MonitoringCheck, error)
	// Bump version + stamp the rotation; sets the new key's fingerprint.
	RecordRotation(ctx context.Context, arg RecordRotationParams) error
	ResolveAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	// The resolver-assembly query: for a device IP, return every credential in a
	// group bound to either a subnet that contains the IP (more specific) or a
	// location anchor, with the binding specificity + member priority so the
	// pure resolver (internal/credresolver) can order them.
	//   specificity 2 = subnet binding, 1 = location binding.
	ResolveCandidatesForIP(ctx context.Context, arg ResolveCandidatesForIPParams) ([]ResolveCandidatesForIPRow, error)
	// Auto-resolve: any un-resolved alert whose check has recovered to 'up'.
	ResolveRecoveredAlerts(ctx context.Context) ([]ResolveRecoveredAlertsRow, error)
	// Fleet-wide role rollup: how many devices hold each role (the CMDB role cut).
	RoleSummary(ctx context.Context) ([]RoleSummaryRow, error)
	RolesForUser(ctx context.Context, userID uuid.UUID) ([]Role, error)
	SearchByHostname(ctx context.Context, hostname *string) ([]SearchByHostnameRow, error)
	// Primary search entry point for the IP → MAC → port path resolution.
	SearchByIP(ctx context.Context, primaryIp *netip.Addr) (SearchByIPRow, error)
	// Finds the switch(es) that have this MAC in their FDB, then joins the
	// interface for port + VLAN detail.
	SearchByMAC(ctx context.Context, mac string) ([]SearchByMACRow, error)
	SearchMibObjects(ctx context.Context, name string) ([]MibObject, error)
	SetAlertRuleEnabled(ctx context.Context, arg SetAlertRuleEnabledParams) (AlertRule, error)
	SetAlertWorkOrder(ctx context.Context, arg SetAlertWorkOrderParams) error
	// Bind-on-success: record the credential that last authenticated.
	SetDeviceCredential(ctx context.Context, arg SetDeviceCredentialParams) error
	// Stores the scan spec (mode/targets/creds) so the job can be re-run as-is.
	SetDiscoveryJobMetadata(ctx context.Context, arg SetDiscoveryJobMetadataParams) error
	SetMonitoringCheckEnabled(ctx context.Context, arg SetMonitoringCheckEnabledParams) (MonitoringCheck, error)
	SetRolePermissionsClear(ctx context.Context, roleID uuid.UUID) error
	SetUserRolesClear(ctx context.Context, userID uuid.UUID) error
	TotalExpenses(ctx context.Context) (float64, error)
	TouchDeviceDiscovery(ctx context.Context, arg TouchDeviceDiscoveryParams) error
	TouchValidation(ctx context.Context) error
	// Rename + weak-flag update (Credentials CRUD edit).
	UpdateCredentialMeta(ctx context.Context, arg UpdateCredentialMetaParams) (Credential, error)
	// Used by key rotation: re-seal the secret under a new key + KeyID.
	UpdateCredentialSecret(ctx context.Context, arg UpdateCredentialSecretParams) error
	// Operator edit of a device's identity fields (Inventory CRUD).
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
	// Reflect the worst current check status onto the device row so device lists
	// show a live health badge without a per-row sample query.
	UpdateDeviceMonitoringStatus(ctx context.Context, arg UpdateDeviceMonitoringStatusParams) error
	UpdateDeviceTemplate(ctx context.Context, arg UpdateDeviceTemplateParams) (DeviceTemplate, error)
	// Reconcile path: refresh a live device's mutable identity fields on
	// re-discovery (keyed by the caller to the (primary_ip, location) match).
	UpdateDiscoveredDevice(ctx context.Context, arg UpdateDiscoveredDeviceParams) (Device, error)
	UpdateDiscoveryJobStatus(ctx context.Context, arg UpdateDiscoveryJobStatusParams) error
	UpdateDiscoveryResult(ctx context.Context, arg UpdateDiscoveryResultParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateSparePart(ctx context.Context, arg UpdateSparePartParams) (SparePart, error)
	UpdateSystem(ctx context.Context, arg UpdateSystemParams) (System, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVendorFingerprint(ctx context.Context, arg UpdateVendorFingerprintParams) (VendorFingerprint, error)
	UpdateWorkOrder(ctx context.Context, arg UpdateWorkOrderParams) (WorkOrder, error)
	// ---- ARP entries ---------------------------------------------------------
	UpsertARP(ctx context.Context, arg UpsertARPParams) error
	UpsertAccessPoint(ctx context.Context, arg UpsertAccessPointParams) (AccessPoint, error)
	UpsertBMCInfo(ctx context.Context, arg UpsertBMCInfoParams) error
	UpsertBMCSensor(ctx context.Context, arg UpsertBMCSensorParams) error
	UpsertCameraInfo(ctx context.Context, arg UpsertCameraInfoParams) (CameraInfo, error)
	UpsertDeviceFact(ctx context.Context, arg UpsertDeviceFactParams) error
	// Adopt / record the current key's fingerprint (generate + first-run adopt).
	UpsertEncryptionMetadata(ctx context.Context, arg UpsertEncryptionMetadataParams) error
	UpsertFirewallStatus(ctx context.Context, arg UpsertFirewallStatusParams) error
	UpsertHAMember(ctx context.Context, arg UpsertHAMemberParams) error
	// ---- Interfaces -----------------------------------------------------------
	UpsertInterface(ctx context.Context, arg UpsertInterfaceParams) (Interface, error)
	UpsertLicense(ctx context.Context, arg UpsertLicenseParams) error
	// ---- MAC address table ---------------------------------------------------
	UpsertMAC(ctx context.Context, arg UpsertMACParams) error
	// Idempotent registration: re-registering the same (device, kind, port)
	// updates the schedule knobs without resetting the live status counters.
	UpsertMonitoringCheck(ctx context.Context, arg UpsertMonitoringCheckParams) (MonitoringCheck, error)
	UpsertNVRChannel(ctx context.Context, arg UpsertNVRChannelParams) (NvrChannel, error)
	// ---- Neighbors (LLDP/CDP) -----------------------------------------------
	UpsertNeighbor(ctx context.Context, arg UpsertNeighborParams) (Neighbor, error)
	UpsertPbxPhone(ctx context.Context, arg UpsertPbxPhoneParams) error
	UpsertPortVlan(ctx context.Context, arg UpsertPortVlanParams) error
	UpsertPrinterSupply(ctx context.Context, arg UpsertPrinterSupplyParams) error
	UpsertServerStorage(ctx context.Context, arg UpsertServerStorageParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	// ---- Topology links ------------------------------------------------------
	UpsertTopologyLink(ctx context.Context, arg UpsertTopologyLinkParams) error
	UpsertUPSStatus(ctx context.Context, arg UpsertUPSStatusParams) error
	// Upsert keyed on (host, name): re-collecting refreshes state without dups.
	UpsertVM(ctx context.Context, arg UpsertVMParams) (VirtualMachine, error)
	// ---- VLANs ----------------------------------------------------------------
	UpsertVlan(ctx context.Context, arg UpsertVlanParams) (Vlan, error)
	UpsertVpnTunnel(ctx context.Context, arg UpsertVpnTunnelParams) error
	UpsertWLANControllerInfo(ctx context.Context, arg UpsertWLANControllerInfoParams) (WlanControllerInfo, error)
}

var _ Querier = (*Queries)(nil)
