// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: relay_agents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const agentJobStatusCounts = `-- name: AgentJobStatusCounts :many
SELECT status::text AS status, count(*) AS n FROM agent_jobs GROUP BY status
`

type AgentJobStatusCountsRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

// Fleet-wide collect-job rollup by status (acceptance / queue-visibility report).
func (q *Queries) AgentJobStatusCounts(ctx context.Context) ([]AgentJobStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, agentJobStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentJobStatusCountsRow{}
	for rows.Next() {
		var i AgentJobStatusCountsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectionProgressForJob = `-- name: CollectionProgressForJob :one
SELECT
  count(*) FILTER (WHERE status = 'queued' AND (next_attempt_at IS NULL OR next_attempt_at <= now()))::bigint AS queued,
  count(*) FILTER (WHERE status = 'queued' AND next_attempt_at > now())::bigint               AS retry_waiting,
  count(*) FILTER (WHERE status = 'dispatched')::bigint                                        AS running,
  count(*) FILTER (WHERE status = 'done')::bigint                                              AS done,
  count(*) FILTER (WHERE status = 'failed')::bigint                                            AS failed
FROM agent_jobs
WHERE kind = 'collect_os' AND device_id IN (
  SELECT device_id FROM discovery_results WHERE job_id = $1 AND device_id IS NOT NULL
)
`

type CollectionProgressForJobRow struct {
	Queued       int64 `json:"queued"`
	RetryWaiting int64 `json:"retry_waiting"`
	Running      int64 `json:"running"`
	Done         int64 `json:"done"`
	Failed       int64 `json:"failed"`
}

// Collect-job rollup for the devices a discovery job enrolled — lets the UI/API show
// "Discovery complete · collecting N" while deep collection drains AFTER the scan's
// probe/enroll phase finishes. retry_waiting (backoff) is split from queued so the
// operator sees jobs that are waiting vs ready. The scan is "settled" when
// queued + retry_waiting + running all reach 0.
func (q *Queries) CollectionProgressForJob(ctx context.Context, jobID uuid.UUID) (CollectionProgressForJobRow, error) {
	row := q.db.QueryRow(ctx, collectionProgressForJob, jobID)
	var i CollectionProgressForJobRow
	err := row.Scan(
		&i.Queued,
		&i.RetryWaiting,
		&i.Running,
		&i.Done,
		&i.Failed,
	)
	return i, err
}

const completeAgentJob = `-- name: CompleteAgentJob :exec
UPDATE agent_jobs
SET status = $2, result = $3, category = $4, error = $5, finished_at = now()
WHERE id = $1
`

type CompleteAgentJobParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	Result   []byte    `json:"result"`
	Category string    `json:"category"`
	Error    string    `json:"error"`
}

func (q *Queries) CompleteAgentJob(ctx context.Context, arg CompleteAgentJobParams) error {
	_, err := q.db.Exec(ctx, completeAgentJob,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Category,
		arg.Error,
	)
	return err
}

const countActiveDeviceAgentJobs = `-- name: CountActiveDeviceAgentJobs :one
SELECT count(*) FROM agent_jobs
WHERE device_id = $1 AND kind = 'collect_os' AND status IN ('queued', 'dispatched')
`

// In-flight collection jobs for a device (queued or dispatched) — used to avoid
// enqueuing a duplicate when a scan re-routes the same device to its site agent.
func (q *Queries) CountActiveDeviceAgentJobs(ctx context.Context, deviceID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDeviceAgentJobs, deviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgentJobsByStatusForAgent = `-- name: CountAgentJobsByStatusForAgent :many
SELECT status::text AS status, count(*) AS n FROM agent_jobs WHERE agent_id = $1 GROUP BY status
`

type CountAgentJobsByStatusForAgentRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

// Per-agent job rollup by status (queued / dispatched / done / failed).
func (q *Queries) CountAgentJobsByStatusForAgent(ctx context.Context, agentID uuid.UUID) ([]CountAgentJobsByStatusForAgentRow, error) {
	rows, err := q.db.Query(ctx, countAgentJobsByStatusForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAgentJobsByStatusForAgentRow{}
	for rows.Next() {
		var i CountAgentJobsByStatusForAgentRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDispatchedAgentJobs = `-- name: CountDispatchedAgentJobs :one
SELECT count(*) FROM agent_jobs WHERE agent_id = $1 AND status = 'dispatched'
`

// Jobs currently handed to the agent and not yet reported back — the in-flight
// count subtracted from the dispatch cap to compute the poll budget.
func (q *Queries) CountDispatchedAgentJobs(ctx context.Context, agentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDispatchedAgentJobs, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedAgentJobs = `-- name: CountFailedAgentJobs :one
SELECT count(*) FROM agent_jobs WHERE agent_id = $1 AND status = 'failed'
`

// Failed jobs for one agent (for the agent detail page + Data Quality count).
func (q *Queries) CountFailedAgentJobs(ctx context.Context, agentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedAgentJobs, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentJob = `-- name: CreateAgentJob :one
INSERT INTO agent_jobs (agent_id, device_id, credential_id, kind, protocol, target, request)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, agent_id, device_id, credential_id, kind, protocol, target, status, request, result, category, error, created_at, dispatched_at, finished_at, attempt, max_attempts, next_attempt_at
`

type CreateAgentJobParams struct {
	AgentID      uuid.UUID  `json:"agent_id"`
	DeviceID     *uuid.UUID `json:"device_id"`
	CredentialID *uuid.UUID `json:"credential_id"`
	Kind         string     `json:"kind"`
	Protocol     string     `json:"protocol"`
	Target       string     `json:"target"`
	Request      []byte     `json:"request"`
}

func (q *Queries) CreateAgentJob(ctx context.Context, arg CreateAgentJobParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, createAgentJob,
		arg.AgentID,
		arg.DeviceID,
		arg.CredentialID,
		arg.Kind,
		arg.Protocol,
		arg.Target,
		arg.Request,
	)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.DeviceID,
		&i.CredentialID,
		&i.Kind,
		&i.Protocol,
		&i.Target,
		&i.Status,
		&i.Request,
		&i.Result,
		&i.Category,
		&i.Error,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const createRelayAgent = `-- name: CreateRelayAgent :one

INSERT INTO relay_agents (name, location_id, token_hash)
VALUES ($1, $2, $3)
RETURNING id, name, location_id, token_hash, hostname, ip, os, version, capabilities, status, enabled, last_heartbeat, last_error, created_at, updated_at
`

type CreateRelayAgentParams struct {
	Name       string     `json:"name"`
	LocationID *uuid.UUID `json:"location_id"`
	TokenHash  string     `json:"token_hash"`
}

// Relay Agent / Site Collector persistence. No secrets stored here; the agent
// token is stored only as a SHA-256 hash.
func (q *Queries) CreateRelayAgent(ctx context.Context, arg CreateRelayAgentParams) (RelayAgent, error) {
	row := q.db.QueryRow(ctx, createRelayAgent, arg.Name, arg.LocationID, arg.TokenHash)
	var i RelayAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationID,
		&i.TokenHash,
		&i.Hostname,
		&i.Ip,
		&i.Os,
		&i.Version,
		&i.Capabilities,
		&i.Status,
		&i.Enabled,
		&i.LastHeartbeat,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRelayAgent = `-- name: DeleteRelayAgent :exec
DELETE FROM relay_agents WHERE id = $1
`

func (q *Queries) DeleteRelayAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelayAgent, id)
	return err
}

const getAgentJob = `-- name: GetAgentJob :one
SELECT id, agent_id, device_id, credential_id, kind, protocol, target, status, request, result, category, error, created_at, dispatched_at, finished_at, attempt, max_attempts, next_attempt_at FROM agent_jobs WHERE id = $1
`

func (q *Queries) GetAgentJob(ctx context.Context, id uuid.UUID) (AgentJob, error) {
	row := q.db.QueryRow(ctx, getAgentJob, id)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.DeviceID,
		&i.CredentialID,
		&i.Kind,
		&i.Protocol,
		&i.Target,
		&i.Status,
		&i.Request,
		&i.Result,
		&i.Category,
		&i.Error,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const getRelayAgent = `-- name: GetRelayAgent :one
SELECT id, name, location_id, token_hash, hostname, ip, os, version, capabilities, status, enabled, last_heartbeat, last_error, created_at, updated_at FROM relay_agents WHERE id = $1
`

func (q *Queries) GetRelayAgent(ctx context.Context, id uuid.UUID) (RelayAgent, error) {
	row := q.db.QueryRow(ctx, getRelayAgent, id)
	var i RelayAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationID,
		&i.TokenHash,
		&i.Hostname,
		&i.Ip,
		&i.Os,
		&i.Version,
		&i.Capabilities,
		&i.Status,
		&i.Enabled,
		&i.LastHeartbeat,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelayAgentByToken = `-- name: GetRelayAgentByToken :one
SELECT id, name, location_id, token_hash, hostname, ip, os, version, capabilities, status, enabled, last_heartbeat, last_error, created_at, updated_at FROM relay_agents WHERE token_hash = $1
`

func (q *Queries) GetRelayAgentByToken(ctx context.Context, tokenHash string) (RelayAgent, error) {
	row := q.db.QueryRow(ctx, getRelayAgentByToken, tokenHash)
	var i RelayAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationID,
		&i.TokenHash,
		&i.Hostname,
		&i.Ip,
		&i.Os,
		&i.Version,
		&i.Capabilities,
		&i.Status,
		&i.Enabled,
		&i.LastHeartbeat,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentJobs = `-- name: ListAgentJobs :many
SELECT id, agent_id, device_id, kind, protocol, target, status, category, error, created_at, dispatched_at, finished_at
FROM agent_jobs WHERE agent_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListAgentJobsParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Limit   int32     `json:"limit"`
}

type ListAgentJobsRow struct {
	ID           uuid.UUID  `json:"id"`
	AgentID      uuid.UUID  `json:"agent_id"`
	DeviceID     *uuid.UUID `json:"device_id"`
	Kind         string     `json:"kind"`
	Protocol     string     `json:"protocol"`
	Target       string     `json:"target"`
	Status       string     `json:"status"`
	Category     string     `json:"category"`
	Error        string     `json:"error"`
	CreatedAt    time.Time  `json:"created_at"`
	DispatchedAt *time.Time `json:"dispatched_at"`
	FinishedAt   *time.Time `json:"finished_at"`
}

func (q *Queries) ListAgentJobs(ctx context.Context, arg ListAgentJobsParams) ([]ListAgentJobsRow, error) {
	rows, err := q.db.Query(ctx, listAgentJobs, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentJobsRow{}
	for rows.Next() {
		var i ListAgentJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.DeviceID,
			&i.Kind,
			&i.Protocol,
			&i.Target,
			&i.Status,
			&i.Category,
			&i.Error,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesWithActiveAgentJobs = `-- name: ListDevicesWithActiveAgentJobs :many
SELECT DISTINCT device_id FROM agent_jobs
WHERE kind = 'collect_os' AND status IN ('queued', 'dispatched') AND device_id IS NOT NULL
`

// Device ids with an in-flight collect_os job (queued or dispatched). Feeds the
// pending_collection management state so an in-flight host is not misreported as a
// terminal failure from its stale direct-probe attempt.
func (q *Queries) ListDevicesWithActiveAgentJobs(ctx context.Context) ([]*uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDevicesWithActiveAgentJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*uuid.UUID{}
	for rows.Next() {
		var device_id *uuid.UUID
		if err := rows.Scan(&device_id); err != nil {
			return nil, err
		}
		items = append(items, device_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAgentJobsAll = `-- name: ListRecentAgentJobsAll :many
SELECT id, agent_id, device_id, kind, protocol, target, status, category, error, created_at, dispatched_at, finished_at
FROM agent_jobs ORDER BY created_at DESC LIMIT $1
`

type ListRecentAgentJobsAllRow struct {
	ID           uuid.UUID  `json:"id"`
	AgentID      uuid.UUID  `json:"agent_id"`
	DeviceID     *uuid.UUID `json:"device_id"`
	Kind         string     `json:"kind"`
	Protocol     string     `json:"protocol"`
	Target       string     `json:"target"`
	Status       string     `json:"status"`
	Category     string     `json:"category"`
	Error        string     `json:"error"`
	CreatedAt    time.Time  `json:"created_at"`
	DispatchedAt *time.Time `json:"dispatched_at"`
	FinishedAt   *time.Time `json:"finished_at"`
}

// Recent jobs across all agents (fleet-wide failed-job / Data Quality views).
func (q *Queries) ListRecentAgentJobsAll(ctx context.Context, limit int32) ([]ListRecentAgentJobsAllRow, error) {
	rows, err := q.db.Query(ctx, listRecentAgentJobsAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentAgentJobsAllRow{}
	for rows.Next() {
		var i ListRecentAgentJobsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.DeviceID,
			&i.Kind,
			&i.Protocol,
			&i.Target,
			&i.Status,
			&i.Category,
			&i.Error,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelayAgents = `-- name: ListRelayAgents :many
SELECT id, name, location_id, token_hash, hostname, ip, os, version, capabilities, status, enabled, last_heartbeat, last_error, created_at, updated_at FROM relay_agents ORDER BY name
`

func (q *Queries) ListRelayAgents(ctx context.Context) ([]RelayAgent, error) {
	rows, err := q.db.Query(ctx, listRelayAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RelayAgent{}
	for rows.Next() {
		var i RelayAgent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocationID,
			&i.TokenHash,
			&i.Hostname,
			&i.Ip,
			&i.Os,
			&i.Version,
			&i.Capabilities,
			&i.Status,
			&i.Enabled,
			&i.LastHeartbeat,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableAgentJobs = `-- name: ListRunnableAgentJobs :many
SELECT id, agent_id, device_id, credential_id, kind, protocol, target, status, request, result, category, error, created_at, dispatched_at, finished_at, attempt, max_attempts, next_attempt_at FROM agent_jobs
WHERE agent_id = $1 AND status = 'queued'
  AND (next_attempt_at IS NULL OR next_attempt_at <= now())
ORDER BY created_at
LIMIT $2
`

type ListRunnableAgentJobsParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Limit   int32     `json:"limit"`
}

// The next queued jobs for an agent that are ready to run now (backoff elapsed),
// capped by $2 = the per-agent dispatch budget (cap - in-flight dispatched). This
// is what bounds the thundering herd: the server never hands one agent more than
// the cap of concurrent collect jobs.
func (q *Queries) ListRunnableAgentJobs(ctx context.Context, arg ListRunnableAgentJobsParams) ([]AgentJob, error) {
	rows, err := q.db.Query(ctx, listRunnableAgentJobs, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentJob{}
	for rows.Next() {
		var i AgentJob
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.DeviceID,
			&i.CredentialID,
			&i.Kind,
			&i.Protocol,
			&i.Target,
			&i.Status,
			&i.Request,
			&i.Result,
			&i.Category,
			&i.Error,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.FinishedAt,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentJobDispatched = `-- name: MarkAgentJobDispatched :exec
UPDATE agent_jobs SET status = 'dispatched', dispatched_at = now() WHERE id = $1
`

func (q *Queries) MarkAgentJobDispatched(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAgentJobDispatched, id)
	return err
}

const relayAgentHeartbeat = `-- name: RelayAgentHeartbeat :exec
UPDATE relay_agents
SET status = CASE WHEN enabled THEN 'online' ELSE 'disabled' END,
    version = COALESCE(NULLIF($2, ''), version),
    last_heartbeat = now(), last_error = COALESCE(NULLIF($3, ''), last_error), updated_at = now()
WHERE id = $1
`

type RelayAgentHeartbeatParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) RelayAgentHeartbeat(ctx context.Context, arg RelayAgentHeartbeatParams) error {
	_, err := q.db.Exec(ctx, relayAgentHeartbeat, arg.ID, arg.Column2, arg.Column3)
	return err
}

const requeueAgentJob = `-- name: RequeueAgentJob :exec
UPDATE agent_jobs
SET status = 'queued', attempt = attempt + 1, next_attempt_at = $2,
    dispatched_at = NULL, error = $3, category = $4
WHERE id = $1
`

type RequeueAgentJobParams struct {
	ID            uuid.UUID  `json:"id"`
	NextAttemptAt *time.Time `json:"next_attempt_at"`
	Error         string     `json:"error"`
	Category      string     `json:"category"`
}

// Return a transiently-failed job to the queue with an incremented attempt and a
// backoff deadline ($2). Clears dispatched_at so it can be re-dispatched once the
// backoff elapses. Used for retryable (non-auth) collection failures.
func (q *Queries) RequeueAgentJob(ctx context.Context, arg RequeueAgentJobParams) error {
	_, err := q.db.Exec(ctx, requeueAgentJob,
		arg.ID,
		arg.NextAttemptAt,
		arg.Error,
		arg.Category,
	)
	return err
}

const requeueStaleAgentJobs = `-- name: RequeueStaleAgentJobs :execrows
UPDATE agent_jobs
SET status          = CASE WHEN attempt + 1 >= max_attempts THEN 'failed' ELSE 'queued' END,
    attempt         = attempt + 1,
    dispatched_at   = NULL,
    next_attempt_at = CASE WHEN attempt + 1 >= max_attempts THEN NULL ELSE now() END,
    finished_at     = CASE WHEN attempt + 1 >= max_attempts THEN now() ELSE finished_at END,
    error           = CASE WHEN attempt + 1 >= max_attempts
                           THEN 'agent did not report a result (stale dispatched; gave up after max attempts)'
                           ELSE error END,
    category        = CASE WHEN attempt + 1 >= max_attempts THEN 'agent_no_result' ELSE category END
WHERE kind = 'collect_os' AND status = 'dispatched'
  AND dispatched_at IS NOT NULL AND dispatched_at < $1
`

// Recover jobs stuck 'dispatched' whose agent never reported back (agent crash /
// dropped connection): requeue (bumped attempt) if attempts remain, else mark
// failed so they never block re-enqueue forever. $1 = dispatched-before cutoff.
func (q *Queries) RequeueStaleAgentJobs(ctx context.Context, dispatchedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStaleAgentJobs, dispatchedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveSiteAgent = `-- name: ResolveSiteAgent :one
SELECT id, name, location_id, token_hash, hostname, ip, os, version, capabilities, status, enabled, last_heartbeat, last_error, created_at, updated_at FROM relay_agents
WHERE location_id = $1 AND enabled AND status = 'online'
ORDER BY last_heartbeat DESC NULLS LAST
LIMIT 1
`

// The newest enabled, recently-online agent assigned to a location — used to
// prefer agent collection for devices in that site.
func (q *Queries) ResolveSiteAgent(ctx context.Context, locationID *uuid.UUID) (RelayAgent, error) {
	row := q.db.QueryRow(ctx, resolveSiteAgent, locationID)
	var i RelayAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationID,
		&i.TokenHash,
		&i.Hostname,
		&i.Ip,
		&i.Os,
		&i.Version,
		&i.Capabilities,
		&i.Status,
		&i.Enabled,
		&i.LastHeartbeat,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRelayAgentEnabled = `-- name: SetRelayAgentEnabled :exec
UPDATE relay_agents
SET enabled = $2, status = CASE WHEN $2 THEN status ELSE 'disabled' END, updated_at = now()
WHERE id = $1
`

type SetRelayAgentEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetRelayAgentEnabled(ctx context.Context, arg SetRelayAgentEnabledParams) error {
	_, err := q.db.Exec(ctx, setRelayAgentEnabled, arg.ID, arg.Enabled)
	return err
}

const setRelayAgentLocation = `-- name: SetRelayAgentLocation :exec
UPDATE relay_agents SET location_id = $2, updated_at = now() WHERE id = $1
`

type SetRelayAgentLocationParams struct {
	ID         uuid.UUID  `json:"id"`
	LocationID *uuid.UUID `json:"location_id"`
}

func (q *Queries) SetRelayAgentLocation(ctx context.Context, arg SetRelayAgentLocationParams) error {
	_, err := q.db.Exec(ctx, setRelayAgentLocation, arg.ID, arg.LocationID)
	return err
}

const setRelayAgentToken = `-- name: SetRelayAgentToken :exec
UPDATE relay_agents SET token_hash = $2, updated_at = now() WHERE id = $1
`

type SetRelayAgentTokenParams struct {
	ID        uuid.UUID `json:"id"`
	TokenHash string    `json:"token_hash"`
}

// Rotate an agent's enrollment token (only the new hash is stored). The previous
// token stops working immediately; the operator re-downloads a fresh installer.
func (q *Queries) SetRelayAgentToken(ctx context.Context, arg SetRelayAgentTokenParams) error {
	_, err := q.db.Exec(ctx, setRelayAgentToken, arg.ID, arg.TokenHash)
	return err
}

const updateRelayAgentIdentity = `-- name: UpdateRelayAgentIdentity :exec
UPDATE relay_agents
SET hostname = $2, ip = $3, os = $4, version = $5, capabilities = $6,
    status = 'online', last_heartbeat = now(), updated_at = now()
WHERE id = $1
`

type UpdateRelayAgentIdentityParams struct {
	ID           uuid.UUID `json:"id"`
	Hostname     string    `json:"hostname"`
	Ip           string    `json:"ip"`
	Os           string    `json:"os"`
	Version      string    `json:"version"`
	Capabilities []byte    `json:"capabilities"`
}

func (q *Queries) UpdateRelayAgentIdentity(ctx context.Context, arg UpdateRelayAgentIdentityParams) error {
	_, err := q.db.Exec(ctx, updateRelayAgentIdentity,
		arg.ID,
		arg.Hostname,
		arg.Ip,
		arg.Os,
		arg.Version,
		arg.Capabilities,
	)
	return err
}
