// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: report_schedules.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createReportSchedule = `-- name: CreateReportSchedule :one
INSERT INTO report_schedules (name, report_type, channel_id, frequency, hour_utc, enabled)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, name, report_type, channel_id, frequency, hour_utc, enabled, last_run_at, last_status, created_at
`

type CreateReportScheduleParams struct {
	Name       string     `json:"name"`
	ReportType string     `json:"report_type"`
	ChannelID  *uuid.UUID `json:"channel_id"`
	Frequency  string     `json:"frequency"`
	HourUtc    int32      `json:"hour_utc"`
	Enabled    bool       `json:"enabled"`
}

func (q *Queries) CreateReportSchedule(ctx context.Context, arg CreateReportScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, createReportSchedule,
		arg.Name,
		arg.ReportType,
		arg.ChannelID,
		arg.Frequency,
		arg.HourUtc,
		arg.Enabled,
	)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ReportType,
		&i.ChannelID,
		&i.Frequency,
		&i.HourUtc,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReportSchedule = `-- name: DeleteReportSchedule :exec
DELETE FROM report_schedules WHERE id = $1
`

func (q *Queries) DeleteReportSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReportSchedule, id)
	return err
}

const getReportSchedule = `-- name: GetReportSchedule :one
SELECT id, name, report_type, channel_id, frequency, hour_utc, enabled, last_run_at, last_status, created_at FROM report_schedules WHERE id = $1
`

func (q *Queries) GetReportSchedule(ctx context.Context, id uuid.UUID) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, getReportSchedule, id)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ReportType,
		&i.ChannelID,
		&i.Frequency,
		&i.HourUtc,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listReportSchedules = `-- name: ListReportSchedules :many
SELECT id, name, report_type, channel_id, frequency, hour_utc, enabled, last_run_at, last_status, created_at FROM report_schedules ORDER BY name
`

func (q *Queries) ListReportSchedules(ctx context.Context) ([]ReportSchedule, error) {
	rows, err := q.db.Query(ctx, listReportSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSchedule{}
	for rows.Next() {
		var i ReportSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ReportType,
			&i.ChannelID,
			&i.Frequency,
			&i.HourUtc,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordReportScheduleRun = `-- name: RecordReportScheduleRun :exec
UPDATE report_schedules SET last_run_at = now(), last_status = $2 WHERE id = $1
`

type RecordReportScheduleRunParams struct {
	ID         uuid.UUID `json:"id"`
	LastStatus string    `json:"last_status"`
}

func (q *Queries) RecordReportScheduleRun(ctx context.Context, arg RecordReportScheduleRunParams) error {
	_, err := q.db.Exec(ctx, recordReportScheduleRun, arg.ID, arg.LastStatus)
	return err
}

const setReportScheduleEnabled = `-- name: SetReportScheduleEnabled :one
UPDATE report_schedules SET enabled = $2 WHERE id = $1 RETURNING id, name, report_type, channel_id, frequency, hour_utc, enabled, last_run_at, last_status, created_at
`

type SetReportScheduleEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetReportScheduleEnabled(ctx context.Context, arg SetReportScheduleEnabledParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, setReportScheduleEnabled, arg.ID, arg.Enabled)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ReportType,
		&i.ChannelID,
		&i.Frequency,
		&i.HourUtc,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
	)
	return i, err
}
