// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: search.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createDiscoveryJob = `-- name: CreateDiscoveryJob :one
INSERT INTO discovery_jobs (location_id, subnet_id, scope_cidr, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, location_id, subnet_id, scope_cidr, status, started_at, finished_at, host_count, found_count, error, metadata, created_at
`

type CreateDiscoveryJobParams struct {
	LocationID *uuid.UUID    `json:"location_id"`
	SubnetID   *uuid.UUID    `json:"subnet_id"`
	ScopeCidr  *netip.Prefix `json:"scope_cidr"`
}

func (q *Queries) CreateDiscoveryJob(ctx context.Context, arg CreateDiscoveryJobParams) (DiscoveryJob, error) {
	row := q.db.QueryRow(ctx, createDiscoveryJob, arg.LocationID, arg.SubnetID, arg.ScopeCidr)
	var i DiscoveryJob
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SubnetID,
		&i.ScopeCidr,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HostCount,
		&i.FoundCount,
		&i.Error,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createDiscoveryJobEvent = `-- name: CreateDiscoveryJobEvent :one
INSERT INTO discovery_job_events (job_id, ip, device_id, stage, protocol, status, message)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING seq
`

type CreateDiscoveryJobEventParams struct {
	JobID    uuid.UUID   `json:"job_id"`
	Ip       *netip.Addr `json:"ip"`
	DeviceID *uuid.UUID  `json:"device_id"`
	Stage    string      `json:"stage"`
	Protocol string      `json:"protocol"`
	Status   string      `json:"status"`
	Message  string      `json:"message"`
}

// Persist one live-discovery event for completed-job playback (the live SSE feed
// is served from the in-memory hub; this is the durable history).
func (q *Queries) CreateDiscoveryJobEvent(ctx context.Context, arg CreateDiscoveryJobEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDiscoveryJobEvent,
		arg.JobID,
		arg.Ip,
		arg.DeviceID,
		arg.Stage,
		arg.Protocol,
		arg.Status,
		arg.Message,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const createDiscoveryResult = `-- name: CreateDiscoveryResult :one
INSERT INTO discovery_results (job_id, ip, outcome, probe_data)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, ip, outcome, device_id, driver, category, probe_data, error, probed_at, disposition, retry_count
`

type CreateDiscoveryResultParams struct {
	JobID     uuid.UUID  `json:"job_id"`
	Ip        netip.Addr `json:"ip"`
	Outcome   string     `json:"outcome"`
	ProbeData []byte     `json:"probe_data"`
}

func (q *Queries) CreateDiscoveryResult(ctx context.Context, arg CreateDiscoveryResultParams) (DiscoveryResult, error) {
	row := q.db.QueryRow(ctx, createDiscoveryResult,
		arg.JobID,
		arg.Ip,
		arg.Outcome,
		arg.ProbeData,
	)
	var i DiscoveryResult
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Ip,
		&i.Outcome,
		&i.DeviceID,
		&i.Driver,
		&i.Category,
		&i.ProbeData,
		&i.Error,
		&i.ProbedAt,
		&i.Disposition,
		&i.RetryCount,
	)
	return i, err
}

const deleteDiscoveryJob = `-- name: DeleteDiscoveryJob :exec
DELETE FROM discovery_jobs WHERE id = $1
`

// Removes a job and its results (discovery_results FK ON DELETE CASCADE).
func (q *Queries) DeleteDiscoveryJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDiscoveryJob, id)
	return err
}

const getDiscoveryJob = `-- name: GetDiscoveryJob :one
SELECT id, location_id, subnet_id, scope_cidr, status, started_at, finished_at, host_count, found_count, error, metadata, created_at FROM discovery_jobs WHERE id = $1
`

func (q *Queries) GetDiscoveryJob(ctx context.Context, id uuid.UUID) (DiscoveryJob, error) {
	row := q.db.QueryRow(ctx, getDiscoveryJob, id)
	var i DiscoveryJob
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SubnetID,
		&i.ScopeCidr,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HostCount,
		&i.FoundCount,
		&i.Error,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const latestDeviceProbeData = `-- name: LatestDeviceProbeData :one
SELECT probe_data FROM discovery_results
WHERE device_id = $1 ORDER BY probed_at DESC LIMIT 1
`

// The most recent scan probe_data for a device (open ports, evidence, etc.) —
// used to repair its reachability check from the ports it actually answered on.
func (q *Queries) LatestDeviceProbeData(ctx context.Context, deviceID *uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, latestDeviceProbeData, deviceID)
	var probe_data []byte
	err := row.Scan(&probe_data)
	return probe_data, err
}

const listDiscoveryJobEvents = `-- name: ListDiscoveryJobEvents :many
SELECT seq, job_id, ip, device_id, stage, protocol, status, message, created_at
FROM discovery_job_events WHERE job_id = $1 ORDER BY seq ASC LIMIT 5000
`

type ListDiscoveryJobEventsRow struct {
	Seq       int64       `json:"seq"`
	JobID     uuid.UUID   `json:"job_id"`
	Ip        *netip.Addr `json:"ip"`
	DeviceID  *uuid.UUID  `json:"device_id"`
	Stage     string      `json:"stage"`
	Protocol  string      `json:"protocol"`
	Status    string      `json:"status"`
	Message   string      `json:"message"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) ListDiscoveryJobEvents(ctx context.Context, jobID uuid.UUID) ([]ListDiscoveryJobEventsRow, error) {
	rows, err := q.db.Query(ctx, listDiscoveryJobEvents, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiscoveryJobEventsRow{}
	for rows.Next() {
		var i ListDiscoveryJobEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.JobID,
			&i.Ip,
			&i.DeviceID,
			&i.Stage,
			&i.Protocol,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryJobs = `-- name: ListDiscoveryJobs :many
SELECT id, location_id, subnet_id, scope_cidr, status, started_at, finished_at, host_count, found_count, error, metadata, created_at FROM discovery_jobs ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListDiscoveryJobs(ctx context.Context) ([]DiscoveryJob, error) {
	rows, err := q.db.Query(ctx, listDiscoveryJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoveryJob{}
	for rows.Next() {
		var i DiscoveryJob
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.SubnetID,
			&i.ScopeCidr,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.HostCount,
			&i.FoundCount,
			&i.Error,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryResults = `-- name: ListDiscoveryResults :many
SELECT id, job_id, ip, outcome, device_id, driver, category, probe_data, error, probed_at, disposition, retry_count FROM discovery_results WHERE job_id = $1 ORDER BY probed_at DESC
`

func (q *Queries) ListDiscoveryResults(ctx context.Context, jobID uuid.UUID) ([]DiscoveryResult, error) {
	rows, err := q.db.Query(ctx, listDiscoveryResults, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoveryResult{}
	for rows.Next() {
		var i DiscoveryResult
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Ip,
			&i.Outcome,
			&i.DeviceID,
			&i.Driver,
			&i.Category,
			&i.ProbeData,
			&i.Error,
			&i.ProbedAt,
			&i.Disposition,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnownDeviceScanDispositions = `-- name: ListKnownDeviceScanDispositions :many
SELECT device_id, disposition, job_id, probed_at
FROM discovery_results
WHERE device_id IS NOT NULL
  AND disposition IN ('known_seen','known_recovered','known_missed','known_unreachable')
ORDER BY probed_at DESC
LIMIT 5000
`

type ListKnownDeviceScanDispositionsRow struct {
	DeviceID    *uuid.UUID `json:"device_id"`
	Disposition string     `json:"disposition"`
	JobID       uuid.UUID  `json:"job_id"`
	ProbedAt    time.Time  `json:"probed_at"`
}

// Per-device scan dispositions across recent jobs (newest first). Powers the
// scan-stability Data Quality issues: missed-last-scan, flapping (recovered by
// retry), and frequently-missed-known-device. Bounded so the scan history of a
// long-lived deployment cannot blow up the query.
func (q *Queries) ListKnownDeviceScanDispositions(ctx context.Context) ([]ListKnownDeviceScanDispositionsRow, error) {
	rows, err := q.db.Query(ctx, listKnownDeviceScanDispositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKnownDeviceScanDispositionsRow{}
	for rows.Next() {
		var i ListKnownDeviceScanDispositionsRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Disposition,
			&i.JobID,
			&i.ProbedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByHostname = `-- name: SearchByHostname :many
SELECT id, name, primary_ip, hostname, category, status, location_id
FROM devices
WHERE (hostname ILIKE $1 OR name ILIKE $1) AND deleted_at IS NULL
ORDER BY name
LIMIT 20
`

type SearchByHostnameRow struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	PrimaryIp  *netip.Addr `json:"primary_ip"`
	Hostname   *string     `json:"hostname"`
	Category   string      `json:"category"`
	Status     string      `json:"status"`
	LocationID *uuid.UUID  `json:"location_id"`
}

func (q *Queries) SearchByHostname(ctx context.Context, hostname *string) ([]SearchByHostnameRow, error) {
	rows, err := q.db.Query(ctx, searchByHostname, hostname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchByHostnameRow{}
	for rows.Next() {
		var i SearchByHostnameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrimaryIp,
			&i.Hostname,
			&i.Category,
			&i.Status,
			&i.LocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByIP = `-- name: SearchByIP :one
SELECT id, name, primary_ip, hostname, category, status, location_id
FROM devices
WHERE primary_ip = $1 AND deleted_at IS NULL
LIMIT 1
`

type SearchByIPRow struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	PrimaryIp  *netip.Addr `json:"primary_ip"`
	Hostname   *string     `json:"hostname"`
	Category   string      `json:"category"`
	Status     string      `json:"status"`
	LocationID *uuid.UUID  `json:"location_id"`
}

// Primary search entry point for the IP → MAC → port path resolution.
func (q *Queries) SearchByIP(ctx context.Context, primaryIp *netip.Addr) (SearchByIPRow, error) {
	row := q.db.QueryRow(ctx, searchByIP, primaryIp)
	var i SearchByIPRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryIp,
		&i.Hostname,
		&i.Category,
		&i.Status,
		&i.LocationID,
	)
	return i, err
}

const searchByMAC = `-- name: SearchByMAC :many
SELECT
    m.mac, m.vlan_id, m.if_index, m.last_seen_at,
    d.id AS device_id, d.name AS switch_name, d.primary_ip AS switch_ip,
    i.if_name, i.if_alias, i.port_role,
    a.ip_address AS known_ip
FROM mac_addresses m
JOIN devices d ON d.id = m.device_id AND d.deleted_at IS NULL
LEFT JOIN interfaces i ON i.device_id = m.device_id AND i.if_index = m.if_index
LEFT JOIN arp_entries a ON a.mac = m.mac
WHERE m.mac = $1
ORDER BY m.last_seen_at DESC
`

type SearchByMACRow struct {
	Mac        string      `json:"mac"`
	VlanID     int32       `json:"vlan_id"`
	IfIndex    *int32      `json:"if_index"`
	LastSeenAt time.Time   `json:"last_seen_at"`
	DeviceID   uuid.UUID   `json:"device_id"`
	SwitchName string      `json:"switch_name"`
	SwitchIp   *netip.Addr `json:"switch_ip"`
	IfName     *string     `json:"if_name"`
	IfAlias    *string     `json:"if_alias"`
	PortRole   *string     `json:"port_role"`
	KnownIp    *netip.Addr `json:"known_ip"`
}

// Finds the switch(es) that have this MAC in their FDB, then joins the
// interface for port + VLAN detail.
func (q *Queries) SearchByMAC(ctx context.Context, mac string) ([]SearchByMACRow, error) {
	rows, err := q.db.Query(ctx, searchByMAC, mac)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchByMACRow{}
	for rows.Next() {
		var i SearchByMACRow
		if err := rows.Scan(
			&i.Mac,
			&i.VlanID,
			&i.IfIndex,
			&i.LastSeenAt,
			&i.DeviceID,
			&i.SwitchName,
			&i.SwitchIp,
			&i.IfName,
			&i.IfAlias,
			&i.PortRole,
			&i.KnownIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDiscoveryJobMetadata = `-- name: SetDiscoveryJobMetadata :exec
UPDATE discovery_jobs SET metadata = $2 WHERE id = $1
`

type SetDiscoveryJobMetadataParams struct {
	ID       uuid.UUID `json:"id"`
	Metadata []byte    `json:"metadata"`
}

// Stores the scan spec (mode/targets/creds) so the job can be re-run as-is.
func (q *Queries) SetDiscoveryJobMetadata(ctx context.Context, arg SetDiscoveryJobMetadataParams) error {
	_, err := q.db.Exec(ctx, setDiscoveryJobMetadata, arg.ID, arg.Metadata)
	return err
}

const updateDiscoveryJobStatus = `-- name: UpdateDiscoveryJobStatus :exec
UPDATE discovery_jobs
SET status = $2,
    started_at   = CASE WHEN $2 = 'running' THEN now() ELSE started_at END,
    finished_at  = CASE WHEN $2 IN ('completed','failed','cancelled') THEN now() ELSE finished_at END,
    host_count   = COALESCE($3, host_count),
    found_count  = COALESCE($4, found_count),
    error        = $5
WHERE id = $1
`

type UpdateDiscoveryJobStatusParams struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	HostCount  int32     `json:"host_count"`
	FoundCount int32     `json:"found_count"`
	Error      *string   `json:"error"`
}

func (q *Queries) UpdateDiscoveryJobStatus(ctx context.Context, arg UpdateDiscoveryJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateDiscoveryJobStatus,
		arg.ID,
		arg.Status,
		arg.HostCount,
		arg.FoundCount,
		arg.Error,
	)
	return err
}

const updateDiscoveryResult = `-- name: UpdateDiscoveryResult :exec
UPDATE discovery_results
SET outcome = $2, device_id = $3, driver = $4, category = $5, error = $6, probe_data = $7,
    disposition = $8, retry_count = $9
WHERE id = $1
`

type UpdateDiscoveryResultParams struct {
	ID          uuid.UUID  `json:"id"`
	Outcome     string     `json:"outcome"`
	DeviceID    *uuid.UUID `json:"device_id"`
	Driver      *string    `json:"driver"`
	Category    *string    `json:"category"`
	Error       *string    `json:"error"`
	ProbeData   []byte     `json:"probe_data"`
	Disposition string     `json:"disposition"`
	RetryCount  int32      `json:"retry_count"`
}

func (q *Queries) UpdateDiscoveryResult(ctx context.Context, arg UpdateDiscoveryResultParams) error {
	_, err := q.db.Exec(ctx, updateDiscoveryResult,
		arg.ID,
		arg.Outcome,
		arg.DeviceID,
		arg.Driver,
		arg.Category,
		arg.Error,
		arg.ProbeData,
		arg.Disposition,
		arg.RetryCount,
	)
	return err
}
