// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: security.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearAllCredentialSecrets = `-- name: ClearAllCredentialSecrets :exec
UPDATE credentials
SET encrypted_blob = ''::bytea, key_id = '', needs_secret_reentry = true, updated_at = now()
WHERE octet_length(encrypted_blob) > 0
`

// Lost-key recovery: wipe only the secret fields; preserve the record,
// metadata, assignments and group memberships. Flag for re-entry.
func (q *Queries) ClearAllCredentialSecrets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAllCredentialSecrets)
	return err
}

const clearReentryFlag = `-- name: ClearReentryFlag :exec
UPDATE credentials SET needs_secret_reentry = false WHERE id = $1
`

func (q *Queries) ClearReentryFlag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearReentryFlag, id)
	return err
}

const countCredentialsNeedingReentry = `-- name: CountCredentialsNeedingReentry :one
SELECT COUNT(*) FROM credentials WHERE needs_secret_reentry
`

func (q *Queries) CountCredentialsNeedingReentry(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCredentialsNeedingReentry)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEncryptedCredentials = `-- name: CountEncryptedCredentials :one

SELECT COUNT(*) FROM credentials WHERE octet_length(encrypted_blob) > 0
`

// ===== Credential secret accounting / recovery =============================
func (q *Queries) CountEncryptedCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEncryptedCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUndecryptableCredentials = `-- name: CountUndecryptableCredentials :one
SELECT COUNT(*) FROM credentials
WHERE octet_length(encrypted_blob) > 0 AND key_id <> $1
`

// Blobs sealed under a key id other than the one currently loaded.
func (q *Queries) CountUndecryptableCredentials(ctx context.Context, keyID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUndecryptableCredentials, keyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEncryptionMetadata = `-- name: GetEncryptionMetadata :one

SELECT id, fingerprint, key_id, algorithm, version, created_at, last_rotation_at, last_validation_at FROM encryption_metadata WHERE id = 1
`

// ===== Encryption key lifecycle (metadata only — never the key) ===========
func (q *Queries) GetEncryptionMetadata(ctx context.Context) (EncryptionMetadatum, error) {
	row := q.db.QueryRow(ctx, getEncryptionMetadata)
	var i EncryptionMetadatum
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.KeyID,
		&i.Algorithm,
		&i.Version,
		&i.CreatedAt,
		&i.LastRotationAt,
		&i.LastValidationAt,
	)
	return i, err
}

const listCredentialBlobs = `-- name: ListCredentialBlobs :many
SELECT id, name, kind, encrypted_blob, key_id
FROM credentials
WHERE octet_length(encrypted_blob) > 0
ORDER BY name
`

type ListCredentialBlobsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Kind          string    `json:"kind"`
	EncryptedBlob []byte    `json:"encrypted_blob"`
	KeyID         string    `json:"key_id"`
}

func (q *Queries) ListCredentialBlobs(ctx context.Context) ([]ListCredentialBlobsRow, error) {
	rows, err := q.db.Query(ctx, listCredentialBlobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialBlobsRow{}
	for rows.Next() {
		var i ListCredentialBlobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.EncryptedBlob,
			&i.KeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsNeedingReentry = `-- name: ListCredentialsNeedingReentry :many
SELECT id, name, kind, weak, needs_secret_reentry, created_at, updated_at
FROM credentials WHERE needs_secret_reentry ORDER BY name
`

type ListCredentialsNeedingReentryRow struct {
	ID                 uuid.UUID `json:"id"`
	Name               string    `json:"name"`
	Kind               string    `json:"kind"`
	Weak               bool      `json:"weak"`
	NeedsSecretReentry bool      `json:"needs_secret_reentry"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) ListCredentialsNeedingReentry(ctx context.Context) ([]ListCredentialsNeedingReentryRow, error) {
	rows, err := q.db.Query(ctx, listCredentialsNeedingReentry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsNeedingReentryRow{}
	for rows.Next() {
		var i ListCredentialsNeedingReentryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Weak,
			&i.NeedsSecretReentry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRotation = `-- name: RecordRotation :exec
INSERT INTO encryption_metadata (id, fingerprint, key_id, version, last_rotation_at)
VALUES (1, $1, $2, 1, now())
ON CONFLICT (id) DO UPDATE SET
    fingerprint = $1, key_id = $2,
    version = encryption_metadata.version + 1,
    last_rotation_at = now()
`

type RecordRotationParams struct {
	Fingerprint string `json:"fingerprint"`
	KeyID       string `json:"key_id"`
}

// Bump version + stamp the rotation; sets the new key's fingerprint.
func (q *Queries) RecordRotation(ctx context.Context, arg RecordRotationParams) error {
	_, err := q.db.Exec(ctx, recordRotation, arg.Fingerprint, arg.KeyID)
	return err
}

const touchValidation = `-- name: TouchValidation :exec
UPDATE encryption_metadata SET last_validation_at = now() WHERE id = 1
`

func (q *Queries) TouchValidation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, touchValidation)
	return err
}

const upsertEncryptionMetadata = `-- name: UpsertEncryptionMetadata :exec
INSERT INTO encryption_metadata (id, fingerprint, key_id, version)
VALUES (1, $1, $2, 1)
ON CONFLICT (id) DO UPDATE SET fingerprint = $1, key_id = $2
`

type UpsertEncryptionMetadataParams struct {
	Fingerprint string `json:"fingerprint"`
	KeyID       string `json:"key_id"`
}

// Adopt / record the current key's fingerprint (generate + first-run adopt).
func (q *Queries) UpsertEncryptionMetadata(ctx context.Context, arg UpsertEncryptionMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertEncryptionMetadata, arg.Fingerprint, arg.KeyID)
	return err
}
