// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ssh_cli.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countSSHCliBySource = `-- name: CountSSHCliBySource :many
SELECT source, status, count(*) AS n FROM ssh_cli_results WHERE device_id = $1 GROUP BY source, status
`

type CountSSHCliBySourceRow struct {
	Source string `json:"source"`
	Status string `json:"status"`
	N      int64  `json:"n"`
}

func (q *Queries) CountSSHCliBySource(ctx context.Context, deviceID uuid.UUID) ([]CountSSHCliBySourceRow, error) {
	rows, err := q.db.Query(ctx, countSSHCliBySource, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSSHCliBySourceRow{}
	for rows.Next() {
		var i CountSSHCliBySourceRow
		if err := rows.Scan(&i.Source, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSSHCliResultsForSource = `-- name: DeleteSSHCliResultsForSource :exec
DELETE FROM ssh_cli_results WHERE device_id = $1 AND source = $2
`

type DeleteSSHCliResultsForSourceParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	Source   string    `json:"source"`
}

func (q *Queries) DeleteSSHCliResultsForSource(ctx context.Context, arg DeleteSSHCliResultsForSourceParams) error {
	_, err := q.db.Exec(ctx, deleteSSHCliResultsForSource, arg.DeviceID, arg.Source)
	return err
}

const listSSHCliResults = `-- name: ListSSHCliResults :many
SELECT id, device_id, source, command, status, output_preview, parsed_rows, error_message, collected_at FROM ssh_cli_results WHERE device_id = $1 ORDER BY command
`

func (q *Queries) ListSSHCliResults(ctx context.Context, deviceID uuid.UUID) ([]SshCliResult, error) {
	rows, err := q.db.Query(ctx, listSSHCliResults, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SshCliResult{}
	for rows.Next() {
		var i SshCliResult
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Source,
			&i.Command,
			&i.Status,
			&i.OutputPreview,
			&i.ParsedRows,
			&i.ErrorMessage,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSSHCliResult = `-- name: UpsertSSHCliResult :exec
INSERT INTO ssh_cli_results (device_id, source, command, status, output_preview, parsed_rows, error_message, collected_at)
VALUES ($1,$2,$3,$4,$5,$6,$7, now())
ON CONFLICT (device_id, source, command) DO UPDATE SET
    status = EXCLUDED.status,
    output_preview = EXCLUDED.output_preview,
    parsed_rows = EXCLUDED.parsed_rows,
    error_message = EXCLUDED.error_message,
    collected_at = now()
`

type UpsertSSHCliResultParams struct {
	DeviceID      uuid.UUID `json:"device_id"`
	Source        string    `json:"source"`
	Command       string    `json:"command"`
	Status        string    `json:"status"`
	OutputPreview string    `json:"output_preview"`
	ParsedRows    int32     `json:"parsed_rows"`
	ErrorMessage  string    `json:"error_message"`
}

func (q *Queries) UpsertSSHCliResult(ctx context.Context, arg UpsertSSHCliResultParams) error {
	_, err := q.db.Exec(ctx, upsertSSHCliResult,
		arg.DeviceID,
		arg.Source,
		arg.Command,
		arg.Status,
		arg.OutputPreview,
		arg.ParsedRows,
		arg.ErrorMessage,
	)
	return err
}
