// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subnets.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const createSubnet = `-- name: CreateSubnet :one
INSERT INTO subnets (location_id, cidr, name, vlan_id)
VALUES ($1, $2, $3, $4)
RETURNING id, location_id, cidr, name, vlan_id, metadata, created_at, updated_at
`

type CreateSubnetParams struct {
	LocationID uuid.UUID    `json:"location_id"`
	Cidr       netip.Prefix `json:"cidr"`
	Name       *string      `json:"name"`
	VlanID     *int32       `json:"vlan_id"`
}

func (q *Queries) CreateSubnet(ctx context.Context, arg CreateSubnetParams) (Subnet, error) {
	row := q.db.QueryRow(ctx, createSubnet,
		arg.LocationID,
		arg.Cidr,
		arg.Name,
		arg.VlanID,
	)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Cidr,
		&i.Name,
		&i.VlanID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubnets = `-- name: ListSubnets :many
SELECT id, location_id, cidr, name, vlan_id, metadata, created_at, updated_at FROM subnets ORDER BY location_id, cidr
`

func (q *Queries) ListSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.Query(ctx, listSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subnet{}
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Cidr,
			&i.Name,
			&i.VlanID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubnetsByLocation = `-- name: ListSubnetsByLocation :many
SELECT id, location_id, cidr, name, vlan_id, metadata, created_at, updated_at FROM subnets WHERE location_id = $1 ORDER BY cidr
`

func (q *Queries) ListSubnetsByLocation(ctx context.Context, locationID uuid.UUID) ([]Subnet, error) {
	rows, err := q.db.Query(ctx, listSubnetsByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subnet{}
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Cidr,
			&i.Name,
			&i.VlanID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
