// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subnet_credentials.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const addSubnetCredential = `-- name: AddSubnetCredential :exec
INSERT INTO subnet_credentials (subnet_id, credential_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSubnetCredentialParams struct {
	SubnetID     uuid.UUID `json:"subnet_id"`
	CredentialID uuid.UUID `json:"credential_id"`
}

func (q *Queries) AddSubnetCredential(ctx context.Context, arg AddSubnetCredentialParams) error {
	_, err := q.db.Exec(ctx, addSubnetCredential, arg.SubnetID, arg.CredentialID)
	return err
}

const clearSubnetCredentials = `-- name: ClearSubnetCredentials :exec
DELETE FROM subnet_credentials WHERE subnet_id = $1
`

func (q *Queries) ClearSubnetCredentials(ctx context.Context, subnetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearSubnetCredentials, subnetID)
	return err
}

const listSubnetCredentials = `-- name: ListSubnetCredentials :many
SELECT c.id, c.name, c.kind
FROM subnet_credentials sc
JOIN credentials c ON c.id = sc.credential_id
WHERE sc.subnet_id = $1
ORDER BY c.kind, c.name
`

type ListSubnetCredentialsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Kind string    `json:"kind"`
}

// Credentials assigned to a subnet (for the editor + indicators).
func (q *Queries) ListSubnetCredentials(ctx context.Context, subnetID uuid.UUID) ([]ListSubnetCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listSubnetCredentials, subnetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubnetCredentialsRow{}
	for rows.Next() {
		var i ListSubnetCredentialsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subnetCredentialCounts = `-- name: SubnetCredentialCounts :many
SELECT s.id AS subnet_id,
       count(sc.credential_id)::bigint AS cred_count,
       COALESCE(array_agg(DISTINCT c.kind) FILTER (WHERE c.kind IS NOT NULL), '{}')::text[] AS kinds
FROM subnets s
LEFT JOIN subnet_credentials sc ON sc.subnet_id = s.id
LEFT JOIN credentials c ON c.id = sc.credential_id
WHERE s.location_id = $1
GROUP BY s.id
`

type SubnetCredentialCountsRow struct {
	SubnetID  uuid.UUID `json:"subnet_id"`
	CredCount int64     `json:"cred_count"`
	Kinds     []string  `json:"kinds"`
}

// Per-subnet assignment count + distinct kinds for a location (UI row badges).
func (q *Queries) SubnetCredentialCounts(ctx context.Context, locationID uuid.UUID) ([]SubnetCredentialCountsRow, error) {
	rows, err := q.db.Query(ctx, subnetCredentialCounts, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubnetCredentialCountsRow{}
	for rows.Next() {
		var i SubnetCredentialCountsRow
		if err := rows.Scan(&i.SubnetID, &i.CredCount, &i.Kinds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subnetScopedCredentialsForIP = `-- name: SubnetScopedCredentialsForIP :many
WITH match AS (
    SELECT s.id, s.name, s.cidr, masklen(s.cidr) AS ml
    FROM subnets s
    WHERE s.cidr >>= $1::inet
      AND EXISTS (SELECT 1 FROM subnet_credentials sc WHERE sc.subnet_id = s.id)
    ORDER BY
      (CASE WHEN $2::uuid IS NOT NULL
             AND s.location_id = $2 THEN 0 ELSE 1 END),
      masklen(s.cidr) DESC
    LIMIT 1
)
SELECT c.id, c.kind, m.name AS subnet_name, (host(m.cidr) || '/' || m.ml)::text AS cidr
FROM match m
JOIN subnet_credentials sc ON sc.subnet_id = m.id
JOIN credentials c ON c.id = sc.credential_id
ORDER BY c.kind
`

type SubnetScopedCredentialsForIPParams struct {
	Ip         netip.Addr `json:"ip"`
	LocationID *uuid.UUID `json:"location_id"`
}

type SubnetScopedCredentialsForIPRow struct {
	ID         uuid.UUID `json:"id"`
	Kind       string    `json:"kind"`
	SubnetName *string   `json:"subnet_name"`
	Cidr       string    `json:"cidr"`
}

// The EXCLUSIVE credential set for the most-specific site subnet that (a) contains
// the IP and (b) has assignments. Empty result ⇒ no subnet scoping ⇒ caller falls
// back to normal resolution.
//
// location_id is a PREFERENCE, NOT a hard filter. The anti-spray/lockout-safety
// contract is "any IP inside an assigned subnet is tried with ONLY that subnet's
// credentials" — independent of which site the operator happened to select for the
// scan. Gating the match on an exact location_id match silently disengaged that
// protection whenever the scan carried a location other than the subnet's own
// (e.g. a child/parent/sibling node, or a different hotel), falling back to
// spraying every stored credential. So we match on the CIDR alone and only use the
// scan's location to break ties between overlapping subnets at different sites:
// a subnet at the scan's location outranks one elsewhere, then narrower mask wins.
func (q *Queries) SubnetScopedCredentialsForIP(ctx context.Context, arg SubnetScopedCredentialsForIPParams) ([]SubnetScopedCredentialsForIPRow, error) {
	rows, err := q.db.Query(ctx, subnetScopedCredentialsForIP, arg.Ip, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubnetScopedCredentialsForIPRow{}
	for rows.Next() {
		var i SubnetScopedCredentialsForIPRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SubnetName,
			&i.Cidr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
