// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: vendor_profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countVendorProfilesUsingCredential = `-- name: CountVendorProfilesUsingCredential :one
SELECT count(*) FROM vendor_connection_profiles WHERE credential_id = $1
`

// How many profiles still reference a credential (for orphan-credential cleanup on
// profile delete).
func (q *Queries) CountVendorProfilesUsingCredential(ctx context.Context, credentialID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorProfilesUsingCredential, credentialID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendorProfile = `-- name: CreateVendorProfile :one

INSERT INTO vendor_connection_profiles (name, vendor_type, target_url, credential_id, location_id, device_id, config, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, vendor_type, target_url, credential_id, location_id, device_id, config, enabled, last_test_at, last_test_ok, last_test_detail, last_collection_at, last_collection_detail, status, created_at, updated_at
`

type CreateVendorProfileParams struct {
	Name         string     `json:"name"`
	VendorType   string     `json:"vendor_type"`
	TargetUrl    string     `json:"target_url"`
	CredentialID *uuid.UUID `json:"credential_id"`
	LocationID   *uuid.UUID `json:"location_id"`
	DeviceID     *uuid.UUID `json:"device_id"`
	Config       []byte     `json:"config"`
	Enabled      bool       `json:"enabled"`
}

// Vendor connection profile CRUD + resolution. No secrets are stored here; the
// credential reference points at the encrypted credentials table.
func (q *Queries) CreateVendorProfile(ctx context.Context, arg CreateVendorProfileParams) (VendorConnectionProfile, error) {
	row := q.db.QueryRow(ctx, createVendorProfile,
		arg.Name,
		arg.VendorType,
		arg.TargetUrl,
		arg.CredentialID,
		arg.LocationID,
		arg.DeviceID,
		arg.Config,
		arg.Enabled,
	)
	var i VendorConnectionProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VendorType,
		&i.TargetUrl,
		&i.CredentialID,
		&i.LocationID,
		&i.DeviceID,
		&i.Config,
		&i.Enabled,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestDetail,
		&i.LastCollectionAt,
		&i.LastCollectionDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVendorProfile = `-- name: DeleteVendorProfile :exec
DELETE FROM vendor_connection_profiles WHERE id = $1
`

func (q *Queries) DeleteVendorProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVendorProfile, id)
	return err
}

const getVendorProfile = `-- name: GetVendorProfile :one
SELECT id, name, vendor_type, target_url, credential_id, location_id, device_id, config, enabled, last_test_at, last_test_ok, last_test_detail, last_collection_at, last_collection_detail, status, created_at, updated_at FROM vendor_connection_profiles WHERE id = $1
`

func (q *Queries) GetVendorProfile(ctx context.Context, id uuid.UUID) (VendorConnectionProfile, error) {
	row := q.db.QueryRow(ctx, getVendorProfile, id)
	var i VendorConnectionProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VendorType,
		&i.TargetUrl,
		&i.CredentialID,
		&i.LocationID,
		&i.DeviceID,
		&i.Config,
		&i.Enabled,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestDetail,
		&i.LastCollectionAt,
		&i.LastCollectionDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorProfileForDeviceVendor = `-- name: GetVendorProfileForDeviceVendor :one
SELECT id, name, vendor_type, target_url, credential_id, location_id, device_id, config, enabled, last_test_at, last_test_ok, last_test_detail, last_collection_at, last_collection_detail, status, created_at, updated_at FROM vendor_connection_profiles
WHERE device_id = $1 AND vendor_type = $2
ORDER BY created_at LIMIT 1
`

type GetVendorProfileForDeviceVendorParams struct {
	DeviceID   *uuid.UUID `json:"device_id"`
	VendorType string     `json:"vendor_type"`
}

// The (device, vendor_type) profile if one exists (any enabled state) — keeps the
// "Add controller" flow idempotent (update in place rather than create a duplicate).
func (q *Queries) GetVendorProfileForDeviceVendor(ctx context.Context, arg GetVendorProfileForDeviceVendorParams) (VendorConnectionProfile, error) {
	row := q.db.QueryRow(ctx, getVendorProfileForDeviceVendor, arg.DeviceID, arg.VendorType)
	var i VendorConnectionProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VendorType,
		&i.TargetUrl,
		&i.CredentialID,
		&i.LocationID,
		&i.DeviceID,
		&i.Config,
		&i.Enabled,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestDetail,
		&i.LastCollectionAt,
		&i.LastCollectionDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendorProfiles = `-- name: ListVendorProfiles :many
SELECT id, name, vendor_type, target_url, credential_id, location_id, device_id, config, enabled, last_test_at, last_test_ok, last_test_detail, last_collection_at, last_collection_detail, status, created_at, updated_at FROM vendor_connection_profiles ORDER BY vendor_type, name
`

func (q *Queries) ListVendorProfiles(ctx context.Context) ([]VendorConnectionProfile, error) {
	rows, err := q.db.Query(ctx, listVendorProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorConnectionProfile{}
	for rows.Next() {
		var i VendorConnectionProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VendorType,
			&i.TargetUrl,
			&i.CredentialID,
			&i.LocationID,
			&i.DeviceID,
			&i.Config,
			&i.Enabled,
			&i.LastTestAt,
			&i.LastTestOk,
			&i.LastTestDetail,
			&i.LastCollectionAt,
			&i.LastCollectionDetail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveVendorProfiles = `-- name: ResolveVendorProfiles :many
SELECT id, name, vendor_type, target_url, credential_id, location_id, device_id, config, enabled, last_test_at, last_test_ok, last_test_detail, last_collection_at, last_collection_detail, status, created_at, updated_at FROM vendor_connection_profiles
WHERE enabled
  AND vendor_type = $1
  AND (device_id = $2 OR location_id = $3 OR (device_id IS NULL AND location_id IS NULL))
ORDER BY (device_id = $2) DESC, (location_id = $3) DESC
`

type ResolveVendorProfilesParams struct {
	VendorType string     `json:"vendor_type"`
	DeviceID   *uuid.UUID `json:"device_id"`
	LocationID *uuid.UUID `json:"location_id"`
}

// Profiles applicable to a device during a scan: a profile bound to this exact
// device, or one bound to this location (site-level), or an unbound global
// profile — for the given vendor_type. Most specific first.
func (q *Queries) ResolveVendorProfiles(ctx context.Context, arg ResolveVendorProfilesParams) ([]VendorConnectionProfile, error) {
	rows, err := q.db.Query(ctx, resolveVendorProfiles, arg.VendorType, arg.DeviceID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorConnectionProfile{}
	for rows.Next() {
		var i VendorConnectionProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VendorType,
			&i.TargetUrl,
			&i.CredentialID,
			&i.LocationID,
			&i.DeviceID,
			&i.Config,
			&i.Enabled,
			&i.LastTestAt,
			&i.LastTestOk,
			&i.LastTestDetail,
			&i.LastCollectionAt,
			&i.LastCollectionDetail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVendorProfileCollection = `-- name: SetVendorProfileCollection :exec
UPDATE vendor_connection_profiles
SET last_collection_at = now(), last_collection_detail = $2, updated_at = now()
WHERE id = $1
`

type SetVendorProfileCollectionParams struct {
	ID                   uuid.UUID `json:"id"`
	LastCollectionDetail string    `json:"last_collection_detail"`
}

func (q *Queries) SetVendorProfileCollection(ctx context.Context, arg SetVendorProfileCollectionParams) error {
	_, err := q.db.Exec(ctx, setVendorProfileCollection, arg.ID, arg.LastCollectionDetail)
	return err
}

const setVendorProfileTest = `-- name: SetVendorProfileTest :exec
UPDATE vendor_connection_profiles
SET last_test_at = now(), last_test_ok = $2, last_test_detail = $3,
    status = CASE WHEN $2 THEN 'ok' ELSE 'failed' END, updated_at = now()
WHERE id = $1
`

type SetVendorProfileTestParams struct {
	ID             uuid.UUID `json:"id"`
	LastTestOk     *bool     `json:"last_test_ok"`
	LastTestDetail string    `json:"last_test_detail"`
}

func (q *Queries) SetVendorProfileTest(ctx context.Context, arg SetVendorProfileTestParams) error {
	_, err := q.db.Exec(ctx, setVendorProfileTest, arg.ID, arg.LastTestOk, arg.LastTestDetail)
	return err
}

const updateVendorProfile = `-- name: UpdateVendorProfile :one
UPDATE vendor_connection_profiles
SET name = $2, vendor_type = $3, target_url = $4, credential_id = $5,
    location_id = $6, device_id = $7, config = $8, enabled = $9, updated_at = now()
WHERE id = $1
RETURNING id, name, vendor_type, target_url, credential_id, location_id, device_id, config, enabled, last_test_at, last_test_ok, last_test_detail, last_collection_at, last_collection_detail, status, created_at, updated_at
`

type UpdateVendorProfileParams struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	VendorType   string     `json:"vendor_type"`
	TargetUrl    string     `json:"target_url"`
	CredentialID *uuid.UUID `json:"credential_id"`
	LocationID   *uuid.UUID `json:"location_id"`
	DeviceID     *uuid.UUID `json:"device_id"`
	Config       []byte     `json:"config"`
	Enabled      bool       `json:"enabled"`
}

func (q *Queries) UpdateVendorProfile(ctx context.Context, arg UpdateVendorProfileParams) (VendorConnectionProfile, error) {
	row := q.db.QueryRow(ctx, updateVendorProfile,
		arg.ID,
		arg.Name,
		arg.VendorType,
		arg.TargetUrl,
		arg.CredentialID,
		arg.LocationID,
		arg.DeviceID,
		arg.Config,
		arg.Enabled,
	)
	var i VendorConnectionProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VendorType,
		&i.TargetUrl,
		&i.CredentialID,
		&i.LocationID,
		&i.DeviceID,
		&i.Config,
		&i.Enabled,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestDetail,
		&i.LastCollectionAt,
		&i.LastCollectionDetail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
