// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: virtualization.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const listVMsByHost = `-- name: ListVMsByHost :many
SELECT id, host_device_id, vm_device_id, name, power_state, vcpu, mem_mb, guest_os, primary_ip, last_seen_at FROM virtual_machines WHERE host_device_id = $1 ORDER BY name
`

func (q *Queries) ListVMsByHost(ctx context.Context, hostDeviceID uuid.UUID) ([]VirtualMachine, error) {
	rows, err := q.db.Query(ctx, listVMsByHost, hostDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VirtualMachine{}
	for rows.Next() {
		var i VirtualMachine
		if err := rows.Scan(
			&i.ID,
			&i.HostDeviceID,
			&i.VmDeviceID,
			&i.Name,
			&i.PowerState,
			&i.Vcpu,
			&i.MemMb,
			&i.GuestOs,
			&i.PrimaryIp,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVM = `-- name: UpsertVM :one
INSERT INTO virtual_machines (host_device_id, vm_device_id, name, power_state, vcpu, mem_mb, guest_os, primary_ip)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (host_device_id, name) DO UPDATE SET
    vm_device_id = EXCLUDED.vm_device_id,
    power_state = EXCLUDED.power_state,
    vcpu = EXCLUDED.vcpu,
    mem_mb = EXCLUDED.mem_mb,
    guest_os = EXCLUDED.guest_os,
    primary_ip = EXCLUDED.primary_ip,
    last_seen_at = now()
RETURNING id, host_device_id, vm_device_id, name, power_state, vcpu, mem_mb, guest_os, primary_ip, last_seen_at
`

type UpsertVMParams struct {
	HostDeviceID uuid.UUID   `json:"host_device_id"`
	VmDeviceID   *uuid.UUID  `json:"vm_device_id"`
	Name         string      `json:"name"`
	PowerState   string      `json:"power_state"`
	Vcpu         *int32      `json:"vcpu"`
	MemMb        *int32      `json:"mem_mb"`
	GuestOs      *string     `json:"guest_os"`
	PrimaryIp    *netip.Addr `json:"primary_ip"`
}

// Upsert keyed on (host, name): re-collecting refreshes state without dups.
func (q *Queries) UpsertVM(ctx context.Context, arg UpsertVMParams) (VirtualMachine, error) {
	row := q.db.QueryRow(ctx, upsertVM,
		arg.HostDeviceID,
		arg.VmDeviceID,
		arg.Name,
		arg.PowerState,
		arg.Vcpu,
		arg.MemMb,
		arg.GuestOs,
		arg.PrimaryIp,
	)
	var i VirtualMachine
	err := row.Scan(
		&i.ID,
		&i.HostDeviceID,
		&i.VmDeviceID,
		&i.Name,
		&i.PowerState,
		&i.Vcpu,
		&i.MemMb,
		&i.GuestOs,
		&i.PrimaryIp,
		&i.LastSeenAt,
	)
	return i, err
}
