// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: web_ports.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWebPortCandidate = `-- name: CreateWebPortCandidate :one
INSERT INTO web_port_candidates (port, scheme, enabled, note)
VALUES ($1, $2, $3, $4)
RETURNING id, port, scheme, enabled, note, created_at
`

type CreateWebPortCandidateParams struct {
	Port    int32  `json:"port"`
	Scheme  string `json:"scheme"`
	Enabled bool   `json:"enabled"`
	Note    string `json:"note"`
}

func (q *Queries) CreateWebPortCandidate(ctx context.Context, arg CreateWebPortCandidateParams) (WebPortCandidate, error) {
	row := q.db.QueryRow(ctx, createWebPortCandidate,
		arg.Port,
		arg.Scheme,
		arg.Enabled,
		arg.Note,
	)
	var i WebPortCandidate
	err := row.Scan(
		&i.ID,
		&i.Port,
		&i.Scheme,
		&i.Enabled,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebPortCandidate = `-- name: DeleteWebPortCandidate :exec
DELETE FROM web_port_candidates WHERE id = $1
`

func (q *Queries) DeleteWebPortCandidate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebPortCandidate, id)
	return err
}

const listEnabledWebPortCandidates = `-- name: ListEnabledWebPortCandidates :many
SELECT id, port, scheme, enabled, note, created_at FROM web_port_candidates WHERE enabled ORDER BY port
`

func (q *Queries) ListEnabledWebPortCandidates(ctx context.Context) ([]WebPortCandidate, error) {
	rows, err := q.db.Query(ctx, listEnabledWebPortCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebPortCandidate{}
	for rows.Next() {
		var i WebPortCandidate
		if err := rows.Scan(
			&i.ID,
			&i.Port,
			&i.Scheme,
			&i.Enabled,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebPortCandidates = `-- name: ListWebPortCandidates :many
SELECT id, port, scheme, enabled, note, created_at FROM web_port_candidates ORDER BY port
`

func (q *Queries) ListWebPortCandidates(ctx context.Context) ([]WebPortCandidate, error) {
	rows, err := q.db.Query(ctx, listWebPortCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebPortCandidate{}
	for rows.Next() {
		var i WebPortCandidate
		if err := rows.Scan(
			&i.ID,
			&i.Port,
			&i.Scheme,
			&i.Enabled,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebPortCandidate = `-- name: UpdateWebPortCandidate :one
UPDATE web_port_candidates
SET port = $2, scheme = $3, enabled = $4, note = $5
WHERE id = $1
RETURNING id, port, scheme, enabled, note, created_at
`

type UpdateWebPortCandidateParams struct {
	ID      uuid.UUID `json:"id"`
	Port    int32     `json:"port"`
	Scheme  string    `json:"scheme"`
	Enabled bool      `json:"enabled"`
	Note    string    `json:"note"`
}

func (q *Queries) UpdateWebPortCandidate(ctx context.Context, arg UpdateWebPortCandidateParams) (WebPortCandidate, error) {
	row := q.db.QueryRow(ctx, updateWebPortCandidate,
		arg.ID,
		arg.Port,
		arg.Scheme,
		arg.Enabled,
		arg.Note,
	)
	var i WebPortCandidate
	err := row.Scan(
		&i.ID,
		&i.Port,
		&i.Scheme,
		&i.Enabled,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
