// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: wireless.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const getWLANControllerInfo = `-- name: GetWLANControllerInfo :one
SELECT device_id, vendor, version, ap_count, client_count, last_seen_at FROM wlan_controller_info WHERE device_id = $1
`

func (q *Queries) GetWLANControllerInfo(ctx context.Context, deviceID uuid.UUID) (WlanControllerInfo, error) {
	row := q.db.QueryRow(ctx, getWLANControllerInfo, deviceID)
	var i WlanControllerInfo
	err := row.Scan(
		&i.DeviceID,
		&i.Vendor,
		&i.Version,
		&i.ApCount,
		&i.ClientCount,
		&i.LastSeenAt,
	)
	return i, err
}

const listAccessPoints = `-- name: ListAccessPoints :many
SELECT id, controller_device_id, name, mac, model, ip, status, client_count, last_seen_at FROM access_points WHERE controller_device_id = $1 ORDER BY name
`

func (q *Queries) ListAccessPoints(ctx context.Context, controllerDeviceID uuid.UUID) ([]AccessPoint, error) {
	rows, err := q.db.Query(ctx, listAccessPoints, controllerDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessPoint{}
	for rows.Next() {
		var i AccessPoint
		if err := rows.Scan(
			&i.ID,
			&i.ControllerDeviceID,
			&i.Name,
			&i.Mac,
			&i.Model,
			&i.Ip,
			&i.Status,
			&i.ClientCount,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccessPoint = `-- name: UpsertAccessPoint :one
INSERT INTO access_points (controller_device_id, name, mac, model, ip, status, client_count)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (controller_device_id, name) DO UPDATE SET
    mac = EXCLUDED.mac,
    model = EXCLUDED.model,
    ip = EXCLUDED.ip,
    status = EXCLUDED.status,
    client_count = EXCLUDED.client_count,
    last_seen_at = now()
RETURNING id, controller_device_id, name, mac, model, ip, status, client_count, last_seen_at
`

type UpsertAccessPointParams struct {
	ControllerDeviceID uuid.UUID   `json:"controller_device_id"`
	Name               string      `json:"name"`
	Mac                *string     `json:"mac"`
	Model              *string     `json:"model"`
	Ip                 *netip.Addr `json:"ip"`
	Status             string      `json:"status"`
	ClientCount        int32       `json:"client_count"`
}

func (q *Queries) UpsertAccessPoint(ctx context.Context, arg UpsertAccessPointParams) (AccessPoint, error) {
	row := q.db.QueryRow(ctx, upsertAccessPoint,
		arg.ControllerDeviceID,
		arg.Name,
		arg.Mac,
		arg.Model,
		arg.Ip,
		arg.Status,
		arg.ClientCount,
	)
	var i AccessPoint
	err := row.Scan(
		&i.ID,
		&i.ControllerDeviceID,
		&i.Name,
		&i.Mac,
		&i.Model,
		&i.Ip,
		&i.Status,
		&i.ClientCount,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertWLANControllerInfo = `-- name: UpsertWLANControllerInfo :one
INSERT INTO wlan_controller_info (device_id, vendor, version, ap_count, client_count)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (device_id) DO UPDATE SET
    vendor = EXCLUDED.vendor,
    version = EXCLUDED.version,
    ap_count = EXCLUDED.ap_count,
    client_count = EXCLUDED.client_count,
    last_seen_at = now()
RETURNING device_id, vendor, version, ap_count, client_count, last_seen_at
`

type UpsertWLANControllerInfoParams struct {
	DeviceID    uuid.UUID `json:"device_id"`
	Vendor      *string   `json:"vendor"`
	Version     *string   `json:"version"`
	ApCount     int32     `json:"ap_count"`
	ClientCount int32     `json:"client_count"`
}

func (q *Queries) UpsertWLANControllerInfo(ctx context.Context, arg UpsertWLANControllerInfoParams) (WlanControllerInfo, error) {
	row := q.db.QueryRow(ctx, upsertWLANControllerInfo,
		arg.DeviceID,
		arg.Vendor,
		arg.Version,
		arg.ApCount,
		arg.ClientCount,
	)
	var i WlanControllerInfo
	err := row.Scan(
		&i.DeviceID,
		&i.Vendor,
		&i.Version,
		&i.ApCount,
		&i.ClientCount,
		&i.LastSeenAt,
	)
	return i, err
}
